### ISSUE TITLE
macro_china_cpi_yearly missing forecast values

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#10]
您好，

中国宏观数据cpi好像缺少预测值。
macro_china_cpi_yearly 和 macro_china_cpi_monthly 都有这个问题。估计其他类似函数也有这个问题。
这是数据源的截图：
![image](https://user-images.githubusercontent.com/359830/73907095-07dcb380-48e0-11ea-99e4-6cd2afcd7f8f.png)
![image](https://user-images.githubusercontent.com/359830/73907113-1a56ed00-48e0-11ea-91c2-4e73e2476d17.png)

这个预测值应该是很重要的。

**Comment by jindaxiang** [comment]
> 预测值：国际不同金融机构针对不同类型数据会展开独立的预期调查，金十数据发布的数据预期值通常引自路透社;

这个预测值是单个机构预测的，不具备普适性，所以没有计划获取预测值的数据

**Comment by edwardsun** [comment]
请问有没有可能做成默认=cpi历史值，但如果加参数就可以同时抓取预测值？

**Comment by jindaxiang** [comment]
> 请问有没有可能做成默认=cpi历史值，但如果加参数就可以同时抓取预测值？

因为很多其他类似的接口没用预测值，批量修改不显示，建议您在使用的时候修改下源码部分获取

**Comment by edwardsun** [comment]
谢谢。有没有什么参考？

**Comment by jindaxiang** [comment]
def macro_china_cpi_yearly():
    """
    中国年度CPI数据, 数据区间从19860201-至今
    https://datacenter.jin10.com/reportType/dc_chinese_cpi_yoy
    :return: pandas.Series
    """
    t = time.time()
    res = requests.get(
        JS_CHINA_CPI_YEARLY_URL.format(
            str(int(round(t * 1000))), str(int(round(t * 1000)) + 90)
        )
    )
    json_data = json.loads(res.text[res.text.find("{") : res.text.rfind("}") + 1])
    date_list = [item["date"] for item in json_data["list"]]
    value_list = [item["datas"]["中国CPI年率报告"] for item in json_data["list"]]
    value_df = pd.DataFrame(value_list)
    value_df.columns = json_data["kinds"]
    value_df.index = pd.to_datetime(date_list)
    temp_df = value_df["今值(%)"]  # just fix 今值(%) --> 预测值(%)
    temp_df.name = "cpi"
    return temp_df

**Comment by jindaxiang** [comment]
# just fix 今值(%) --> 预测值(%)

**Comment by edwardsun** [comment]
thanks!
