### ISSUE TITLE
基金分红拆分数据

### ISSUE THREAD

**Issue by aforwardz** [jindaxiang/akshare#1011]
目前关于这部分数据开源的比较少，个别api商城有，天天基金似乎没看到有相关开放接口，这部分数据不知道哪里可以获取到

希望能增加这部分数据

**Comment by jindaxiang** [comment]
> 目前关于这部分数据开源的比较少，个别api商城有，天天基金似乎没看到有相关开放接口，这部分数据不知道哪里可以获取到
> 
> 希望能增加这部分数据

暂时没有合适的数据源
