### ISSUE TITLE
stock_financial_analysis_indicator接口会偶尔中断，且不报异常，程序就处于假死状态

### ISSUE THREAD

**Issue by harryhan1989** [jindaxiang/akshare#1027]
我设置遍历定期遍历所有股票，调用stock_financial_analysis_indicator接口抓取财务指标数据，基本上都是执行一段时间后就程序假死了，通过日志看是stock_financial_analysis_indicator这个方法假死不继续执行了，程序进程还在，但不能继续执行。猜测可能是爬虫网络请求出问题，且没有做异常或超时处理造成一直等待

**Comment by harryhan1989** [comment]
同样现象极偶尔也会出现在stock_zh_a_spot这个接口上（这个接口出现频率极低），这个接口我是基本上交易日1分钟执行一次的，稳定运行多天后，只在一天里出现过一次，调用此接口也出现假死现象，猜测可能原因类似

**Comment by jindaxiang** [comment]
> stock_financial_analysis_indicator

适当控制下载的频率

**Comment by fujiawei-dev** [comment]
为什么不添加超时，适当控制频率不太好把握

**Comment by jindaxiang** [comment]
> 为什么不添加超时，适当控制频率不太好把握

我测试下
