### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by simplein** [jindaxiang/akshare#1033]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
windows10 20H2 (19042.804)
2. Python 版本
python3.8.5
3. AkShare 版本
0.8.28
4. 接口的名称和代码
import akshare as ak
stock_financial_report_sina_df = ak.stock_financial_report_sina(stock="600004", symbol="现金流量表")
print(stock_financial_report_sina_df)
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/23433828/110049575-0ef91e00-7d8d-11eb-8cb8-d192237ffad1.png)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\akshare\stock_fundamental\stock_finance.py", line 39, in stock_financial_report_sina
    temp_df = pd.read_table(BytesIO(r.content), encoding="gb2312", header=None).iloc[:, :-2]
  File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 765, in read_table
    return read_csv(**locals())
  File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 537, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 808, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 2034, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe6 in position 137: illegal multibyte sequence
6. 期望获得的正确结果
使用的是文档的案例，应该获得文档数据
        报表日期 单位 一、经营活动产生的现金流量  ... 现金等价物的期末余额 现金等价物的期初余额   现金及现金等价物的净增加额
1   20200930  元           NaN  ...          0          0               0
2   20200630  元           NaN  ...          0          0     11724335.23
3   20200331  元           NaN  ...          0          0               0
4   20191231  元           NaN  ...          0          0  -1044254625.00
5   20190930  元           NaN  ...          0          0               0
..       ... ..           ...  ...        ...        ...             ...
69  20030930  元           NaN  ...          0          0    -83266325.50
70  20030630  元           NaN  ...          0          0   -143509055.17
71  20030331  元           NaN  ...          0          0    115220322.31
72  20021231  元           NaN  ...          0          0    110751837.42
73  20020630  元           NaN  ...          0          0               0

注1：该接口的问题不是一直发生，似乎和时间有关系。这次递交的错误时间为2021年3月5日上午8点20分左右运行。但是前一天晚上11点运行有正常结果。

注2：上午8点50分，在ipython中运行，又有时正常，有时候不正常。前面几个股票代码都正常，但是运行一些到股票代码000156的时候又出错。该股票代码不是固定。
===========代码===============
import pandas as pd
from datetime import datetime
import akshare as ak
day='20210304'
def get_stock_financereport_all(): 
    day = datetime.today().strftime('%Y%m%d')
    stock_info_a_code_name_df = ak.stock_info_a_code_name()
    df_balance=pd.DataFrame(); df_income=pd.DataFrame(); df_cashflow=pd.DataFrame()
    for s in stock_info_a_code_name_df['code'].values.tolist():
        print(s)
        # print(s, end='\r')
        stock_financial_report_balance_sina_df = ak.stock_financial_report_sina(stock=s, symbol="资产负债表")
        stock_financial_report_income_sina_df = ak.stock_financial_report_sina(stock=s, symbol="利润表")
        stock_financial_report_cashflow_sina_df = ak.stock_financial_report_sina(stock=s, symbol="现金流量表")
print(datetime.now())
get_stock_financereport_all()
==========记录=================
已开启 'Python 3.8.5 64-bit (conda)' 内核
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

000155
000156

UnicodeDecodeError                        Traceback (most recent call last)
d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in 
    183 # get_akdata_swindex_alldaily('20140101',day)
    184 # get_akdata_swindex_cons_hist()
--> 185 get_stock_financereport_all()
    186 print(datetime.now())

d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in get_stock_financereport_all()
    154         print(s)
    155         # print(s, end='\r')
--> 156         stock_financial_report_balance_sina_df = ak.stock_financial_report_sina(stock=s, symbol="资产负债表")
    157         stock_financial_report_income_sina_df = ak.stock_financial_report_sina(stock=s, symbol="利润表")
    158         stock_financial_report_cashflow_sina_df = ak.stock_financial_report_sina(stock=s, symbol="现金流量表")

~\anaconda3\lib\site-packages\akshare\stock_fundamental\stock_finance.py in stock_financial_report_sina(stock, symbol)
     37         url = f"http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/{stock}/ctrl/all.phtml"  # 现金流量表
     38     r = requests.get(url)
---> 39     temp_df = pd.read_table(BytesIO(r.content), encoding="gb2312", header=None).iloc[:, :-2]
     40     temp_df = temp_df.T
     41     temp_df.columns = temp_df.iloc[0, :]

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_table(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    763         # default to avoid a ValueError
    764         sep = ","
--> 765     return read_csv(**locals())
    766 
    767 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    684     )
    685 
--> 686     return _read(filepath_or_buffer, kwds)
    687 
    688 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    450 
    451     # Create the parser.
--> 452     parser = TextFileReader(fp_or_buf, **kwds)
    453 
    454     if chunksize or iterator:

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    944             self.options["has_index_names"] = kwds["has_index_names"]
    945 
--> 946         self._make_engine(self.engine)
    947 
    948     def close(self):

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1176     def _make_engine(self, engine="c"):
   1177         if engine == "c":
-> 1178             self._engine = CParserWrapper(self.f, **self.options)
   1179         else:
   1180             if engine == "python":

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   2006         kwds["usecols"] = self.usecols
   2007 
-> 2008         self._reader = parsers.TextReader(src, **kwds)
   2009         self.unnamed_cols = self._reader.unnamed_cols
   2010 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._get_header()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()

UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe6 in position 137: illegal multibyte sequence

注3：重新运行ipython以上代码 , 立刻出错

=======错误记录==========

2021-03-05 08:57:00.874590
000001

UnicodeDecodeError                        Traceback (most recent call last)
d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in 
    183 # get_akdata_swindex_alldaily('20140101',day)
    184 # get_akdata_swindex_cons_hist()
--> 185 get_stock_financereport_all()
    186 print(datetime.now())

d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in get_stock_financereport_all()
    154         print(s)
    155         # print(s, end='\r')
--> 156         stock_financial_report_balance_sina_df = ak.stock_financial_report_sina(stock=s, symbol="资产负债表")
    157         stock_financial_report_income_sina_df = ak.stock_financial_report_sina(stock=s, symbol="利润表")
    158         stock_financial_report_cashflow_sina_df = ak.stock_financial_report_sina(stock=s, symbol="现金流量表")

~\anaconda3\lib\site-packages\akshare\stock_fundamental\stock_finance.py in stock_financial_report_sina(stock, symbol)
     37         url = f"http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/{stock}/ctrl/all.phtml"  # 现金流量表
     38     r = requests.get(url)
---> 39     temp_df = pd.read_table(BytesIO(r.content), encoding="gb2312", header=None).iloc[:, :-2]
     40     temp_df = temp_df.T
     41     temp_df.columns = temp_df.iloc[0, :]

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_table(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    763         # default to avoid a ValueError
    764         sep = ","
--> 765     return read_csv(**locals())
    766 
    767 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    684     )
    685 
--> 686     return _read(filepath_or_buffer, kwds)
    687 
    688 

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    450 
    451     # Create the parser.
--> 452     parser = TextFileReader(fp_or_buf, **kwds)
    453 
    454     if chunksize or iterator:

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    944             self.options["has_index_names"] = kwds["has_index_names"]
    945 
--> 946         self._make_engine(self.engine)
    947 
    948     def close(self):

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1176     def _make_engine(self, engine="c"):
   1177         if engine == "c":
-> 1178             self._engine = CParserWrapper(self.f, **self.options)
   1179         else:
   1180             if engine == "python":

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   2006         kwds["usecols"] = self.usecols
   2007 
-> 2008         self._reader = parsers.TextReader(src, **kwds)
   2009         self.unnamed_cols = self._reader.unnamed_cols
   2010 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._get_header()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

pandas\_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()

UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe6 in position 137: illegal multibyte sequence

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    windows10 20H2 (19042.804)
> 2. Python 版本
>    python3.8.5
> 3. AkShare 版本
>    0.8.28
> 4. 接口的名称和代码
>    import akshare as ak
>    stock_financial_report_sina_df = ak.stock_financial_report_sina(stock="600004", symbol="现金流量表")
>    print(stock_financial_report_sina_df)
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/23433828/110049575-0ef91e00-7d8d-11eb-8cb8-d192237ffad1.png)
>    Traceback (most recent call last):
>    File "", line 1, in 
>    File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\akshare\stock_fundamental\stock_finance.py", line 39, in stock_financial_report_sina
>    temp_df = pd.read_table(BytesIO(r.content), encoding="gb2312", header=None).iloc[:, :-2]
>    File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 765, in read_table
>    return read_csv(**locals())
>    File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
>    return _read(filepath_or_buffer, kwds)
>    File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 452, in _read
>    parser = TextFileReader(fp_or_buf, **kwds)
>    File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 946, in **init**
>    self._make_engine(self.engine)
>    File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 1178, in _make_engine
>    self._engine = CParserWrapper(self.f, **self.options)
>    File "C:\Users\wuxiaodong\anaconda3\lib\site-packages\pandas\io\parsers.py", line 2008, in **init**
>    self._reader = parsers.TextReader(src, **kwds)
>    File "pandas_libs\parsers.pyx", line 537, in pandas._libs.parsers.TextReader.**cinit**
>    File "pandas_libs\parsers.pyx", line 808, in pandas._libs.parsers.TextReader._get_header
>    File "pandas_libs\parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
>    File "pandas_libs\parsers.pyx", line 2034, in pandas._libs.parsers.raise_parser_error
>    UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe6 in position 137: illegal multibyte sequence
> 6. 期望获得的正确结果
>    使用的是文档的案例，应该获得文档数据
>    报表日期 单位 一、经营活动产生的现金流量  ... 现金等价物的期末余额 现金等价物的期初余额   现金及现金等价物的净增加额
>    1   20200930  元           NaN  ...          0          0               0
>    2   20200630  元           NaN  ...          0          0     11724335.23
>    3   20200331  元           NaN  ...          0          0               0
>    4   20191231  元           NaN  ...          0          0  -1044254625.00
>    5   20190930  元           NaN  ...          0          0               0
>    ..       ... ..           ...  ...        ...        ...             ...
>    69  20030930  元           NaN  ...          0          0    -83266325.50
>    70  20030630  元           NaN  ...          0          0   -143509055.17
>    71  20030331  元           NaN  ...          0          0    115220322.31
>    72  20021231  元           NaN  ...          0          0    110751837.42
>    73  20020630  元           NaN  ...          0          0               0
> 
> 注1：该接口的问题不是一直发生，似乎和时间有关系。这次递交的错误时间为2021年3月5日上午8点20分左右运行。但是前一天晚上11点运行有正常结果。
> 
> 注2：上午8点50分，在ipython中运行，又有时正常，有时候不正常。前面几个股票代码都正常，但是运行一些到股票代码000156的时候又出错。该股票代码不是固定。
> ===========代码===============
> import pandas as pd
> from datetime import datetime
> import akshare as ak
> day='20210304'
> def get_stock_financereport_all():
> day = datetime.today().strftime('%Y%m%d')
> stock_info_a_code_name_df = ak.stock_info_a_code_name()
> df_balance=pd.DataFrame(); df_income=pd.DataFrame(); df_cashflow=pd.DataFrame()
> for s in stock_info_a_code_name_df['code'].values.tolist():
> print(s)
> # print(s, end='\r')
> stock_financial_report_balance_sina_df = ak.stock_financial_report_sina(stock=s, symbol="资产负债表")
> stock_financial_report_income_sina_df = ak.stock_financial_report_sina(stock=s, symbol="利润表")
> stock_financial_report_cashflow_sina_df = ak.stock_financial_report_sina(stock=s, symbol="现金流量表")
> print(datetime.now())
> get_stock_financereport_all()
> ==========记录=================
> 已开启 'Python 3.8.5 64-bit (conda)' 内核
> Python 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> 000155
> 000156
> 
> UnicodeDecodeError Traceback (most recent call last)
> d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in
> 183 # get_akdata_swindex_alldaily('20140101',day)
> 184 # get_akdata_swindex_cons_hist()
> --> 185 get_stock_financereport_all()
> 186 print(datetime.now())
> 
> d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in get_stock_financereport_all()
> 154 print(s)
> 155 # print(s, end='\r')
> --> 156 stock_financial_report_balance_sina_df = ak.stock_financial_report_sina(stock=s, symbol="资产负债表")
> 157 stock_financial_report_income_sina_df = ak.stock_financial_report_sina(stock=s, symbol="利润表")
> 158 stock_financial_report_cashflow_sina_df = ak.stock_financial_report_sina(stock=s, symbol="现金流量表")
> 
> ~\anaconda3\lib\site-packages\akshare\stock_fundamental\stock_finance.py in stock_financial_report_sina(stock, symbol)
> 37 url = f"[http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/{stock}/ctrl/all.phtml](http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/%7Bstock%7D/ctrl/all.phtml)" # 现金流量表
> 38 r = requests.get(url)
> ---> 39 temp_df = pd.read_table(BytesIO(r.content), encoding="gb2312", header=None).iloc[:, :-2]
> 40 temp_df = temp_df.T
> 41 temp_df.columns = temp_df.iloc[0, :]
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_table(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
> 763 # default to avoid a ValueError
> 764 sep = ","
> --> 765 return read_csv(**locals())
> 766
> 767
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
> 684 )
> 685
> --> 686 return _read(filepath_or_buffer, kwds)
> 687
> 688
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
> 450
> 451 # Create the parser.
> --> 452 parser = TextFileReader(fp_or_buf, **kwds)
> 453
> 454 if chunksize or iterator:
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in **init**(self, f, engine, **kwds)
> 944 self.options["has_index_names"] = kwds["has_index_names"]
> 945
> --> 946 self._make_engine(self.engine)
> 947
> 948 def close(self):
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
> 1176 def _make_engine(self, engine="c"):
> 1177 if engine == "c":
> -> 1178 self._engine = CParserWrapper(self.f, **self.options)
> 1179 else:
> 1180 if engine == "python":
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in **init**(self, src, **kwds)
> 2006 kwds["usecols"] = self.usecols
> 2007
> -> 2008 self._reader = parsers.TextReader(src, **kwds)
> 2009 self.unnamed_cols = self._reader.unnamed_cols
> 2010
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.TextReader.**cinit**()
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.TextReader._get_header()
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()
> 
> UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe6 in position 137: illegal multibyte sequence
> 
> 注3：重新运行ipython以上代码 , 立刻出错
> 
> =======错误记录==========
> 
> 2021-03-05 08:57:00.874590
> 000001
> 
> UnicodeDecodeError Traceback (most recent call last)
> d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in
> 183 # get_akdata_swindex_alldaily('20140101',day)
> 184 # get_akdata_swindex_cons_hist()
> --> 185 get_stock_financereport_all()
> 186 print(datetime.now())
> 
> d:\codes\QuantsLocal\GOQPY\datacollection\bin\collectrawdata.py in get_stock_financereport_all()
> 154 print(s)
> 155 # print(s, end='\r')
> --> 156 stock_financial_report_balance_sina_df = ak.stock_financial_report_sina(stock=s, symbol="资产负债表")
> 157 stock_financial_report_income_sina_df = ak.stock_financial_report_sina(stock=s, symbol="利润表")
> 158 stock_financial_report_cashflow_sina_df = ak.stock_financial_report_sina(stock=s, symbol="现金流量表")
> 
> ~\anaconda3\lib\site-packages\akshare\stock_fundamental\stock_finance.py in stock_financial_report_sina(stock, symbol)
> 37 url = f"[http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/{stock}/ctrl/all.phtml](http://money.finance.sina.com.cn/corp/go.php/vDOWN_CashFlow/displaytype/4/stockid/%7Bstock%7D/ctrl/all.phtml)" # 现金流量表
> 38 r = requests.get(url)
> ---> 39 temp_df = pd.read_table(BytesIO(r.content), encoding="gb2312", header=None).iloc[:, :-2]
> 40 temp_df = temp_df.T
> 41 temp_df.columns = temp_df.iloc[0, :]
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_table(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
> 763 # default to avoid a ValueError
> 764 sep = ","
> --> 765 return read_csv(**locals())
> 766
> 767
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
> 684 )
> 685
> --> 686 return _read(filepath_or_buffer, kwds)
> 687
> 688
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
> 450
> 451 # Create the parser.
> --> 452 parser = TextFileReader(fp_or_buf, **kwds)
> 453
> 454 if chunksize or iterator:
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in **init**(self, f, engine, **kwds)
> 944 self.options["has_index_names"] = kwds["has_index_names"]
> 945
> --> 946 self._make_engine(self.engine)
> 947
> 948 def close(self):
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
> 1176 def _make_engine(self, engine="c"):
> 1177 if engine == "c":
> -> 1178 self._engine = CParserWrapper(self.f, **self.options)
> 1179 else:
> 1180 if engine == "python":
> 
> ~\anaconda3\lib\site-packages\pandas\io\parsers.py in **init**(self, src, **kwds)
> 2006 kwds["usecols"] = self.usecols
> 2007
> -> 2008 self._reader = parsers.TextReader(src, **kwds)
> 2009 self.unnamed_cols = self._reader.unnamed_cols
> 2010
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.TextReader.**cinit**()
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.TextReader._get_header()
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()
> 
> pandas_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()
> 
> UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe6 in position 137: illegal multibyte sequence

目前测试不能复现所反馈的问题，猜测可以是由于连续访问的缘故，建议在每次访问接口时增加 5 秒以上的时间间隔
