### ISSUE TITLE
akshare无法正常关闭

### ISSUE THREAD

**Issue by beesound** [jindaxiang/akshare#1035]
**描述遇到的问题**
1. 操作系统版本: win7
2. Python 版本:   3.74
3. AkShare 版本  ：Version: 0.8.28
4. 接口的名称和代码：
import akshare as ak
macro_china_shrzgm_df = ak.macro_china_shrzgm()
print(macro_china_shrzgm_df)
macro_china_shrzgm_df.to_excel('macro_data.xlsx')
5. 接口报错的截图或代码
通过pycharm运行程序启动后无法结束，而且无法手动结束程序运行，就像卡死了一样。

**Comment by jindaxiang** [comment]
> 4\. macro_china_shrzgm

可以正常运行，应该是您本地环境设置的问题
