### ISSUE TITLE
get_shfe_daily 函数，json.loads报错

### ISSUE THREAD

**Issue by Chandlercjy** [jindaxiang/akshare#1039]
调用futures_daily_bar.py中的函数爬取交易所的历史行情数据：
get_shfe_daily("20040625")

会导致错误
    raise JSONDecodeError("Expecting value", s, err.value) from None

建议添加错误处理警告，避免爬取数据时强行中断程序运行
```python

def get_shfe_daily(date="20131016"):
    """
    上海期货交易所-日频率-量价数据
    :param date: 日期 format：YYYY-MM-DD 或 YYYYMMDD 或 datetime.date对象, 默认为当前交易日
    :type date: str or datetime.date
    :return: 上海期货交易所-日频率-量价数据
    :rtype: pandas.DataFrame or None
    上期所日交易数据(DataFrame):
    symbol        合约代码
    date          日期
    open          开盘价
    high          最高价
    low           最低价
    close         收盘价
    volume        成交量
    open_interest 持仓量
    turnover      成交额
    settle        结算价
    pre_settle     前结算价
    variety       合约类别
    或 None(给定交易日没有交易数据)
    """

    day = cons.convert_date(date) if date is not None else datetime.date.today()
    if day.strftime("%Y%m%d") not in calendar:
        warnings.warn("%s非交易日" % day.strftime("%Y%m%d"))
        return None
    try:
        json_data = json.loads(
            requests_link(
                cons.SHFE_DAILY_URL % (day.strftime("%Y%m%d")),
                headers=cons.shfe_headers,
            ).text
        )
    except requests.HTTPError as reason:
        if reason.response != 404:
            print(cons.SHFE_DAILY_URL % (day.strftime("%Y%m%d")), reason)
        return
    # 添加json解码错误处理
    except json.decoder.JSONDecodeError as e:
        print(f"ERROR: Download Failed for {date=} {e=} ")
        return

    if len(json_data["o_curinstrument"]) == 0:
        return

    df = pd.DataFrame(
        [
            row
            for row in json_data["o_curinstrument"]
            if row["DELIVERYMONTH"] not in ["小计", "合计"] and row["DELIVERYMONTH"] != ""
        ]
    )
    df["variety"] = df.PRODUCTID.str.slice(0, -6).str.upper()
    df["symbol"] = df["variety"] + df["DELIVERYMONTH"]
    df["date"] = day.strftime("%Y%m%d")
    v_wap_df = get_shfe_v_wap(day)
    if v_wap_df is not None:
        df = pd.merge(
            df,
            v_wap_df[v_wap_df.time_range == "9:00-15:00"],
            on=["date", "symbol"],
            how="left",
        )
        df["turnover"] = df.v_wap * df.VOLUME
    else:
        df["VOLUME"] = df["VOLUME"].apply(lambda x: 0 if x == "" else x)
        df["turnover"] = df["VOLUME"] * df["SETTLEMENTPRICE"]
    df.rename(columns=cons.SHFE_COLUMNS, inplace=True)
    return df[cons.OUTPUT_COLUMNS]


```

**Comment by jindaxiang** [comment]
> 调用futures_daily_bar.py中的函数爬取交易所的历史行情数据：
> get_shfe_daily("20040625")
> 
> 会导致错误
> raise JSONDecodeError("Expecting value", s, err.value) from None
> 
> 建议添加错误处理警告，避免爬取数据时强行中断程序运行
> 
> ```python
> def get_shfe_daily(date="20131016"):
>     """
>     上海期货交易所-日频率-量价数据
>     :param date: 日期 format：YYYY-MM-DD 或 YYYYMMDD 或 datetime.date对象, 默认为当前交易日
>     :type date: str or datetime.date
>     :return: 上海期货交易所-日频率-量价数据
>     :rtype: pandas.DataFrame or None
>     上期所日交易数据(DataFrame):
>     symbol        合约代码
>     date          日期
>     open          开盘价
>     high          最高价
>     low           最低价
>     close         收盘价
>     volume        成交量
>     open_interest 持仓量
>     turnover      成交额
>     settle        结算价
>     pre_settle     前结算价
>     variety       合约类别
>     或 None(给定交易日没有交易数据)
>     """
> 
>     day = cons.convert_date(date) if date is not None else datetime.date.today()
>     if day.strftime("%Y%m%d") not in calendar:
>         warnings.warn("%s非交易日" % day.strftime("%Y%m%d"))
>         return None
>     try:
>         json_data = json.loads(
>             requests_link(
>                 cons.SHFE_DAILY_URL % (day.strftime("%Y%m%d")),
>                 headers=cons.shfe_headers,
>             ).text
>         )
>     except requests.HTTPError as reason:
>         if reason.response != 404:
>             print(cons.SHFE_DAILY_URL % (day.strftime("%Y%m%d")), reason)
>         return
>     # 添加json解码错误处理
>     except json.decoder.JSONDecodeError as e:
>         print(f"ERROR: Download Failed for {date=} {e=} ")
>         return
> 
>     if len(json_data["o_curinstrument"]) == 0:
>         return
> 
>     df = pd.DataFrame(
>         [
>             row
>             for row in json_data["o_curinstrument"]
>             if row["DELIVERYMONTH"] not in ["小计", "合计"] and row["DELIVERYMONTH"] != ""
>         ]
>     )
>     df["variety"] = df.PRODUCTID.str.slice(0, -6).str.upper()
>     df["symbol"] = df["variety"] + df["DELIVERYMONTH"]
>     df["date"] = day.strftime("%Y%m%d")
>     v_wap_df = get_shfe_v_wap(day)
>     if v_wap_df is not None:
>         df = pd.merge(
>             df,
>             v_wap_df[v_wap_df.time_range == "9:00-15:00"],
>             on=["date", "symbol"],
>             how="left",
>         )
>         df["turnover"] = df.v_wap * df.VOLUME
>     else:
>         df["VOLUME"] = df["VOLUME"].apply(lambda x: 0 if x == "" else x)
>         df["turnover"] = df["VOLUME"] * df["SETTLEMENTPRICE"]
>     df.rename(columns=cons.SHFE_COLUMNS, inplace=True)
>     return df[cons.OUTPUT_COLUMNS]
> ```

建议在本地做错误处理
