### ISSUE TITLE
[data] DCE error [File is not a recognized excel file] for exch [DCE], date [20210309]

### ISSUE THREAD

**Issue by daisypupu** [jindaxiang/akshare#1049]
```
exch_api = {'CFFEX': ak.get_cffex_rank_table, 'SHFE': ak.get_shfe_rank_table,
            'CZCE': ak.get_czce_rank_table, 'DCE': ak.get_dce_rank_table}
exch_api[exch](date=dt_iter.strftime("%Y%m%d"))
```

20210309 大商所文件报错

**Comment by jindaxiang** [comment]
> ```
> exch_api = {'CFFEX': ak.get_cffex_rank_table, 'SHFE': ak.get_shfe_rank_table,
>             'CZCE': ak.get_czce_rank_table, 'DCE': ak.get_dce_rank_table}
> exch_api[exch](date=dt_iter.strftime("%Y%m%d"))
> ```
> 
> 20210309 大商所文件报错

感谢反馈问题，升级到 AKShare 0.8.32 版本，已修复
