### ISSUE TITLE
A股数据，历史分笔网易接口报错： ak.stock_zh_a_tick_163

### ISSUE THREAD

**Issue by yinshurman** [jindaxiang/akshare#1056]
**教程示例代码直接报错**:
python 版本： 3.7.4
操作系统：macos 10.15.7
akshare 版本: 0.8.30

`      

      import akshare as ak           

      stock_zh_a_tick_163_df = ak.stock_zh_a_tick_163(code="sh600848", trade_date="20210127")     

      print(stock_zh_a_tick_163_df)   

`

报错信息Error:
`    
    XLRDError                                 Traceback (most recent call last)
<ipython-input-462-96c9f9369d18> in <module>
----> 1 ak.stock_zh_a_tick_163(code="sh600848", trade_date="20210127")

/opt/anaconda3/lib/python3.7/site-packages/akshare/stock/zh_stock_a_tick_tx_163.py in stock_zh_a_tick_163(code, trade_date)
     86     r = requests.get(url)
     87     r.encoding = "utf-8"
---> 88     temp_df = pd.read_excel(BytesIO(r.content))
     89     temp_df.columns = [
     90         "成交时间",

/opt/anaconda3/lib/python3.7/site-packages/pandas/io/excel/_base.py in read_excel(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, verbose, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, mangle_dupe_cols, **kwds)
    302
    303     if not isinstance(io, ExcelFile):
--> 304         io = ExcelFile(io, engine=engine)
    305     elif engine and engine != io.engine:
    306         raise ValueError(

/opt/anaconda3/lib/python3.7/site-packages/pandas/io/excel/_base.py in __init__(self, io, engine)
    819         self._io = stringify_path(io)
    820
--> 821         self._reader = self._engines[engine](self._io)
    822
    823     def __fspath__(self):

/opt/anaconda3/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py in __init__(self, filepath_or_buffer)
     19         err_msg = "Install xlrd >= 1.0.0 for Excel support"
     20         import_optional_dependency("xlrd", extra=err_msg)
---> 21         super().__init__(filepath_or_buffer)
     22
     23     @property

/opt/anaconda3/lib/python3.7/site-packages/pandas/io/excel/_base.py in __init__(self, filepath_or_buffer)
    349             # N.B. xlrd.Book has a read attribute too
    350             filepath_or_buffer.seek(0)
--> 351             self.book = self.load_workbook(filepath_or_buffer)
    352         elif isinstance(filepath_or_buffer, str):
    353             self.book = self.load_workbook(filepath_or_buffer)

/opt/anaconda3/lib/python3.7/site-packages/pandas/io/excel/_xlrd.py in load_workbook(self, filepath_or_buffer)
     32         if hasattr(filepath_or_buffer, "read"):
     33             data = filepath_or_buffer.read()
---> 34             return open_workbook(file_contents=data)
     35         else:
     36             return open_workbook(filepath_or_buffer)

/opt/anaconda3/lib/python3.7/site-packages/xlrd/__init__.py in open_workbook(filename, logfile, verbosity, use_mmap, file_contents, encoding_override, formatting_info, on_demand, ragged_rows)
    155         formatting_info=formatting_info,
    156         on_demand=on_demand,
--> 157         ragged_rows=ragged_rows,
    158     )
    159     return bk

/opt/anaconda3/lib/python3.7/site-packages/xlrd/book.py in open_workbook_xls(filename, logfile, verbosity, use_mmap, file_contents, encoding_override, formatting_info, on_demand, ragged_rows)
     90         t1 = perf_counter()
     91         bk.load_time_stage_1 = t1 - t0
---> 92         biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
     93         if not biff_version:
     94             raise XLRDError("Can't determine file's BIFF version")

/opt/anaconda3/lib/python3.7/site-packages/xlrd/book.py in getbof(self, rqd_stream)
   1276             bof_error('Expected BOF record; met end of file')
   1277         if opcode not in bofcodes:
-> 1278             bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
   1279         length = self.get2bytes()
   1280         if length == MY_EOF:

/opt/anaconda3/lib/python3.7/site-packages/xlrd/book.py in bof_error(msg)
   1270
   1271         def bof_error(msg):
-> 1272             raise XLRDError('Unsupported format, or corrupt file: ' + msg)
   1273         savpos = self._position
   1274         opcode = self.get2bytes()

XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP'

`

**Comment by jindaxiang** [comment]
> 20210127

该接口只能获取近期的数据，例如：
```
  stock_zh_a_tick_163_df = stock_zh_a_tick_163(code="sh600848", trade_date="20210311")
  print(stock_zh_a_tick_163_df)
```
