### ISSUE TITLE
沪港通：每日个股统计接口报错：stock_em_hsgt_stock_statistics

### ISSUE THREAD

**Issue by yinshurman** [jindaxiang/akshare#1057]
**Describe the bug**
教程示例代码直接报错

python 版本： 3.7.4
操作系统：macos 10.15.7
akshare 版本: 0.8.30

**To Reproduce**
`    
    
    import akshare as ak        

    stock_em_hsgt_stock_statistics_df = ak.stock_em_hsgt_stock_statistics(symbol="南向持股",   
    start_date="20201218", end_date="20201218")          

    print(stock_em_hsgt_stock_statistics_df)     
`
     

报错信息如下：
`    
    ValueError                                Traceback (most recent call last)
<ipython-input-466-6d43791e4437> in <module>
----> 1 ak.stock_em_hsgt_stock_statistics(symbol="北向持股", start_date="20201218", end_date="20201218")

/opt/anaconda3/lib/python3.7/site-packages/akshare/stock_feature/stock_em_hsgt.py in stock_em_hsgt_stock_statistics(symbol, start_date, end_date)
    470             '_',
    471             '_',
--> 472             '_',
    473         ]
    474         temp_df = temp_df[[

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in __setattr__(self, name, value)
   5285         try:
   5286             object.__getattribute__(self, name)
-> 5287             return object.__setattr__(self, name, value)
   5288         except AttributeError:
   5289             pass

pandas/_libs/properties.pyx in pandas._libs.properties.AxisProperty.__set__()

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in _set_axis(self, axis, labels)
    659
    660     def _set_axis(self, axis, labels) -> None:
--> 661         self._data.set_axis(axis, labels)
    662         self._clear_item_cache()
    663

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/managers.py in set_axis(self, axis, new_labels)
    176         if new_len != old_len:
    177             raise ValueError(
--> 178                 f"Length mismatch: Expected axis has {old_len} elements, new "
    179                 f"values have {new_len} elements"
    180             )

ValueError: Length mismatch: Expected axis has 0 elements, new values have 16 elements
`

**Comment by jindaxiang** [comment]
> 20201218

该接口只能返回近期的数据
