### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by scanfyu** [jindaxiang/akshare#1062]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
Windows10 1909
2. Python 版本
python3.7
3. AkShare 版本
0.8.36
4. 接口的名称和代码
ak.index_stock_cons_csindex
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/3198940/111138768-4c468280-85bb-11eb-8a02-80fa1e2bf4dd.png)
6. 期望获得的正确结果
在使用for循环，轮询该接口时，['000300', '399905']，获取000300正常，获取399905时报错Excel异常识别。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    Windows10 1909
> 2. Python 版本
>    python3.7
> 3. AkShare 版本
>    0.8.36
> 4. 接口的名称和代码
>    ak.index_stock_cons_csindex
> 5. 接口报错的截图或代码
>    ![image](https://user-images.githubusercontent.com/3198940/111138768-4c468280-85bb-11eb-8a02-80fa1e2bf4dd.png)
> 6. 期望获得的正确结果
>    在使用for循环，轮询该接口时，['000300', '399905']，获取000300正常，获取399905时报错Excel异常识别。

网站没有该数据
