### ISSUE TITLE
下载期货交易所CZCE数据报错，bug修正

### ISSUE THREAD

**Issue by Chandlercjy** [jindaxiang/akshare#1067]
```python
import akshare as ak

print(ak.__version__)
df = ak.get_futures_daily(
        start_date="20050509", end_date="20050510", market="CZCE", index_bar=False
    )

```

```bash
0.8.37

Traceback (most recent call last):
  File "/home/chandler/Projects/TradeAwesome/trade_awesome/futures/download_futures_domestic_history_kline.py", line 157, in <module>
    df = ak.get_futures_daily(
  File "/home/chandler/.pyenv/versions/3.8.1/lib/python3.8/site-packages/akshare/futures/futures_daily_bar.py", line 453, in get_futures_daily
    df = f(date=str(start_date).replace("-", ""))
  File "/home/chandler/.pyenv/versions/3.8.1/lib/python3.8/site-packages/akshare/futures/futures_daily_bar.py", line 223, in get_czce_daily
    m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
KeyError: 0
```

感谢开源akshare。

初步尝试以下修改可以修复，不过建议也许用df.rename(columns={})的方式针对性更改列名，可能会更好些。
```python
# 修复函数get_czce_daily

def get_czce_daily(date: str = "20200901") -> pd.DataFrame:
    """
    郑州商品交易所-日频率-量价数据
    :param date: 日期 format：YYYY-MM-DD 或 YYYYMMDD 或 datetime.date对象，默认为当前交易日; 日期需要大于200100824
    :type date: str or datetime.date
    :return: 郑州商品交易所-日频率-量价数据
    :rtype: pandas.DataFrame or None
    """
    day = cons.convert_date(date) if date is not None else datetime.date.today()
    if day.strftime("%Y%m%d") not in calendar:
        warnings.warn(f"{day.strftime('%Y%m%d')}非交易日")
        return None
    if day > datetime.date(2010, 8, 24):
        if day > datetime.date(2015, 9, 19):
            u = cons.CZCE_DAILY_URL_3
            url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
        elif day < datetime.date(2015, 9, 19):
            u = cons.CZCE_DAILY_URL_2
            url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
        listed_columns = cons.CZCE_COLUMNS
        output_columns = cons.OUTPUT_COLUMNS
        try:
            r = requests.get(url)
            html = r.text
        except requests.exceptions.HTTPError as reason:
            if reason.response.status_code != 404:
                print(
                    cons.CZCE_DAILY_URL_3
                    % (day.strftime("%Y"), day.strftime("%Y%m%d")),
                    reason,
                )
            return
        if html.find("您的访问出错了") >= 0 or html.find("无期权每日行情交易记录") >= 0:
            return
        html = [
            i.replace(" ", "").split("|")
            for i in html.split("\n")[:-4]
            if i[0][0] != "小"
        ]

        if day > datetime.date(2015, 9, 19):
            if html[1][0] not in ["品种月份", "品种代码"]:
                return
            dict_data = list()
            day_const = int(day.strftime("%Y%m%d"))
            for row in html[2:]:
                m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
                if not m:
                    continue
                row_dict = {"date": day_const, "symbol": row[0], "variety": m.group(1)}
                for i, field in enumerate(listed_columns):
                    if row[i + 1] == "\r":
                        row_dict[field] = 0.0
                    elif field in [
                        "volume",
                        "open_interest",
                        "oi_chg",
                        "exercise_volume",
                    ]:
                        row[i + 1] = row[i + 1].replace(",", "")
                        row_dict[field] = int(row[i + 1])
                    else:
                        row[i + 1] = row[i + 1].replace(",", "")
                        row_dict[field] = float(row[i + 1])
                dict_data.append(row_dict)

            return pd.DataFrame(dict_data)[output_columns]
        elif day < datetime.date(2015, 9, 19):
            dict_data = list()
            day_const = int(day.strftime("%Y%m%d"))
            for row in html[1:]:
                row = row[0].split(",")
                m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
                if not m:
                    continue
                row_dict = {"date": day_const, "symbol": row[0], "variety": m.group(1)}
                for i, field in enumerate(listed_columns):
                    if row[i + 1] == "\r":
                        row_dict[field] = 0.0
                    elif field in [
                        "volume",
                        "open_interest",
                        "oi_chg",
                        "exercise_volume",
                    ]:
                        row_dict[field] = int(float(row[i + 1]))
                    else:
                        row_dict[field] = float(row[i + 1])
                dict_data.append(row_dict)
            return pd.DataFrame(dict_data)[output_columns]

    if day <= datetime.date(2010, 8, 24):
        u = cons.CZCE_DAILY_URL_1
        url = u % day.strftime("%Y%m%d")
        listed_columns = cons.CZCE_COLUMNS_2
        output_columns = cons.OUTPUT_COLUMNS
        df = pd.read_html(url)[1].dropna(how="any")

        dict_data = list()
        day_const = int(day.strftime("%Y%m%d"))

        for row in df.to_dict(orient="records"): # 取消[1:]索引
            row = list(row.values())    # 添加行
            m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
            if not m:
                continue
            row_dict = {"date": day_const, "symbol": row[0], "variety": m.group(1)}
            for i, field in enumerate(listed_columns):
                if row[i + 1] == "\r":
                    row_dict[field] = 0.0
                elif field in ["volume", "open_interest", "oi_chg", "exercise_volume"]:

                    row_dict[field] = int(row[i + 1])
                else:

                    row_dict[field] = float(row[i + 1])
            dict_data.append(row_dict)

        return pd.DataFrame(dict_data)[output_columns]



```

**Comment by jindaxiang** [comment]
> ```python
> import akshare as ak
> 
> print(ak.__version__)
> df = ak.get_futures_daily(
>         start_date="20050509", end_date="20050510", market="CZCE", index_bar=False
>     )
> ```
> 
> ```shell
> 0.8.37
> 
> Traceback (most recent call last):
>   File "/home/chandler/Projects/TradeAwesome/trade_awesome/futures/download_futures_domestic_history_kline.py", line 157, in <module>
>     df = ak.get_futures_daily(
>   File "/home/chandler/.pyenv/versions/3.8.1/lib/python3.8/site-packages/akshare/futures/futures_daily_bar.py", line 453, in get_futures_daily
>     df = f(date=str(start_date).replace("-", ""))
>   File "/home/chandler/.pyenv/versions/3.8.1/lib/python3.8/site-packages/akshare/futures/futures_daily_bar.py", line 223, in get_czce_daily
>     m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
> KeyError: 0
> ```
> 
> 感谢开源akshare。
> 
> 初步尝试以下修改可以修复，不过建议也许用df.rename(columns={})的方式针对性更改列名，可能会更好些。
> 
> ```python
> # 修复函数get_czce_daily
> 
> def get_czce_daily(date: str = "20200901") -> pd.DataFrame:
>     """
>     郑州商品交易所-日频率-量价数据
>     :param date: 日期 format：YYYY-MM-DD 或 YYYYMMDD 或 datetime.date对象，默认为当前交易日; 日期需要大于200100824
>     :type date: str or datetime.date
>     :return: 郑州商品交易所-日频率-量价数据
>     :rtype: pandas.DataFrame or None
>     """
>     day = cons.convert_date(date) if date is not None else datetime.date.today()
>     if day.strftime("%Y%m%d") not in calendar:
>         warnings.warn(f"{day.strftime('%Y%m%d')}非交易日")
>         return None
>     if day > datetime.date(2010, 8, 24):
>         if day > datetime.date(2015, 9, 19):
>             u = cons.CZCE_DAILY_URL_3
>             url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
>         elif day < datetime.date(2015, 9, 19):
>             u = cons.CZCE_DAILY_URL_2
>             url = u % (day.strftime("%Y"), day.strftime("%Y%m%d"))
>         listed_columns = cons.CZCE_COLUMNS
>         output_columns = cons.OUTPUT_COLUMNS
>         try:
>             r = requests.get(url)
>             html = r.text
>         except requests.exceptions.HTTPError as reason:
>             if reason.response.status_code != 404:
>                 print(
>                     cons.CZCE_DAILY_URL_3
>                     % (day.strftime("%Y"), day.strftime("%Y%m%d")),
>                     reason,
>                 )
>             return
>         if html.find("您的访问出错了") >= 0 or html.find("无期权每日行情交易记录") >= 0:
>             return
>         html = [
>             i.replace(" ", "").split("|")
>             for i in html.split("\n")[:-4]
>             if i[0][0] != "小"
>         ]
> 
>         if day > datetime.date(2015, 9, 19):
>             if html[1][0] not in ["品种月份", "品种代码"]:
>                 return
>             dict_data = list()
>             day_const = int(day.strftime("%Y%m%d"))
>             for row in html[2:]:
>                 m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
>                 if not m:
>                     continue
>                 row_dict = {"date": day_const, "symbol": row[0], "variety": m.group(1)}
>                 for i, field in enumerate(listed_columns):
>                     if row[i + 1] == "\r":
>                         row_dict[field] = 0.0
>                     elif field in [
>                         "volume",
>                         "open_interest",
>                         "oi_chg",
>                         "exercise_volume",
>                     ]:
>                         row[i + 1] = row[i + 1].replace(",", "")
>                         row_dict[field] = int(row[i + 1])
>                     else:
>                         row[i + 1] = row[i + 1].replace(",", "")
>                         row_dict[field] = float(row[i + 1])
>                 dict_data.append(row_dict)
> 
>             return pd.DataFrame(dict_data)[output_columns]
>         elif day < datetime.date(2015, 9, 19):
>             dict_data = list()
>             day_const = int(day.strftime("%Y%m%d"))
>             for row in html[1:]:
>                 row = row[0].split(",")
>                 m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
>                 if not m:
>                     continue
>                 row_dict = {"date": day_const, "symbol": row[0], "variety": m.group(1)}
>                 for i, field in enumerate(listed_columns):
>                     if row[i + 1] == "\r":
>                         row_dict[field] = 0.0
>                     elif field in [
>                         "volume",
>                         "open_interest",
>                         "oi_chg",
>                         "exercise_volume",
>                     ]:
>                         row_dict[field] = int(float(row[i + 1]))
>                     else:
>                         row_dict[field] = float(row[i + 1])
>                 dict_data.append(row_dict)
>             return pd.DataFrame(dict_data)[output_columns]
> 
>     if day <= datetime.date(2010, 8, 24):
>         u = cons.CZCE_DAILY_URL_1
>         url = u % day.strftime("%Y%m%d")
>         listed_columns = cons.CZCE_COLUMNS_2
>         output_columns = cons.OUTPUT_COLUMNS
>         df = pd.read_html(url)[1].dropna(how="any")
> 
>         dict_data = list()
>         day_const = int(day.strftime("%Y%m%d"))
> 
>         for row in df.to_dict(orient="records"): # 取消[1:]索引
>             row = list(row.values())    # 添加行
>             m = cons.FUTURES_SYMBOL_PATTERN.match(row[0])
>             if not m:
>                 continue
>             row_dict = {"date": day_const, "symbol": row[0], "variety": m.group(1)}
>             for i, field in enumerate(listed_columns):
>                 if row[i + 1] == "\r":
>                     row_dict[field] = 0.0
>                 elif field in ["volume", "open_interest", "oi_chg", "exercise_volume"]:
> 
>                     row_dict[field] = int(row[i + 1])
>                 else:
> 
>                     row_dict[field] = float(row[i + 1])
>             dict_data.append(row_dict)
> 
>         return pd.DataFrame(dict_data)[output_columns]
> ```

感谢反馈问题，已修复，请升级到 0.8.38版本
