### ISSUE TITLE
关于期货成交额的问题

### ISSUE THREAD

**Issue by allenwoods** [jindaxiang/akshare#1071]
通过`ak.get_futures_daily`获得的`期货-内盘-历史行情中`, 各个交易所的成交量(turnover)逻辑并不一致: CFFEX/CZCE/DCE是从交易所直接获取的数据,单位为万元. SHFE使用成交量*收盘结算价,单位为元. INE代码中直接赋值为0. 

想请教下, 这样的做法是有什么原因吗?为何不统一转为元呢?

**Comment by jindaxiang** [comment]
> 通过`ak.get_futures_daily`获得的`期货-内盘-历史行情中`, 各个交易所的成交量(turnover)逻辑并不一致: CFFEX/CZCE/DCE是从交易所直接获取的数据,单位为万元. SHFE使用成交量*收盘结算价,单位为元. INE代码中直接赋值为0.
> 
> 想请教下, 这样的做法是有什么原因吗?为何不统一转为元呢?

主要依照数据源的格式，目前该部分需要会被重构
