### ISSUE TITLE
stock_zh_a_daily当symbol是sh689009时报错

### ISSUE THREAD

**Issue by swdmike** [jindaxiang/akshare#1076]
**Describe the bug**
df = ak.stock_zh_a_daily(symbol=sb.symbol, start_date="20000101", end_date="20210228")
当symbol=sh689009时报错：
发生异常: JSONDecodeError
No value to decode

版本为v0.8.41

**Comment by jindaxiang** [comment]
> **Describe the bug**
> df = ak.stock_zh_a_daily(symbol=sb.symbol, start_date="20000101", end_date="20210228")
> 当symbol=sh689009时报错：
> 发生异常: JSONDecodeError
> No value to decode
> 
> 版本为v0.8.41

该股票特殊，请用 stock_zh_a_cdr_daily
