### ISSUE TITLE
能否提供可转债的历史溢价率？谢谢

### ISSUE THREAD

**Issue by HickeyHsu** [jindaxiang/akshare#1081]
如题

**Comment by jindaxiang** [comment]
> 如题

有相应的数据源嘛？

**Comment by HickeyHsu** [comment]
> > 如题
> 
> 有相应的数据源嘛？

东方财富网有，但是我不太会爬，不知道可行不

**Comment by jindaxiang** [comment]
> > > 如题
> > 
> > 
> > 有相应的数据源嘛？
> 
> 东方财富网有，但是我不太会爬，不知道可行不

具体哪个页面啊？

**Comment by HickeyHsu** [comment]
> > > > 如题
> > > 
> > > 
> > > 有相应的数据源嘛？
> > 
> > 
> > 东方财富网有，但是我不太会爬，不知道可行不
> 
> 具体哪个页面啊？
例如：
http://data.eastmoney.com/kzz/detail/113504.html
有可转债溢价率分析的页面
