### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by yy306525121** [jindaxiang/akshare#1085]
**描述遇到的问题**
1. 操作系统版本 
2. Python 版本 3.8.8
3. AkShare 版本 0.8.43
接口stock_financial_report_sina接口出现问题，  当调用资产负债表数据时报编码错误， 

![image](https://user-images.githubusercontent.com/12985872/112438981-85cd7980-8d83-11eb-8b47-d3e83a4cde7a.png)

![image](https://user-images.githubusercontent.com/12985872/112438966-81a15c00-8d83-11eb-80c8-b666fe685482.png)

**Comment by jindaxiang** [comment]
> 3\. stock_financial_report_sina

`    stock_financial_report_sina_df = ak.stock_financial_report_sina(stock="600004", symbol="资产负债表")
    print(stock_financial_report_sina_df)
`
没有问题
