### ISSUE TITLE
关于stock_zh_a_minute的情况

### ISSUE THREAD

**Issue by 92JasonK** [jindaxiang/akshare#1086]
拉取1分钟数据能拉取20000条数据，但拉取5/15，只能拉取1000多条数据，这个限制可以放开吗？
如果可以的话，可以用什么方式？
如果不行，这个限制是数据来源的限制吗

**Comment by jindaxiang** [comment]
> 拉取1分钟数据能拉取20000条数据，但拉取5/15，只能拉取1000多条数据，这个限制可以放开吗？
> 如果可以的话，可以用什么方式？
> 如果不行，这个限制是数据来源的限制吗

这个不是 AKShare 的限制，而是目标网页的限制

**Comment by 92JasonK** [comment]
我不清楚目标网页是什么形式，能否做到在页面上拉取的动作，然后再download数据呢？😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Albert King ***@***.***&gt;
发送时间: 2021年3月25日 18:15
收件人: jindaxiang/akshare ***@***.***&gt;
抄送: Jason_K ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[jindaxiang/akshare] 关于stock_zh_a_minute的情况 (#1086)





  
拉取1分钟数据能拉取20000条数据，但拉取5/15，只能拉取1000多条数据，这个限制可以放开吗？
 如果可以的话，可以用什么方式？
 如果不行，这个限制是数据来源的限制吗
  
这个不是 AKShare 的限制，而是目标网页的限制
