### ISSUE TITLE
获取注册仓单接口出错

### ISSUE THREAD

**Issue by allenwoods** [jindaxiang/akshare#1095]
系统环境为Ubuntu 20, akshare版本已更新
```bash
❯ pip freeze | grep akshare
akshare==0.8.47
```

在使用注册仓单接口时出错, 执行以下代码:
```python
# From akshare.futures.receipt

if __name__ == '__main__':
    get_receipt_df = get_receipt(start_day='20201117', end_day='20201117')
    print(get_receipt_df)
```

出现错误:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-fe9ade20aa8c> in <module>
----> 1 ak.get_receipt(start_day="20210326", end_day="20210326")

~/.conda/envs/finance/lib/python3.7/site-packages/akshare/futures/receipt.py in get_receipt(start_day, end_day, vars_list)
    369                 if market != 'cffex' and get_vars != []:
    370                     if f is not None:
--> 371                         records = records.append(f(start_day, get_vars))
    372 
    373         start_day += datetime.timedelta(days=1)

~/.conda/envs/finance/lib/python3.7/site-packages/akshare/futures/receipt.py in get_czce_receipt_3(date, vars_list)
    282     r = requests_link(url, encoding='utf-8')
    283     r.encoding = 'utf-8'
--> 284     data = pd.read_html(r.text, encoding='gb2312')
    285     records = pd.DataFrame()
    286     if len(data) < 4:

~/.conda/envs/finance/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    297                 )
    298                 warnings.warn(msg, FutureWarning, stacklevel=stacklevel)
--> 299             return func(*args, **kwargs)
    300 
    301         return wrapper

~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only)
   1098         na_values=na_values,
   1099         keep_default_na=keep_default_na,
-> 1100         displayed_only=displayed_only,
   1101     )

~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
    911     else:
    912         assert retained is not None  # for mypy
--> 913         raise retained
    914 
    915     ret = []

~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
    891 
    892         try:
--> 893             tables = p.parse_tables()
    894         except ValueError as caught:
    895             # if `io` is an io-like object, check if it's seekable

~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in parse_tables(self)
    211         list of parsed (header, body, footer) tuples from tables.
    212         """
--> 213         tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
    214         return (self._parse_thead_tbody_tfoot(table) for table in tables)
    215 

~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in _parse_tables(self, doc, match, attrs)
    541 
    542         if not tables:
--> 543             raise ValueError("No tables found")
    544 
    545         result = []

ValueError: No tables found
```

测试了dce和shfe数据是可以正常获取的(通过`vars_list=['C', 'CU']`), 问题似乎出现在`get_czce_receipt_3` 函数中:
![image](https://user-images.githubusercontent.com/7327215/112771191-42159100-905d-11eb-88e2-174a3964203c.png)

该接口对 http://www.czce.com.cn/cn/DFSStaticFiles/Future/2021/20210203/FutureDataWhsheet.htm 的访问返回了412错误, 然而, 该地址在浏览器中可以访问, 且0324前调用该接口仍然正常运行. 看起来似乎是缺少浏览器UA之类的信息? 我对网络访问不太熟悉, 不知道该从何下手开始修改😰

**Comment by jindaxiang** [comment]
> 412

应该是采用了新的加密方式，还需要研究下

**Comment by jindaxiang** [comment]
> 系统环境为Ubuntu 20, akshare版本已更新
> 
> ```shell
> ❯ pip freeze | grep akshare
> akshare==0.8.47
> ```
> 
> 在使用注册仓单接口时出错, 执行以下代码:
> 
> ```python
> # From akshare.futures.receipt
> 
> if __name__ == '__main__':
>     get_receipt_df = get_receipt(start_day='20201117', end_day='20201117')
>     print(get_receipt_df)
> ```
> 
> 出现错误:
> 
> ```python
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-16-fe9ade20aa8c> in <module>
> ----> 1 ak.get_receipt(start_day="20210326", end_day="20210326")
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/akshare/futures/receipt.py in get_receipt(start_day, end_day, vars_list)
>     369                 if market != 'cffex' and get_vars != []:
>     370                     if f is not None:
> --> 371                         records = records.append(f(start_day, get_vars))
>     372 
>     373         start_day += datetime.timedelta(days=1)
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/akshare/futures/receipt.py in get_czce_receipt_3(date, vars_list)
>     282     r = requests_link(url, encoding='utf-8')
>     283     r.encoding = 'utf-8'
> --> 284     data = pd.read_html(r.text, encoding='gb2312')
>     285     records = pd.DataFrame()
>     286     if len(data) < 4:
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
>     297                 )
>     298                 warnings.warn(msg, FutureWarning, stacklevel=stacklevel)
> --> 299             return func(*args, **kwargs)
>     300 
>     301         return wrapper
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in read_html(io, match, flavor, header, index_col, skiprows, attrs, parse_dates, thousands, encoding, decimal, converters, na_values, keep_default_na, displayed_only)
>    1098         na_values=na_values,
>    1099         keep_default_na=keep_default_na,
> -> 1100         displayed_only=displayed_only,
>    1101     )
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
>     911     else:
>     912         assert retained is not None  # for mypy
> --> 913         raise retained
>     914 
>     915     ret = []
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in _parse(flavor, io, match, attrs, encoding, displayed_only, **kwargs)
>     891 
>     892         try:
> --> 893             tables = p.parse_tables()
>     894         except ValueError as caught:
>     895             # if `io` is an io-like object, check if it's seekable
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in parse_tables(self)
>     211         list of parsed (header, body, footer) tuples from tables.
>     212         """
> --> 213         tables = self._parse_tables(self._build_doc(), self.match, self.attrs)
>     214         return (self._parse_thead_tbody_tfoot(table) for table in tables)
>     215 
> 
> ~/.conda/envs/finance/lib/python3.7/site-packages/pandas/io/html.py in _parse_tables(self, doc, match, attrs)
>     541 
>     542         if not tables:
> --> 543             raise ValueError("No tables found")
>     544 
>     545         result = []
> 
> ValueError: No tables found
> ```
> 
> 测试了dce和shfe数据是可以正常获取的(通过`vars_list=['C', 'CU']`), 问题似乎出现在`get_czce_receipt_3` 函数中:
> ![image](https://user-images.githubusercontent.com/7327215/112771191-42159100-905d-11eb-88e2-174a3964203c.png)
> 
> 该接口对 http://www.czce.com.cn/cn/DFSStaticFiles/Future/2021/20210203/FutureDataWhsheet.htm 的访问返回了412错误, 然而, 该地址在浏览器中可以访问, 且0324前调用该接口仍然正常运行. 看起来似乎是缺少浏览器UA之类的信息? 我对网络访问不太熟悉, 不知道该从何下手开始修改😰

由于该接口采用了新的加密方式，暂时无法获取数据
