### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by ChristopherGuyan1997** [jindaxiang/akshare#1097]
招商证券评级 的实例代码有误，应该改为
import akshare as ak
fund_rating_zs = ak.fund_rating_zs()
print(fund_rating_zs)

https://www.akshare.xyz/zh_CN/latest/data/fund/fund_public.html

**Comment by jindaxiang** [comment]
> fund_rating_zs

可以正常运行，但是我会增加 日期 参数进去，请关注文档更新

**Comment by ChristopherGuyan1997** [comment]
是可以正常运行，我的意思是文档本身写错了，目前这个借口的代码是上海的那个，请核查，我给出的是应该修正的部分



---原始邮件---
发件人: "Albert ***@***.***&gt;
发送时间: 2021年3月29日(周一) 下午5:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jindaxiang/akshare] AkShare 接口问题报告 (#1097)




  
fund_rating_zs
  
可以正常运行，但是我会增加 日期 参数进去，请关注文档更新

**Comment by ChristopherGuyan1997** [comment]
是可以正常运行，但是文档本身内容错误。



---原始邮件---
发件人: "Albert ***@***.***&gt;
发送时间: 2021年3月29日(周一) 下午5:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jindaxiang/akshare] AkShare 接口问题报告 (#1097)




  
fund_rating_zs
  
可以正常运行，但是我会增加 日期 参数进去，请关注文档更新

**Comment by jindaxiang** [comment]
> 是可以正常运行，我的意思是文档本身写错了，目前这个借口的代码是上海的那个，请核查，我给出的是应该修正的部分
> […](#)
> ---原始邮件--- 发件人: "Albert ***@***.***&gt; 发送时间: 2021年3月29日(周一) 下午5:18 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [jindaxiang/akshare] AkShare 接口问题报告 (#1097) fund_rating_zs 可以正常运行，但是我会增加 日期 参数进去，请关注文档更新 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，已经修复文档错误，并且增加日期参数，感谢反馈问题。
