### ISSUE TITLE
speculation sentiments

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#11]
您好，

请问未来是否可能在外汇数据中加入各交易平台各品种投机情绪？
https://datacenter.jin10.com/reportType/dc_ssi_trends

![image](https://user-images.githubusercontent.com/359830/73946477-fc7b8f00-48c3-11ea-9172-74465025bf53.png)

![image](https://user-images.githubusercontent.com/359830/73946530-1026f580-48c4-11ea-9acd-af15114cff0d.png)

谢谢

**Comment by jindaxiang** [comment]
Hello. AkShare version 0.3.84 have added this function: 
```
macro_fx_sentiment_df = macro_fx_sentiment(start_date="2020-02-07", end_date="2020-02-07")
print(macro_fx_sentiment_df)
```

**Comment by edwardsun** [comment]
Thanks~
