### ISSUE TITLE
error for exchange DCE on date[20210402], [File is not a recognized excel file]

### ISSUE THREAD

**Issue by daisypupu** [jindaxiang/akshare#1105]
`ak.get_futures_daily`

DCE
error for exchange DCE on date[20210402], [File is not a recognized excel file]

**Comment by jindaxiang** [comment]
> `ak.get_futures_daily`
> 
> DCE
> error for exchange DCE on date[20210402], [File is not a recognized excel file]

由于该接口采用了新的加密方式，暂时无法获取数据
