### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by shichaog** [jindaxiang/akshare#1106]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**

```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
mac OS 10.15
2. Python 版本
3.7
3. AkShare 版本
版本是0.8.33
4. 接口的名称和代码
stock_zh_index_spot_df = ak.stock_zh_index_spot()
5. 接口报错的截图或代码
<img width="576" alt="截屏2021-04-03 下午7 33 30" src="https://user-images.githubusercontent.com/7869827/113477332-a1d3c800-94b3-11eb-82e2-7dd333c83c7b.png">

6. 期望获得的正确结果
指数数据种类和数据正确性不对啊，沪深300和中证800都缺呢

**Comment by shichaog** [comment]
300信息和300电信没有；官网https://www.akshare.xyz/zh_CN/latest/data/index/index.html#id2，这里是有300信息和300电信这一指数的，请帮忙看下哪里出问题了，谢谢

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    mac OS 10.15
> 2. Python 版本
>    3.7
> 3. AkShare 版本
>    版本是0.8.33
> 4. 接口的名称和代码
>    stock_zh_index_spot_df = ak.stock_zh_index_spot()
> 5. 接口报错的截图或代码
> 
> <img alt="截屏2021-04-03 下午7 33 30" width="576" src="https://user-images.githubusercontent.com/7869827/113477332-a1d3c800-94b3-11eb-82e2-7dd333c83c7b.png">
> 
> 1. 期望获得的正确结果
>    指数数据种类和数据正确性不对啊，沪深300和中证800都缺呢

感谢反馈问题，已更新文档说明，目前该接口主要是返回新浪的股票指数数据。
