### ISSUE TITLE
能否增加IPO排队申报的接口数据

### ISSUE THREAD

**Issue by zzzeven** [jindaxiang/akshare#1114]
非常感谢。
数据地址，    
东方财富网-数据中心-新股数据-新股申报
https://data.eastmoney.com/xg/xg/sbqy.html
注册制申报
https://data.eastmoney.com/zcz/

**Comment by jindaxiang** [comment]
> 非常感谢。
> 数据地址，
> 东方财富网-数据中心-新股数据-新股申报
> https://data.eastmoney.com/xg/xg/sbqy.html
> 注册制申报
> https://data.eastmoney.com/zcz/

感谢反馈，已经更新相关接口，请升级到最新版
