### ISSUE TITLE
get_dce_daily 函数无法获取数据

### ISSUE THREAD

**Issue by changvin** [jindaxiang/akshare#1117]
akshare  == 0.8.55
调用 akshare.futures.get_dce_daily 获取日线数据是返回错误：Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP'

**Comment by jindaxiang** [comment]
> akshare == 0.8.55
> 调用 akshare.futures.get_dce_daily 获取日线数据是返回错误：Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP'

大商所的接口已经失效

**Comment by harveywwu** [comment]
直接从浏览器连接这个接口可以自动下载一个excel,不知道为什么python不行http://www.dce.com.cn/publicweb/quotesdata/exportDayQuotesChData.html?year=2021&month=3&date=6&exportFlag=excel

**Comment by changvin** [comment]
> > akshare == 0.8.55
> > 调用 akshare.futures.get_dce_daily 获取日线数据是返回错误：Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP'
> 
> 大商所的接口已经失效

直接浏览器调用是可以的

**Comment by jindaxiang** [comment]
> > > akshare == 0.8.55
> > > 调用 akshare.futures.get_dce_daily 获取日线数据是返回错误：Unsupported format, or corrupt file: Expected BOF record; found b'<!DOCTYP'
> > 
> > 
> > 大商所的接口已经失效
> 
> 直接浏览器调用是可以的

后续更新其他数据源的
