### ISSUE TITLE
stock_financial_report_sina 接口不能用了

### ISSUE THREAD

**Issue by fangxianzheng** [jindaxiang/akshare#1121]
stock_financial_report_sina 接口不能用了，可能是新浪页面结构有过改动
报错：
stock_financial_analysis_indicator_df = ak.stock_financial_analysis_indicator(stock="600004")
  File "/Users/fangxianzheng/anaconda3/lib/python3.7/site-packages/akshare/stock_fundamental/stock_finance.py", line 81, in stock_financial_analysis_indicator
    year_context = soup.find(attrs={"id": "con02-1"}).find("table").find_all("a")
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by jindaxiang** [comment]
> stock_financial_analysis_indicator

可以正常使用，注意要升级到最新版
