### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by yechengda** [jindaxiang/akshare#1143]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. Ubuntu 18.04
2. Python3.8
3. AKShare 0.8.31
4. ak.crypto_hist,ak.currency_hist,ak.index_investing_global,ak.bond_investing_global
5. JSONDecodeError: Expecting value: line 1 column 1 (char 0),AttributeError: 'NoneType' object has no attribute 'find_all'(bond_investing_global)
6. 正常调用

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. Ubuntu 18.04
> 2. Python3.8
> 3. AKShare 0.8.31
> 4. ak.crypto_hist,ak.currency_hist,ak.index_investing_global,ak.bond_investing_global
> 5. JSONDecodeError: Expecting value: line 1 column 1 (char 0),AttributeError: 'NoneType' object has no attribute 'find_all'(bond_investing_global)
> 6. 正常调用

感谢反馈问题，目前已经修复该问题，但是只能通过代理访问该接口

**Comment by yechengda** [comment]
Ubuntu 18.04

Python3.8

AKShare 0.8.31

ak.crypto_hist,ak.currency_hist,ak.index_investing_global,ak.bond_investing_global

JSONDecodeError: Expecting value: line 1 column 1 (char 0),

AttributeError: 'NoneType' object has no attribute 'find_all'(bond_investing_global)
