### ISSUE TITLE
大商所的期货数据获取失败。 get_dce_daily 在下载excel 文件的时候没下到

### ISSUE THREAD

**Issue by shanhujiao1985** [jindaxiang/akshare#1150]
get_dce_daily 函数

错误信息：File is not a recognized excel file

2021.4.16  之后开始出现问题

**Comment by shanhujiao1985** [comment]
def get_dce_daily(date: str = "20030115") -> pd.DataFrame:
  
....
    r = requests.post(url, data=params, headers=headers)
    data_df = pd.read_excel(BytesIO(r.content))
....
    return data_df

**Comment by jindaxiang** [comment]
> def get_dce_daily(date: str = "20030115") -> pd.DataFrame:
> 
> ....
> r = requests.post(url, data=params, headers=headers)
> data_df = pd.read_excel(BytesIO(r.content))
> ....
> return data_df

该接口暂时无法使用

**Comment by ZuoVJ** [comment]
好像是大商所反爬了。。。能尽快修复吗

**Comment by jindaxiang** [comment]
> 好像是大商所反爬了。。。能尽快修复吗

暂时无法恢复

**Comment by ZuoVJ** [comment]
为啥就close了。。。不打算跟踪了吗

**Comment by jindaxiang** [comment]
已经可以正常使用了
