### ISSUE TITLE
可以增加期货每日保证金/手续费的情况吗？

### ISSUE THREAD

**Issue by ZuoVJ** [jindaxiang/akshare#1162]
这个东西偶尔会有变动，而且变动了影响还挺大的，可是人工去看总有些不及时和不方便，如果可以的话～能支持到就最好啦

**Comment by jindaxiang** [comment]
> 这个东西偶尔会有变动，而且变动了影响还挺大的，可是人工去看总有些不及时和不方便，如果可以的话～能支持到就最好啦

暂时无法更新呢

**Comment by jindaxiang** [comment]
> 这个东西偶尔会有变动，而且变动了影响还挺大的，可是人工去看总有些不及时和不方便，如果可以的话～能支持到就最好啦

这部分的数据目前是手动更新的，后期有合适的数据源可以考虑更新到相关的数据接口
