### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by scanfyu** [jindaxiang/akshare#1166]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
Windows10
2. Python 版本
3.7.6
3. AkShare 版本
akshare-0.8.79
4. 接口的名称和代码
ak.stock_em_yjkb
5. 接口报错的截图或代码
ak.stock_em_yjkb("20201231")
只拿到了前500条数据。
6. 期望获得的正确结果
是否可以返回全量数据，或者给一个其他接口，根据页面长度分别获取不同页面的数据。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    Windows10
> 2. Python 版本
>    3.7.6
> 3. AkShare 版本
>    akshare-0.8.79
> 4. 接口的名称和代码
>    ak.stock_em_yjkb
> 5. 接口报错的截图或代码
>    ak.stock_em_yjkb("20201231")
>    只拿到了前500条数据。
> 6. 期望获得的正确结果
>    是否可以返回全量数据，或者给一个其他接口，根据页面长度分别获取不同页面的数据。

感谢反馈问题，已修复，请升级到 0.8.80 版本使用
