### ISSUE TITLE
请教关于期货交易所交易日历问题

### ISSUE THREAD

**Issue by jrqhjs** [jindaxiang/akshare#1172]
关于接口: futures_rule，能否单独从各期货交易所的交易日历中获取。因为国泰君安的那个链接有些信息是没有涉及的，比如自然人持仓当天要清零。例如能源中心：http://www.ine.cn/bourseService/businessdata/calendar/；
当前日期为 ： 2021-04-20
 

交割提示:

cu2104、al2104、zn2104、pb2104、ni2104、sn2104、rb2104、wr2104、hc2104、ss2104、ag2104、bu2104、ru2104、sp2104 买方交款、取单。卖方收款。

**Comment by jindaxiang** [comment]
> 关于接口: futures_rule，能否单独从各期货交易所的交易日历中获取。因为国泰君安的那个链接有些信息是没有涉及的，比如自然人持仓当天要清零。例如能源中心：[http://www.ine.cn/bourseService/businessdata/calendar/；](http://www.ine.cn/bourseService/businessdata/calendar/%EF%BC%9B)
> 当前日期为 ： 2021-04-20
> 
> 交割提示:
> 
> cu2104、al2104、zn2104、pb2104、ni2104、sn2104、rb2104、wr2104、hc2104、ss2104、ag2104、bu2104、ru2104、sp2104 买方交款、取单。卖方收款。

暂时不能
