### ISSUE TITLE
ak.stock_zh_a_daily  查询k线数据问题

### ISSUE THREAD

**Issue by mixbe** [jindaxiang/akshare#1182]
Python 3.9.2

```
Traceback (most recent call last):
  File "/Users/cuijl/PycharmProjects/rqalpha/akshare_test/test.py", line 5, in <module>
    stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sz000002", start_date="20101103", end_date="20201116",
  File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/akshare/stock/zh_stock_a_sina.py", line 181, in stock_zh_a_daily
    temp_df = pd.merge(
  File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 89, in merge
    return op.get_result()
  File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 684, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 896, in _get_join_info
    join_index, left_indexer, right_indexer = left_ax.join(
  File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py", line 893, in join
    this, other = self._maybe_utc_convert(other)
  File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 413, in _maybe_utc_convert
    raise TypeError("Cannot join tz-naive with tz-aware DatetimeIndex")
TypeError: Cannot join tz-naive with tz-aware DatetimeIndex
```

**Comment by jindaxiang** [comment]
> Python 3.9.2
> 
> ```
> Traceback (most recent call last):
>   File "/Users/cuijl/PycharmProjects/rqalpha/akshare_test/test.py", line 5, in <module>
>     stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sz000002", start_date="20101103", end_date="20201116",
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/akshare/stock/zh_stock_a_sina.py", line 181, in stock_zh_a_daily
>     temp_df = pd.merge(
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 89, in merge
>     return op.get_result()
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 684, in get_result
>     join_index, left_indexer, right_indexer = self._get_join_info()
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 896, in _get_join_info
>     join_index, left_indexer, right_indexer = left_ax.join(
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py", line 893, in join
>     this, other = self._maybe_utc_convert(other)
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 413, in _maybe_utc_convert
>     raise TypeError("Cannot join tz-naive with tz-aware DatetimeIndex")
> TypeError: Cannot join tz-naive with tz-aware DatetimeIndex
> ```

经测试，目前应该是 Python 3.9.2 版本的问题，建议先用 Python 3.8

**Comment by imcda** [comment]
Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？

**Comment by udbmnm** [comment]
> Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？

3.8.0一样报错

**Comment by jindaxiang** [comment]
> Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？

目前我还没有在其他的版本中复现该问题，能否提供下 pandas 的版本

**Comment by jindaxiang** [comment]
> > Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？
> 
> 3.8.0一样报错

请问下 pandas 的版本

**Comment by imcda** [comment]
> > Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？
> 
> 目前我还没有在其他的版本中复现该问题，能否提供下 pandas 的版本

1.1.5

mac 环境

**Comment by jindaxiang** [comment]
目前该问题已经修复，请升级到 0.8.93 以上版本使用！

**Comment by jindaxiang** [comment]
> > > Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？
> > 
> > 
> > 目前我还没有在其他的版本中复现该问题，能否提供下 pandas 的版本
> 
> 1.1.5
> 
> mac 环境

目前该问题已经修复，请升级到 0.8.93 以上版本使用！

**Comment by jindaxiang** [comment]
> > Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？
> 
> 3.8.0一样报错

目前该问题已经修复，请升级到 0.8.93 以上版本使用！

**Comment by jindaxiang** [comment]
> Python 3.7.9 也有一样的报错，什么原因？只能用 Python 3.8 吗？

目前该问题已经修复，请升级到 0.8.93 以上版本使用！

**Comment by jindaxiang** [comment]
> Python 3.9.2
> 
> ```
> Traceback (most recent call last):
>   File "/Users/cuijl/PycharmProjects/rqalpha/akshare_test/test.py", line 5, in <module>
>     stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sz000002", start_date="20101103", end_date="20201116",
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/akshare/stock/zh_stock_a_sina.py", line 181, in stock_zh_a_daily
>     temp_df = pd.merge(
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 89, in merge
>     return op.get_result()
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 684, in get_result
>     join_index, left_indexer, right_indexer = self._get_join_info()
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 896, in _get_join_info
>     join_index, left_indexer, right_indexer = left_ax.join(
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py", line 893, in join
>     this, other = self._maybe_utc_convert(other)
>   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 413, in _maybe_utc_convert
>     raise TypeError("Cannot join tz-naive with tz-aware DatetimeIndex")
> TypeError: Cannot join tz-naive with tz-aware DatetimeIndex
> ```

目前该问题已经修复，请升级到 0.8.93 以上版本使用！

**Comment by imcda** [comment]
> > Python 3.9.2
> > ```
> > Traceback (most recent call last):
> >   File "/Users/cuijl/PycharmProjects/rqalpha/akshare_test/test.py", line 5, in <module>
> >     stock_zh_a_daily_qfq_df = ak.stock_zh_a_daily(symbol="sz000002", start_date="20101103", end_date="20201116",
> >   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/akshare/stock/zh_stock_a_sina.py", line 181, in stock_zh_a_daily
> >     temp_df = pd.merge(
> >   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 89, in merge
> >     return op.get_result()
> >   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 684, in get_result
> >     join_index, left_indexer, right_indexer = self._get_join_info()
> >   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 896, in _get_join_info
> >     join_index, left_indexer, right_indexer = left_ax.join(
> >   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py", line 893, in join
> >     this, other = self._maybe_utc_convert(other)
> >   File "/Users/cuijl/PycharmProjects/rqalpha/venv/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 413, in _maybe_utc_convert
> >     raise TypeError("Cannot join tz-naive with tz-aware DatetimeIndex")
> > TypeError: Cannot join tz-naive with tz-aware DatetimeIndex
> > ```
> 
> 目前该问题已经修复，请升级到 0.8.93 以上版本使用！

好，谢谢。是什么问题？

**Comment by sailxjx** [comment]
@jindaxiang 我用最新版本还是会有这个错误，用的是 stock_hk_daily 接口，akshare 版本0.9.23，python 版本 3.9.4，pandas 版本 1.2.4

```
>>> df = ak.stock_hk_daily(symbol="00700", adjust="qfq")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/akshare/stock/hk_stock_sina.py", line 152, in stock_hk_daily
    temp_df = pd.merge(
  File "/usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 89, in merge
    return op.get_result()
  File "/usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 684, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/usr/local/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 896, in _get_join_info
    join_index, left_indexer, right_indexer = left_ax.join(
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/datetimelike.py", line 893, in join
    this, other = self._maybe_utc_convert(other)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/datetimes.py", line 413, in _maybe_utc_convert
    raise TypeError("Cannot join tz-naive with tz-aware DatetimeIndex")
TypeError: Cannot join tz-naive with tz-aware DatetimeIndex
>>> ak.__version__
'0.9.23'
>>> pd.__version__
'1.2.4'
```

**Comment by jindaxiang** [comment]
> stock_hk_daily

升级到最新版，已经修复
