### ISSUE TITLE
同花顺数据中心，行业资金净流入排行

### ISSUE THREAD

**Issue by ZHAOHUHU** [jindaxiang/akshare#1183]
http://data.10jqka.com.cn/funds/hyzjl/#refCountId=data_55f13c2c_254   这个链接 ，每日的行业板块资金净流入排行可以增加一个接口吗，这个功能在东财实现了，但是东财又没有板块下面所有成分股的接口，同花顺是没有板块资金排行但是有板块下所有成分股的接口，因为东财和同花顺的行业板块划分不一致，所以数据源只好尽量用一样的了，先谢过大佬

**Comment by jindaxiang** [comment]
> http://data.10jqka.com.cn/funds/hyzjl/#refCountId=data_55f13c2c_254 这个链接 ，每日的行业板块资金净流入排行可以增加一个接口吗，这个功能在东财实现了，但是东财又没有板块下面所有成分股的接口，同花顺是没有板块资金排行但是有板块下所有成分股的接口，因为东财和同花顺的行业板块划分不一致，所以数据源只好尽量用一样的了，先谢过大佬

感谢反馈问题，已经新增相关接口，升级到 0.8.88 版本，文档链接：https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html#id87
