### ISSUE TITLE
关于大商所的数据接口已经可以正常使用，请升级到最新版

### ISSUE THREAD

**Issue by jindaxiang** [jindaxiang/akshare#1192]
经测试，该接口目前已经可以正常获取数据

**Comment by richwu** [comment]
Just pip installed the version 0.8.91, the scrape functionality of dce is back. Weird.

**Comment by jindaxiang** [comment]
> Just pip installed the version 0.8.91, the scrape functionality of dce is back. Weird.

是的，我刚才测试，发现 日频量价 数据可以获取了
