### ISSUE TITLE
关于 stock_zh_a_daily 接口问题已经修复，请升级到最新版使用！

### ISSUE THREAD

**Issue by jindaxiang** [jindaxiang/akshare#1195]
```pip install akshare --upgrade -i https://pypi.org/simple```

**Comment by ustcxmwu** [comment]
赞，很迅速

**Comment by JavaLover4Ricky** [comment]
为中国速度点赞，找了半天原因，还以为是pandas的问题

**Comment by jindaxiang** [comment]
> 为中国速度点赞，找了半天原因，还以为是pandas的问题

是 Pandas 版本更新了

**Comment by xnw176** [comment]
赞一个
