### ISSUE TITLE
关于 英为财情 数据接口的问题，请使用代理后访问！

### ISSUE THREAD

**Issue by jindaxiang** [jindaxiang/akshare#1196]

**Comment by GF-Huang** [comment]
没有美股期权接口？

**Comment by jindaxiang** [comment]
> 没有美股期权接口？

有合适的数据源推荐嘛？

**Comment by GF-Huang** [comment]
没有，我以为 “英为” 有。

**Comment by hzm128128** [comment]
我的A股的财务数据是从通达信客户端上下载，财务项目全。

**Comment by hzm128128** [comment]
我的A股的财务数据是从通达信客户端上下载，财务项目全，有401项，不过有的数据项是空的。数据包两小时就下完了，但不知道怎么解析成excel文档。只好用通达信公式函数进行调用，得花几天。不知道能否增加这个数据。

**Comment by jindaxiang** [comment]
> 我的A股的财务数据是从通达信客户端上下载，财务项目全，有401项，不过有的数据项是空的。数据包两小时就下完了，但不知道怎么解析成excel文档。只好用通达信公式函数进行调用，得花几天。不知道能否增加这个数据。

建议可以直接用通达信的接口

**Comment by hzm128128** [comment]
雅虎网站上有美股的财务数据，并有接口。
