### ISSUE TITLE
stock_zh_a_daily部分股票length mismatch

### ISSUE THREAD

**Issue by shanzhong2021** [jindaxiang/akshare#1199]
好像是复权的问题
pic1
![捕获1](https://user-images.githubusercontent.com/79627415/116496611-0aa63880-a8d8-11eb-8b17-58bec9e7681d.JPG)
pic2
![捕获2](https://user-images.githubusercontent.com/79627415/116496691-37f2e680-a8d8-11eb-9c93-e89d1ca1ea98.JPG)

**To Reproduce**
hh=ak.stock_zh_a_daily(symbol='sh601088', start_date='20201103', end_date='20201104', adjust="qfq")

**Comment by icross56** [comment]
遇到同样的问题

**Comment by jindaxiang** [comment]
> sh601088

该问题是新浪财经数据源的问题，目前部分股票没有返回复权因子

**Comment by shanzhong2021** [comment]
很迅速
