### ISSUE TITLE
live data

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#12]
Hi,

I noticed there are two functions that can possibly provide real-time data.
1. stock_zh_a_spot
2. stock_zh_a_tick

I've questions/suggestions regarding both, respectively.
1. Is it possible to provide a symbol argument to stock_zh_a_spot? eg. stock_zh_a_spot(symbol = '000001'). 
2. Does stock_zh_a_tick provide live data during regular trade hours?
3. I'm interested in symbol = 'sh204007' (GC007, repo rate). Can stock_zh_a_spot fetch this data?

Thanks.

**Comment by edwardsun** [comment]
btw, stock_zh_a_tick does not seem to be able to fetch 'sh131802'. 
Instead 'sh204007' is available. Thoughts? Thanks.

http://stockhtm.finance.qq.com/sstock/ggcx/131802.shtml

**Comment by jindaxiang** [comment]
Hello,
I have checked the function 'stock_zh_a_spot', sina website should run forloop to get all page stocks, then you can run select, so whatever, you have to wait for a forloop time.

**Comment by jindaxiang** [comment]
`sh204007` is bond, 'stock_zh_a_spot' is just for stock, akshare will design 'bond_zh_a_spot' in future

**Comment by edwardsun** [comment]
> `sh204007` is bond, 'stock_zh_a_spot' is just for stock, akshare will design 'bond_zh_a_spot' in future

Hi, fortunately sh204007 actually works. I'm wondering if there is a way to get sh131802 to work as well.

**Comment by edwardsun** [comment]
> Hello,
> I have checked the function 'stock_zh_a_spot', sina website should run forloop to get all page stocks, then you can run select, so whatever, you have to wait for a forloop time.

Thanks for the info. It may be a good idea to put this message somewhere.

**Comment by jindaxiang** [comment]
‘stock_zh_a_tick ’ can only provide data after trading day at16:00

**Comment by jindaxiang** [comment]
In order to achieve the data, you can use 
`stock_zh_a_spot_df[stock_zh_a_spot_df["symbol"].str.contains("000001")]`
to replace
`stock_zh_a_spot(symbol = '000001')`

**Comment by jindaxiang** [comment]
> > `sh204007` is bond, 'stock_zh_a_spot' is just for stock, akshare will design 'bond_zh_a_spot' in future
> 
> Hi, fortunately sh204007 actually works for historical data. I'm wondering if it also works for live data.

I will consider a new interface to handle this type historical data

**Comment by jindaxiang** [comment]
> > Hello,
> > I have checked the function 'stock_zh_a_spot', sina website should run forloop to get all page stocks, then you can run select, so whatever, you have to wait for a forloop time.
> 
> Thanks for the info. It may be a good idea to put this message somewhere.

I will put the detail in docs and code docstrings

**Comment by jindaxiang** [comment]
> btw, stock_zh_a_tick does not seem to be able to fetch 'sh131802'.
> Instead 'sh204007' is available. Thoughts? Thanks.
> 
> http://stockhtm.finance.qq.com/sstock/ggcx/131802.shtml

yeah, thanks for your good idea, i will add func named bond_repo_zh_tick to handle it

**Comment by edwardsun** [comment]
> > btw, stock_zh_a_tick does not seem to be able to fetch 'sh131802'.
> > Instead 'sh204007' is available. Thoughts? Thanks.
> > http://stockhtm.finance.qq.com/sstock/ggcx/131802.shtml
> 
> yeah, thanks for your good idea, i will add func named bond_repo_zh_tick to handle it

Great! Look forward to bond live data and historical tick data.

**Comment by jindaxiang** [comment]
> > > btw, stock_zh_a_tick does not seem to be able to fetch 'sh131802'.
> > > Instead 'sh204007' is available. Thoughts? Thanks.
> > > http://stockhtm.finance.qq.com/sstock/ggcx/131802.shtml
> > 
> > 
> > yeah, thanks for your good idea, i will add func named bond_repo_zh_tick to handle it
> 
> Great! Look forward to bond live data and historical tick data.

ok

**Comment by edwardsun** [comment]
> > > > btw, stock_zh_a_tick does not seem to be able to fetch 'sh131802'.
> > > > Instead 'sh204007' is available. Thoughts? Thanks.
> > > > http://stockhtm.finance.qq.com/sstock/ggcx/131802.shtml
> > > 
> > > 
> > > yeah, thanks for your good idea, i will add func named bond_repo_zh_tick to handle it
> > 
> > 
> > Great! Look forward to bond live data and historical tick data.
> 
> ok

In fact, since bonds (and futures contracts) can expire, it might be a better idea to only post daily repo rates, reverse-repo rates, deposit rates, etc.

**Comment by jindaxiang** [comment]
> > > > > btw, stock_zh_a_tick does not seem to be able to fetch 'sh131802'.
> > > > > Instead 'sh204007' is available. Thoughts? Thanks.
> > > > > http://stockhtm.finance.qq.com/sstock/ggcx/131802.shtml
> > > > 
> > > > 
> > > > yeah, thanks for your good idea, i will add func named bond_repo_zh_tick to handle it
> > > 
> > > 
> > > Great! Look forward to bond live data and historical tick data.
> > 
> > 
> > ok
> 
> In fact, since bonds (and futures contracts) can expire, it might be a better idea to only post daily repo rates, reverse-repo rates, deposit rates, etc.

what's the meaning of 'only post daily repo rates, reverse-repo rates, deposit rates'

**Comment by edwardsun** [comment]
> what's the meaning of 'only post daily repo rates, reverse-repo rates, deposit rates'

Sorry please discard my comment. :)

**Comment by jindaxiang** [comment]
> > what's the meaning of 'only post daily repo rates, reverse-repo rates, deposit rates'
> 
> Sorry please discard my comment. :)

ok

**Comment by edwardsun** [comment]
Just want to follow up on interest rates live data fetch. Any recent plan? Thanks.

**Comment by jindaxiang** [comment]
> interest rates live data

do you have any good data-source website for interest rates live data?

**Comment by edwardsun** [comment]
> do you have any good data-source website for interest rates live data?

I think the sina website that you are currently using is a good data source.

For example,
![image](https://user-images.githubusercontent.com/359830/74441527-fe060380-4e3d-11ea-8db3-056c1a602582.png)

I believe SHIBOR data are already present in akshare so needless to replicate.

There are additional rates data, like sz131802 (R-014), but it's unclear how to structure the codes.

**Comment by jindaxiang** [comment]
> > do you have any good data-source website for interest rates live data?
> 
> I think the sina website that you are currently using is a good data source.
> http://finance.sina.com.cn/bond/
> 
> For example,
> ![image](https://user-images.githubusercontent.com/359830/74441527-fe060380-4e3d-11ea-8db3-056c1a602582.png)
> 
> I believe SHIBOR data are already present in akshare so needless to replicate.
> 
> There are additional rates data, like sz131802 (R-014), but it's unclear how to structure the codes.

In akshare version 0.3.95:
add 沪深债券 and 沪深可转债
https://akshare.readthedocs.io/zh_CN/latest/data/bond/bond.html#id7

**Comment by edwardsun** [comment]
> In akshare version 0.3.95:
> add 沪深债券 and 沪深可转债
> https://akshare.readthedocs.io/zh_CN/latest/data/bond/bond.html#id7

Great! Thanks~

**Comment by edwardsun** [comment]
I'm afraid there is a need to reopen the ticket.
bond spot data does not contain any interest rate data...

It would be ideal to access the following website to simply provide symbol and extract data.

![image](https://user-images.githubusercontent.com/359830/74534510-e1cb9a80-4f01-11ea-9c17-bc3cda41986c.png)

Otherwise live repo rates are tabulated at http://finance.sina.com.cn/bond/

**Comment by jindaxiang** [comment]
> I'm afraid there is a need to reopen the ticket.
> bond spot data does not contain any interest rate data...
> 
> It would be ideal to access the following website to simply provide symbol and extract live data.
> 
> ![image](https://user-images.githubusercontent.com/359830/74534510-e1cb9a80-4f01-11ea-9c17-bc3cda41986c.png)
> 
> Otherwise live repo rates are tabulated at http://finance.sina.com.cn/bond/

real tick data should maintains the requests to interface, just like the interface used in futures functions? or what kind of data?

**Comment by edwardsun** [comment]
> real tick data should maintains the requests to interface, just like the interface used in futures functions? or what kind of data?

The first provided link, http://money.finance.sina.com.cn/bond/quotes/sz131802.html, or the generic http://money.finance.sina.com.cn/bond/quotes/**{symbolname}**.html, can give users the flexibility to fetch live data in which they are interested. It might be difficult to implement, I guess.

In terms of another live data source for interest rates (repo rates), I've found this one.
https://www.chinabond.com.cn/jsp/include/EJB/realtimeV2_jm_hg.jsp

Again, thanks a lot for providing such a great tool.

**Comment by edwardsun** [comment]
closing the ticket for now. maybe useful when there are more use cases from other users.
