### ISSUE TITLE
能否加入同花顺人气股排行前100排行查询呢

### ISSUE THREAD

**Issue by luodadaRyan** [jindaxiang/akshare#1203]
能否加入同花顺人气股排行前100排行查询呢

**Comment by jindaxiang** [comment]
> 能否加入同花顺人气股排行前100排行查询呢

哪里链接地址？

**Comment by luodadaRyan** [comment]
链接: http://www.iwencai.com/stockpick/search?tid=stockpick&qs=box_main_ths&w=%E7%83%AD%E9%97%A8%E8%82%A1%E5%89%8D100

也就是同花顺的问财。输入文字条件，会返回符合条件的股票列表，看看可不可行呢

**Comment by jindaxiang** [comment]
> 链接: http://www.iwencai.com/stockpick/search?tid=stockpick&qs=box_main_ths&w=%E7%83%AD%E9%97%A8%E8%82%A1%E5%89%8D100
> 
> 也就是同花顺的问财。输入文字条件，会返回符合条件的股票列表，看看可不可行呢

已新增，请升级到 0.9.6 版本，https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html#id170
