### ISSUE TITLE
行业指数数据返回值解析异常，问题我已经定位了

### ISSUE THREAD

**Issue by ZHAOHUHU** [jindaxiang/akshare#1208]
该问题为偶现bug，当响应都为200但是同花顺有两种返回形式，一种纯文本，一种js，js解析后仍为指数数据
重现方法：先获取所有行业类别信息，然后for循环调用各行业指数数据，会随机出现该bug
问题定位：详见代码里我写的注释

def stock_board_industry_index_ths(symbol: str = "半导体及元件") -> pd.DataFrame:
    """
    同花顺-板块-行业板块-指数数据
    http://q.10jqka.com.cn/gn/detail/code/301558/
    :param symbol: 指数数据
    :type symbol: str
    :return: 指数数据
    :rtype: pandas.DataFrame
    """
    code_map = _stock_board_concept_code_ths()
    symbol_code = code_map[symbol]
    big_df = pd.DataFrame()
    current_year = datetime.now().year
    for year in tqdm(range(2000, current_year+1)):
        url = f'http://d.10jqka.com.cn/v4/line/bk_{symbol_code}/01/{year}.js'
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36',
            'Referer': 'http://q.10jqka.com.cn',
            'Host': 'd.10jqka.com.cn'
        }
        r = requests.get(url, headers=headers)
        #正确获取行业指数数据的时候 data_text的值为uotebridge_v4_line_bk_881144_01_2013({"data":"20130104,1692.598,1694.551,1663.638后面省略大部分数据 
        #当响应仍为200但是数据是js格式的时候 data_text的值为
        '''
        data_text的值为
        <html><body>
        <script src="//s.thsi.cn/js/chameleon/chameleon.min.1619924.js" type="text/javascript"></script>
        <script language="javascript" type="text/javascript">
        window.location.href="http://d.10jqka.com.cn/v4/line/bk_881133/01/2021.js";
        </script>
        </body></html>
        该js解析之后也是指数的值
        '''
        data_text = r.text
        try:
            demjson.decode(data_text[data_text.find('{'):-1])
        except:
            continue
        temp_df = demjson.decode(data_text[data_text.find('{'):-1])
        temp_df = pd.DataFrame(temp_df['data'].split(';'))
        temp_df = temp_df.iloc[:, 0].str.split(',', expand=True)
        big_df = big_df.append(temp_df, ignore_index=True)
    big_df.columns = [
        '日期',
        '开盘价',
        '最高价',
        '最低价',
        '收盘价',
        '成交量',
        '成交额',
        '_',
        '_',
        '_',
        '_',
    ]
    big_df = big_df[[
        '日期',
        '开盘价',
        '最高价',
        '最低价',
        '收盘价',
        '成交量',
        '成交额',
    ]]
    big_df['日期'] = pd.to_datetime(big_df['日期'])
    return big_df

**Comment by jindaxiang** [comment]
> stock_board_industry_index_ths

暂时未能复现该bug，建议在程序中加入时间间隔

**Comment by PKQ1688** [comment]
我也发生了这个bug，循环获取同花顺的数据时，因为同花顺的返回是随机的，所以会出现这个问题。

**Comment by jindaxiang** [comment]
> 我也发生了这个bug，循环获取同花顺的数据时，因为同花顺的返回是随机的，所以会出现这个问题。

加入时间间隔试试
