### ISSUE TITLE
AKShare stock_individual_fund_flow_rank 接口问题报告

### ISSUE THREAD

**Issue by xkswz** [jindaxiang/akshare#1209]
**描述遇到的问题**

stock_individual_fund_flow_rank 接口 indicator="今日/3日/5日/10日" ，返回数据都一样,和网页展示不一致

1. 操作系统版本 : win10
2. Python 版本 :3.8
3. AKShare 版本 ：0.8.94
4. 接口的名称和代码  :https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html?highlight=stock_individual_fund_flow_rank#id95

5. 接口报错的截图或代码
stock_individual_fund_flow_rank_df3 = ak.stock_individual_fund_flow_rank(indicator="3日")

![image](https://user-images.githubusercontent.com/15240611/116806261-63870280-ab5e-11eb-8825-cbfc8931c2fe.png)
![image](https://user-images.githubusercontent.com/15240611/116806288-929d7400-ab5e-11eb-9537-4dcf8d9590f0.png)

6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **描述遇到的问题**
> 
> stock_individual_fund_flow_rank 接口 indicator="今日/3日/5日/10日" ，返回数据都一样,和网页展示不一致
> 
> 1. 操作系统版本 : win10
> 2. Python 版本 :3.8
> 3. AKShare 版本 ：0.8.94
> 4. 接口的名称和代码  :https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html?highlight=stock_individual_fund_flow_rank#id95
> 5. 接口报错的截图或代码
>    stock_individual_fund_flow_rank_df3 = ak.stock_individual_fund_flow_rank(indicator="3日")
> 
> ![image](https://user-images.githubusercontent.com/15240611/116806261-63870280-ab5e-11eb-8825-cbfc8931c2fe.png)
> ![image](https://user-images.githubusercontent.com/15240611/116806288-929d7400-ab5e-11eb-9537-4dcf8d9590f0.png)
> 
> 1. 期望获得的正确结果

感谢反馈问题，已修复，请升级到 0.8.99 版本使用
