### ISSUE TITLE
同花顺问财-股票热度接口 解析异常

### ISSUE THREAD

**Issue by luodadaRyan** [jindaxiang/akshare#1219]
大佬好，

接口链接：https://akshare-4gize6tod19f2d2e-1252952517.tcloudbaseapp.com/data/stock/stock.html#id170
故障描述：我修改了接口的查询条件
                  1. 为 “20210420热门股”时，出现了 “could not convert string to float: '1/4304'” 异常
                  2. 为 “20210421热门股”时，出现了“ rank_date_str = temp_df.columns[1].split("[")[1].strip("]")
IndexError: list index out of range”异常

好像是这两个查询条件和其他条件的响应数据顺序不太一样，还请看看呢~

修改的地方--->
![1](https://user-images.githubusercontent.com/36357256/117061751-233da500-ad55-11eb-8526-30817ba54ddc.png)

**Comment by luodadaRyan** [comment]
原始的条件是“热门5000股票”，这个会默认返回当天的数据，休市期间返回的是前一个交易日的数据，也就是4月30号的，这个解析是ok的~

**Comment by jindaxiang** [comment]
已增加 date 字段，可以指定日期，请查看文档使用
