### ISSUE TITLE
bond_investing_global 无返回值

### ISSUE THREAD

**Issue by congcong009** [jindaxiang/akshare#1256]
**Describe the bug**
bond_investing_global 无返回值

**To Reproduce**
1. ak.bond_investing_global(country="中国", index_name="中国1年期国债", period="每周", start_date="2000-01-01", end_date="2020-06-06")
2. 分别在国内IP和境外IP下测试
3. 报错如下：
```
File "/lib/python3.7/site-packages/akshare/bond/bond_investing.py", line 84, in bond_investing_global
    name_code_dict = bond_investing_global_country_name_url(country)
  File "/lib/python3.7/site-packages/akshare/bond/bond_investing.py", line 42, in bond_investing_global_country_name_url
    name_url_dict = _get_global_country_name_url()
  File "/lib/python3.7/site-packages/akshare/bond/bond_investing.py", line 27, in _get_global_country_name_url
    name_url_option_list = soup.find("select", attrs={"name": "country"}).find_all("option")[1:]
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Expected behavior**
之前通过境外IP是可以爬取的，但现在无论如何都获取不到数据了

**Additional context**
akshare版本号 0.9.19

**Comment by jindaxiang** [comment]
> 1. bond_investing_global

可以获取的

**Comment by congcong009** [comment]
我今天再次尝试，还是无法获取。
直接点击链接 https://cn.investing.com/rates-bonds/ ，截图如下，会出现一个延迟跳转的页面，请问可能是这个的原因么？
![image](https://user-images.githubusercontent.com/2680017/118580643-d335f800-b7c2-11eb-8500-84ce83a49fe5.png)

**Comment by jindaxiang** [comment]
> 我今天再次尝试，还是无法获取。
> 直接点击链接 https://cn.investing.com/rates-bonds/ ，截图如下，会出现一个延迟跳转的页面，请问可能是这个的原因么？
> ![image](https://user-images.githubusercontent.com/2680017/118580643-d335f800-b7c2-11eb-8500-84ce83a49fe5.png)

需要使用代理

**Comment by congcong009** [comment]
ok了，需要用新加坡的代理，美国的不行
