### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by xkswz** [jindaxiang/akshare#1257]
stock_individual_fund_flow_rank 接口 indicator="今日/3日/5日/10日" ，只返回单页数据

操作系统版本 : win10

Python 版本 :3.8

AKShare 版本 ：0.8.99

接口的名称和代码 :https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html?highlight=stock_individual_fund_flow_rank#id95

接口报错的截图或代码
stock_individual_fund_flow_rank_df3 = ak.stock_individual_fund_flow_rank(indicator="今日")

![image](https://user-images.githubusercontent.com/15240611/117932464-faa84300-b332-11eb-8fe0-f6a5f0388a6e.png)

**Comment by jindaxiang** [comment]
> stock_individual_fund_flow_rank

之前已经修复了，升级到最新版就可以了

**Comment by jindaxiang** [comment]
> stock_individual_fund_flow_rank 接口 indicator="今日/3日/5日/10日" ，只返回单页数据
> 
> 操作系统版本 : win10
> 
> Python 版本 :3.8
> 
> AKShare 版本 ：0.8.99
> 
> 接口的名称和代码 :https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html?highlight=stock_individual_fund_flow_rank#id95
> 
> 接口报错的截图或代码
> stock_individual_fund_flow_rank_df3 = ak.stock_individual_fund_flow_rank(indicator="今日")
> 
> ![image](https://user-images.githubusercontent.com/15240611/117932464-faa84300-b332-11eb-8fe0-f6a5f0388a6e.png)

感谢反馈问题，升级到 0.9.20 版本
