### ISSUE TITLE
希望能添加东方财富的可转债溢价率数据（带请求地址）

### ISSUE THREAD

**Issue by HickeyHsu** [jindaxiang/akshare#1275]
例如请求：http://datacenter.eastmoney.com/api/data/get?type=RPTA_WEB_KZZ_LS&sty=ALL&filter=(ZCODE="127028")&p=1&ps=8000&source=WEB&sr=1&st=date&callback=data&_=1621241191779

返回值中每个日期下的SWAPOR为转股溢价率 PUREBONDOR为转债溢价率
希望能添加！谢谢！

**Comment by HickeyHsu** [comment]
我尝试写了一下，可以运行
`
def get_es(self,symbol= "127028") -> pd.DataFrame:
 
        url = "http://datacenter.eastmoney.com/api/data/get"
        params = {
            "type": "RPTA_WEB_KZZ_LS",
            "token": "70f12f2f4f091e459a279469fe49eca5",
            "sty": "ALL",
            "filter": "(ZCODE={})".format(symbol),
            "st": "date",
            "sr": "1",
            "p": "1",
            "ps": "5000",
            "callback": "data",
            "_": "1621241191779",
        }
        r = requests.get(url, params=params)
        text_data = r.text
        json_data = demjson.decode(text_data[text_data.find("{") : -2])
        temp_df=pd.DataFrame(json_data['result']['data'])
        return temp_df
`

**Comment by jindaxiang** [comment]
> 例如请求：[http://datacenter.eastmoney.com/api/data/get?type=RPTA_WEB_KZZ_LS&sty=ALL&filter=(ZCODE="127028")&p=1&ps=8000&source=WEB&sr=1&st=date&callback=data&_=1621241191779](http://datacenter.eastmoney.com/api/data/get?type=RPTA_WEB_KZZ_LS&sty=ALL&filter=(ZCODE=%22127028%22)&p=1&ps=8000&source=WEB&sr=1&st=date&callback=data&_=1621241191779)
> 
> 返回值中每个日期下的SWAPOR为转股溢价率 PUREBONDOR为转债溢价率
> 希望能添加！谢谢！

已经存在该接口：bond_zh_cov
