### ISSUE TITLE
new data: econ idicator

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#13]
Hi,

I'm wondering if there is a plan to include more ceicdata.
For example,

https://www.ceicdata.com/zh-hans/china/economic-climate-indicator

Thanks for the great tool.

**Comment by jindaxiang** [comment]
Hello, I have checked the [CEIC](https://www.ceicdata.com/zh-hans/china/economic-climate-indicator) you provided, it just returned the [pic](https://www.ceicdata.com/datapage/charts/o_china_cn-business-cycle-signal/?type=column&period=1y&lang=zh-hans), it is impossible to get the accurate digits in pic

**Comment by edwardsun** [comment]
Sure. Closing for now.

**Comment by tonywangcn** [comment]
It's svg with xml style. It's very hard to extract the info.
