### ISSUE TITLE
AKShare 问题报告

### ISSUE THREAD

**Issue by slackwareer** [jindaxiang/akshare#1307]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
Linux raspberrypi 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

2. Python 版本
Python 3.7.3

3. AKShare 版本
akshare-0.9.43-py3-none-any.whl

4. 接口的名称和代码
import akshare的时候报错

5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/239952/119311579-d4c05e00-bca3-11eb-8073-2c69f151373c.png)
![image](https://user-images.githubusercontent.com/239952/119311607-ddb12f80-bca3-11eb-8467-35a4480ebdba.png)

6. 期望获得的正确结果
正常导入

**Comment by slackwareer** [comment]
应该是缺少py_mini_racer需要的本地 so

**Comment by slackwareer** [comment]
我用的是树莓派的系统。。。

**Comment by jindaxiang** [comment]
> 我用的是树莓派的系统。。。

目前该库并不支持 ARM 架构的

**Comment by slackwareer** [comment]
我测试了一下是js引擎的问题，可以把js引擎从mini_racer切换成execjs，用nodejs引擎就行了。执行js可以用一下代码替换：
js_code = execjs.compile(js_hash_text)
dict_list = js_code.call("d", us_js_decode)
不知道在后续版本是否可以考虑一下兼容性问题

@jindaxiang

**Comment by jindaxiang** [comment]
> 我测试了一下是js引擎的问题，可以把js引擎从mini_racer切换成execjs，用nodejs引擎就行了。执行js可以用一下代码替换：
> js_code = execjs.compile(js_hash_text)
> dict_list = js_code.call("d", us_js_decode)
> 不知道在后续版本是否可以考虑一下兼容性问题
> 
> @jindaxiang

之前就是从 execjs 切换过来的，因为 pyexecjs 目前是没有人维护的
