### ISSUE TITLE
获取上期所日线行情数据不准确

### ISSUE THREAD

**Issue by changvin** [jindaxiang/akshare#131]
在调用接口get_futures_daily获取上期所日线行情， 其中返回的turnover字段计算有问题，没有乘上相应品种的合约乘数，造成turnover数据不准确

**Comment by changvin** [comment]
在使用get_futures_daily 获取大商所（DCE）的日线数据也会有报错，原因是大商所多了液化石油气品种， 而akshare/futures/cons.py 的 DCE_MAP 变量没有 液化石油气 的映射，需要更新

**Comment by jindaxiang** [comment]
> 在使用get_futures_daily 获取大商所（DCE）的日线数据也会有报错，原因是大商所多了液化石油气品种， 而akshare/futures/cons.py 的 DCE_MAP 变量没有 液化石油气 的映射，需要更新

已修正，请升级 akshare 到 0.4.62

**Comment by jindaxiang** [comment]
> 在调用接口get_futures_daily获取上期所日线行情， 其中返回的turnover字段计算有问题，没有乘上相应品种的合约乘数，造成turnover数据不准确

这个问题由于期货合约乘数会调整，需要寻找准确的合约乘数
