### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by haliluyaya** [jindaxiang/akshare#1328]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：win10
2. Python 版本:3.8
3. AKShare 版本：0.9.53
4. 接口的名称和代码：bond_zh_us_rate_df = ak.bond_zh_us_rate()
5. 接口报错的截图或代码：未报错，但是返回的dataframe数据标签错误。
（1）“中国国债收益率10年”与实际数据不符合，经排查。“中国国债收益率5年”才是真正的10年期国债收益率。
（2）2021.5.30日测试数据还是正常，但是2021.5.31日测试返回数据就有问题。
6. 期望获得的正确结果：返回正确的数据和标签。

**Comment by jindaxiang** [comment]
> 4\. bond_zh_us_rate

已修复，请升级到 0.9.54
