### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by onlookor** [jindaxiang/akshare#1344]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. MacOS
2. Python 3.9
3. AKShare0.9.60
4. ak.stock_info_sz_name_code(indicator='A股列表')
5. 获得的dataframe列名“B股 简 称”中有空格，然而用参数‘B股列表'和’AB股列表'获得的该列名为不带空格的“B股简称”。
6. 不同参数取得的列名应该一致

**Comment by jindaxiang** [comment]
已修复，升级到 0.9.61 版本
