### ISSUE TITLE
AKShare 接口问题报告——网站的stock_info_sz_name_code接口输出参数描述与实际输出不一致

### ISSUE THREAD

**Issue by onlookor** [jindaxiang/akshare#1345]
1. macOS
2. Python 3.9
3. AKShare 0.9.60
4. stock_info_sz_name_code
5. 网站的输出参数中有“公司代码”、“公司简称”，没有“板块”；实际输出中没有“公司代码”，没有“公司简称”，有“板块”
6. 应保持一致。希望实际输出中包含“公司代码”。

**Comment by jindaxiang** [comment]
> 1. macOS
> 2. Python 3.9
> 3. AKShare 0.9.60
> 4. stock_info_sz_name_code
> 5. 网站的输出参数中有“公司代码”、“公司简称”，没有“板块”；实际输出中没有“公司代码”，没有“公司简称”，有“板块”
> 6. 应保持一致。希望实际输出中包含“公司代码”。

感谢反馈问题，请升级到 0.9.61，已修复
