### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by littleqiang** [jindaxiang/akshare#1363]
个股排行
接口: stock_em_hsgt_hold_stock
目标地址: http://data.eastmoney.com/hsgtcg/list.html
描述: 获取东方财富网-数据中心-沪深港通持股-个股排行
参数 indicator="沪股通"; choice of {"今日排行", "3日排行", "5日排行", "10日排行", "月排行", "季排行", "年排行"}

"5日排行", "10日排行"的数据返回的是重复数据，两个参数返回的都是"5日排行"的数据结果
akshare 版本 0.9.66
截图数据为2021-06-10

![截屏2021-06-11 下午11 42 06](https://user-images.githubusercontent.com/7484831/121714224-35f38880-cb10-11eb-81ff-6fb2a3b88b14.png)

目标网站数据
![截屏2021-06-11 下午11 43 05](https://user-images.githubusercontent.com/7484831/121714253-3ee45a00-cb10-11eb-8112-4f1fefc5e024.png)
![截屏2021-06-11 下午11 43 14](https://user-images.githubusercontent.com/7484831/121714277-4277e100-cb10-11eb-9950-fc9f4ca69b8d.png)

**Comment by littleqiang** [comment]
版本 0.9.66

**Comment by jindaxiang** [comment]
> 个股排行
> 接口: stock_em_hsgt_hold_stock
> 目标地址: http://data.eastmoney.com/hsgtcg/list.html
> 描述: 获取东方财富网-数据中心-沪深港通持股-个股排行
> 参数 indicator="沪股通"; choice of {"今日排行", "3日排行", "5日排行", "10日排行", "月排行", "季排行", "年排行"}
> 
> "5日排行", "10日排行"的数据返回的是重复数据，两个参数返回的都是"5日排行"的数据结果
> akshare 版本 0.9.66
> 截图数据为2021-06-10
> 
> ![截屏2021-06-11 下午11 42 06](https://user-images.githubusercontent.com/7484831/121714224-35f38880-cb10-11eb-81ff-6fb2a3b88b14.png)
> 
> 目标网站数据
> ![截屏2021-06-11 下午11 43 05](https://user-images.githubusercontent.com/7484831/121714253-3ee45a00-cb10-11eb-8112-4f1fefc5e024.png)
> ![截屏2021-06-11 下午11 43 14](https://user-images.githubusercontent.com/7484831/121714277-4277e100-cb10-11eb-9950-fc9f4ca69b8d.png)

感谢反馈问题，请升级到 0.9.67 已修复
