### ISSUE TITLE
index_name isn't usable in currency_hist_df

### ISSUE THREAD

**Issue by fengfenghaha** [jindaxiang/akshare#140]
TypeError                                 Traceback (most recent call last)
<ipython-input-38-e7bd22eed5c8> in <module>
      1 import akshare as ak
----> 2 currency_hist_df = ak.currency_hist(index_name="usd/jpy", start_date="2005/01/01", end_date="2020/01/17")
      3 print(currency_hist_df)

TypeError: currency_hist() got an unexpected keyword argument 'index_name'

I already upgraded akshare. Without index_name the code runs well.

**Comment by jindaxiang** [comment]
> TypeError Traceback (most recent call last)
> in
> 1 import akshare as ak
> ----> 2 currency_hist_df = ak.currency_hist(index_name="usd/jpy", start_date="2005/01/01", end_date="2020/01/17")
> 3 print(currency_hist_df)
> 
> TypeError: currency_hist() got an unexpected keyword argument 'index_name'
> 
> I already upgraded akshare. Without index_name the code runs well.

I have checked the interface, it's work well.
Please update to lastest version.

**Comment by jindaxiang** [comment]
> TypeError Traceback (most recent call last)
> in
> 1 import akshare as ak
> ----> 2 currency_hist_df = ak.currency_hist(index_name="usd/jpy", start_date="2005/01/01", end_date="2020/01/17")
> 3 print(currency_hist_df)
> 
> TypeError: currency_hist() got an unexpected keyword argument 'index_name'
> 
> I already upgraded akshare. Without index_name the code runs well.

I am so sorry for that, I had fixed the example error in documentation!
