### ISSUE TITLE
akshare can‘’

### ISSUE THREAD

**Issue by ghmole** [jindaxiang/akshare#1403]
**Describe the bug**
after import akshare,the quit() function is frozen

**To Reproduce**
import akshare as ak

quit()

**Expected behavior**

full environment like this:
# packages in environment at D:\Ac3\envs\akshare:
#
# Name                    Version                   Build  Channel
akshare                   0.8.78                   pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
ca-certificates           2021.4.13            haa95532_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2020.12.5        py38haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
colorama                  0.4.4                    pypi_0    pypi
decorator                 5.0.7                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
lxml                      4.6.3                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.4.1                    pypi_0    pypi
mplfinance                0.12.7a12                pypi_0    pypi
numpy                     1.20.2                   pypi_0    pypi
openpyxl                  3.0.7                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.4                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.0.1           py38haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
py-mini-racer             0.5.0                    pypi_0    pypi
pygments                  2.8.1                    pypi_0    pypi
pypinyin                  0.41.0                   pypi_0    pypi
python                    3.8.5                h5fd99cc_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                52.0.0           py38haa95532_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
snowballstemmer           2.1.0                    pypi_0    pypi
soupsieve                 2.2.1                    pypi_0    pypi
sphinx                    3.5.4                    pypi_0    pypi
sphinx-hoverxref          0.5b1                    pypi_0    pypi
sphinx-markdown-tables    0.0.15                   pypi_0    pypi
sphinx-notfound-page      0.6                      pypi_0    pypi
sphinx-rtd-theme          0.5.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tqdm                      4.60.0                   pypi_0    pypi
urllib3                   1.26.4                   pypi_0    pypi
vc                        14.2                 h21ff451_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
vs2015_runtime            14.27.29016          h5e58377_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
websocket-client          0.58.0                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wincertstore              0.2                      py38_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
zhconv                    1.4.1                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main

**Comment by jindaxiang** [comment]
应该是你本地环境的问题
