### ISSUE TITLE
如何关闭获取数据时的进度条

### ISSUE THREAD

**Issue by qianxuanyon** [jindaxiang/akshare#1410]
执行循环获取时 进度条太多了 怎么才能关掉

**Comment by jindaxiang** [comment]
> 执行循环获取时 进度条太多了 怎么才能关掉

用 warning 函数试试

**Comment by qianxuanyon** [comment]
warnings.filterwarnings
不起作用 用的是tqdm吗
我会获取每个股票的财报 4000多个股票 会打出来4000多个进度条

**Comment by jindaxiang** [comment]
> warnings.filterwarnings
> 不起作用 用的是tqdm吗
> 我会获取每个股票的财报 4000多个股票 会打出来4000多个进度条

已修复，升级到 0.9.88
