### ISSUE TITLE
字段名称英文支持

### ISSUE THREAD

**Issue by qianxuanyon** [jindaxiang/akshare#1411]
获取到的数据 字段名称全部都是中文 在需要入库时需要手工每个起名字 

是否可以考虑在函数中增加一个参数 用来切换中英文显示

**Comment by jindaxiang** [comment]
> 获取到的数据 字段名称全部都是中文 在需要入库时需要手工每个起名字
> 
> 是否可以考虑在函数中增加一个参数 用来切换中英文显示

之前考虑过这个问题，为了跟目标网站对应，还是用中文字段名
