### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by wzyblowfire** [jindaxiang/akshare#1426]
版本：0.9.02
实时行情数据-东财 stock_zh_a_spot_em接口不存在

**Comment by jindaxiang** [comment]
> stock_zh_a_spot_em

请确认是最新版本

**Comment by wzyblowfire** [comment]
打错了，版本为0.9.92，
![image](https://user-images.githubusercontent.com/33181375/124359536-63b68380-dc1d-11eb-9368-8a5bd6208fa8.png)

**Comment by wzyblowfire** [comment]
> > stock_zh_a_spot_em
> 
> 请确认是最新版本
> 打错了版本为0.9.92

**Comment by jindaxiang** [comment]
> > > stock_zh_a_spot_em
> > 
> > 
> > 请确认是最新版本
> > 打错了版本为0.9.92

我这边测试是正常的，你需要检查线本地环境配置

**Comment by wzyblowfire** [comment]
> > > > stock_zh_a_spot_em
> > > 
> > > 
> > > 请确认是最新版本
> > > 打错了版本为0.9.92
> 
> 我这边测试是正常的，你需要检查线本地环境配置

感谢~已解决问题
