### ISSUE TITLE
cctv新闻数据处理错误

### ISSUE THREAD

**Issue by liulinlin90** [jindaxiang/akshare#1439]
cctv新闻数据处理错误

```
>>> import akshare as ak
>>> ak.news_cctv(date='20210706')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/akshare/news/news_cctv.py", line 30, in news_cctv
    url = soup.find("a", text=pattern)["href"]
TypeError: 'NoneType' object is not subscriptable
>>> 
```

**Comment by jindaxiang** [comment]
> cctv新闻数据处理错误
> 
> ```
> >>> import akshare as ak
> >>> ak.news_cctv(date='20210706')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/akshare/news/news_cctv.py", line 30, in news_cctv
>     url = soup.find("a", text=pattern)["href"]
> TypeError: 'NoneType' object is not subscriptable
> >>> 
> ```

感谢反馈问题，请升级到 AKShare 0.9.99，已修复
