### ISSUE TITLE
关于期货接口中 交易法门的问题

### ISSUE THREAD

**Issue by haozimao** [jindaxiang/akshare#1468]
我是一名做尿素的现货商，玩点期货，了解到交易法门也是通过你提供的接口，但是交易法门得数据非常不准确，容易产生误导，但慎重采用他的东西

**Comment by jindaxiang** [comment]
> 我是一名做尿素的现货商，玩点期货，了解到交易法门也是通过你提供的接口，但是交易法门得数据非常不准确，容易产生误导，但慎重采用他的东西

好的，AKShare 的交易法门的数据接口目前没有继续维护，后期会去掉该接口
