### ISSUE TITLE
AKShare 接口问题报告：stock_zh_a_tick_tx 无法获取任意日期的分笔数据

### ISSUE THREAD

**Issue by shenmufeng** [jindaxiang/akshare#1488]
#已更新至最新

import akshare as ak
stock_zh_a_tick_tx_df = ak.stock_zh_a_tick_tx(code="sh600848", trade_date="20210716")
print(stock_zh_a_tick_tx_df)

#返回
Empty DataFrame
Columns: [暂无数据]
Index: []

日期可以换成任意日期来重现

同样的，网易的获取数据似乎会卡住无法继续。
谢谢

**Comment by jindaxiang** [comment]
> #已更新至最新
> 
> import akshare as ak
> stock_zh_a_tick_tx_df = ak.stock_zh_a_tick_tx(code="sh600848", trade_date="20210716")
> print(stock_zh_a_tick_tx_df)
> 
> #返回
> Empty DataFrame
> Columns: [暂无数据]
> Index: []
> 
> 日期可以换成任意日期来重现
> 
> 同样的，网易的获取数据似乎会卡住无法继续。
> 谢谢

数据源出问题了，暂时无法获取数据

**Comment by JuliusPeng** [comment]
文档中都说明了，自20210611获取不到数据

**Comment by charmby** [comment]
>>> stock_zh_a_tick_163_df = ak.stock_zh_a_tick_163(code="sh600848", trade_date="20210127")
http://quotes.money.163.com/cjmx/2021/20210127/0600848.xls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/charmby/local/conda/miniconda3/lib/python3.8/site-packages/akshare/stock/stock_zh_a_tick_tx_163.py", line 114, in stock_zh_a_tick_163
    temp_df = pd.read_excel(BytesIO(r.content))
  File "/Users/charmby/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/charmby/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/Users/charmby/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
>>> print(stock_zh_a_tick_163_df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'stock_zh_a_tick_163_df' is not defined
腾讯和网易的数据都获取不了了

**Comment by jindaxiang** [comment]
> > > > stock_zh_a_tick_163_df = ak.stock_zh_a_tick_163(code="sh600848", trade_date="20210127")
> > > > http://quotes.money.163.com/cjmx/2021/20210127/0600848.xls
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/Users/charmby/local/conda/miniconda3/lib/python3.8/site-packages/akshare/stock/stock_zh_a_tick_tx_163.py", line 114, in stock_zh_a_tick_163
> > > > temp_df = pd.read_excel(BytesIO(r.content))
> > > > File "/Users/charmby/.local/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
> > > > return func(*args, **kwargs)
> > > > File "/Users/charmby/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 364, in read_excel
> > > > io = ExcelFile(io, storage_options=storage_options, engine=engine)
> > > > File "/Users/charmby/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1195, in **init**
> > > > raise ValueError(
> > > > ValueError: Excel file format cannot be determined, you must specify an engine manually.
> > > > print(stock_zh_a_tick_163_df)
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > NameError: name 'stock_zh_a_tick_163_df' is not defined
> > > > 腾讯和网易的数据都获取不了了

尝试 用 stock_zh_a_tick_163_now 和 stock_zh_a_tick_tx_js 获取近期，历史的数据由于原网站的问题可能无法获取
