### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by mumumiya** [jindaxiang/akshare#1492]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 3.7
3. AKShare 版本 1.0.25
4. 接口的名称和代码  期货 展期收益率 get_roll_yield_bar
5. 接口报错的截图或代码
ak.get_roll_yield_bar(type_method="var", date="20201031", plot=False)
![image](https://user-images.githubusercontent.com/24890210/126166261-73904214-b291-46bb-902c-5d8ea0d88d2f.png)

6. 期望获得的正确结果：返回所有品种当天的展期收益率

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本 3.7
> 3. AKShare 版本 1.0.25
> 4. 接口的名称和代码  期货 展期收益率 get_roll_yield_bar
> 5. 接口报错的截图或代码
>    ak.get_roll_yield_bar(type_method="var", date="20201031", plot=False)
>    ![image](https://user-images.githubusercontent.com/24890210/126166261-73904214-b291-46bb-902c-5d8ea0d88d2f.png)
> 6. 期望获得的正确结果：返回所有品种当天的展期收益率

非交易日
