### ISSUE TITLE
郑商所的注册清单爬虫失败

### ISSUE THREAD

**Issue by hsinhua** [jindaxiang/akshare#1493]
**问题**
无法获取郑商所的注册清单。

**To Reproduce**
ak.get_receipt("20120101", "20210720", ["TA"])  会报错，debug下请求回报是412。

**Comment by jindaxiang** [comment]
> **问题**
> 无法获取郑商所的注册清单。
> 
> **To Reproduce**
> ak.get_receipt("20120101", "20210720", ["TA"]) 会报错，debug下请求回报是412。

不能获取这么长的历史周期
