### ISSUE TITLE
申万一级行业成分股信息增加历史数据

### ISSUE THREAD

**Issue by liningbo** [jindaxiang/akshare#1503]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
sw_index_cons 只能获取最新的申万一级行业的成分股，没有历史数据，回测时不能用最新的。建议增加申万一级行业成分股信息的历史数据，可以获取过去某个时间点，申万一级行业的成分股列表。
**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> sw_index_cons 只能获取最新的申万一级行业的成分股，没有历史数据，回测时不能用最新的。建议增加申万一级行业成分股信息的历史数据，可以获取过去某个时间点，申万一级行业的成分股列表。
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

没有合适的数据源
