### ISSUE TITLE
深交所两融数据接口

### ISSUE THREAD

**Issue by scanfyu** [jindaxiang/akshare#1516]
**Is your feature request related to a problem? Please describe.**
希望提供深交所融资融券标的信息以及融资融券交易明细的数据。

**Describe the solution you'd like**
目标页地址：
融资融券标的证券信息：http://www.szse.cn/disclosure/margin/object/index.html
融资融券交易明细：http://www.szse.cn/disclosure/margin/margin/index.html

**Describe alternatives you've considered**
目前暂未找到更合适的数据源地址

**Additional context**
希望提供数据接口，谢谢。

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 希望提供深交所融资融券标的信息以及融资融券交易明细的数据。
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 目标页地址：
> 融资融券标的证券信息：http://www.szse.cn/disclosure/margin/object/index.html
> 融资融券交易明细：http://www.szse.cn/disclosure/margin/margin/index.html
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 目前暂未找到更合适的数据源地址
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 希望提供数据接口，谢谢。

已更新，升级到 1.0.40 版本
