### ISSUE TITLE
AKShare 接口问题报告 指数历史成份 index_stock_hist

### ISSUE THREAD

**Issue by nigo81** [jindaxiang/akshare#1519]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 linux manjaro
2. Python 版本 python 3.9.6
3. AKShare 版本 1.0.41
4. 接口的名称和代码 index_stock_hist
```python
import akshare as ak
code = 'sz399975'
df = ak.index_stock_hist(code)
print(df)
```
报错：
```python
Traceback (most recent call last):
  File "/home/nigo/tmp/test.py", line 3, in <module>
    df = ak.index_stock_hist(code)
  File "/home/nigo/.local/lib/python3.9/site-packages/akshare/index/index_cons.py", line 147, in index_stock_hist
    for page in range(2, int(last_page_num)+1):
ValueError: invalid literal for int() with base 10: '历史成份'
```
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/38601513/127335957-3c61428b-8bba-43f6-b0e4-67f117e942b5.png)
![image](https://user-images.githubusercontent.com/38601513/127336055-8c23cd9d-af4a-4889-a3bd-d4bfd2de89c5.png)

我看了下'sz399975'网站上的是只有一页，而作者你的代码应该是去获取页码，从第二页开始的。

6. 期望获得的正确结果
针对这种指数历史成分只有一页的，不能正确获取。麻烦修复下。

**Comment by jindaxiang** [comment]
> ```python
> code = 'sz399975'
> df = ak.index_stock_hist(code)
> ```

感谢反馈问题，已修复，升级到 1.0.42 版本使用
