### ISSUE TITLE
AKShare 接口问题报告

### ISSUE THREAD

**Issue by scanfyu** [jindaxiang/akshare#1522]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
win10
2. Python 版本
3.8
3. AKShare 版本
1.0.43
4. 接口的名称和代码
df = ak.stock_margin_detail_szse(date="20210728")

5. 接口报错的截图或代码
ValueError                                Traceback (most recent call last)
<ipython-input-2-24901e891519> in <module>
----> 1 df = ak.stock_margin_detail_szse(date="20210728")

~\miniconda3\envs\data\lib\site-packages\akshare\stock_feature\stock_szse_margin.py in stock_margin_detail_szse(date)
    147     big_df["融资买入额"] = pd.to_numeric(big_df["融资买入额"])
    148     big_df["融资余额"] = pd.to_numeric(big_df["融资余额"])
--> 149     big_df["融券卖出量"] = pd.to_numeric(big_df["融券卖出量"])
    150     big_df["融券余量"] = big_df["融券余量"].str.replace(",", "")
    151     big_df["融券余量"] = pd.to_numeric(big_df["融券余量"])

~\miniconda3\envs\data\lib\site-packages\pandas\core\tools\numeric.py in to_numeric(arg, errors, downcast)
    153         try:
    154             values = lib.maybe_convert_numeric(
--> 155                 values, set(), coerce_numeric=coerce_numeric
    156             )
    157         except (ValueError, TypeError):

pandas\_libs\lib.pyx in pandas._libs.lib.maybe_convert_numeric()

ValueError: Unable to parse string "1,155.64" at position 42

6. 期望获得的正确结果
正常获取数据。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    win10
> 2. Python 版本
>    3.8
> 3. AKShare 版本
>    1.0.43
> 4. 接口的名称和代码
>    df = ak.stock_margin_detail_szse(date="20210728")
> 5. 接口报错的截图或代码
>    ValueError                                Traceback (most recent call last)
>     in 
>    ----> 1 df = ak.stock_margin_detail_szse(date="20210728")
> 
> ~\miniconda3\envs\data\lib\site-packages\akshare\stock_feature\stock_szse_margin.py in stock_margin_detail_szse(date)
> 147 big_df["融资买入额"] = pd.to_numeric(big_df["融资买入额"])
> 148 big_df["融资余额"] = pd.to_numeric(big_df["融资余额"])
> --> 149 big_df["融券卖出量"] = pd.to_numeric(big_df["融券卖出量"])
> 150 big_df["融券余量"] = big_df["融券余量"].str.replace(",", "")
> 151 big_df["融券余量"] = pd.to_numeric(big_df["融券余量"])
> 
> ~\miniconda3\envs\data\lib\site-packages\pandas\core\tools\numeric.py in to_numeric(arg, errors, downcast)
> 153 try:
> 154 values = lib.maybe_convert_numeric(
> --> 155 values, set(), coerce_numeric=coerce_numeric
> 156 )
> 157 except (ValueError, TypeError):
> 
> pandas_libs\lib.pyx in pandas._libs.lib.maybe_convert_numeric()
> 
> ValueError: Unable to parse string "1,155.64" at position 42
> 
> 1. 期望获得的正确结果
>    正常获取数据。

已修复，升级到 1.0.44 使用
