### ISSUE TITLE
全部A股等权重市盈率、市净率及中位数 

### ISSUE THREAD

**Issue by nigo81** [jindaxiang/akshare#1526]
1、全部A股等权重市盈率、中位数：
网址：https://www.legulegu.com/stockdata/a-ttm-lyr
截图：
![image](https://user-images.githubusercontent.com/38601513/127522139-8d30ed27-595e-4a80-ba0b-63c569372491.png)

2、全部A股等权生市净率、中位数：
网址：https://www.legulegu.com/stockdata/all-pb
![image](https://user-images.githubusercontent.com/38601513/127522314-8938b95b-3530-4e03-84cb-672af6661290.png)

以上两个指标对于判断A股现目前是便宜还是贵有作用，而自己去拿个股K线数据计算挺麻烦的。
作者考虑是否后面可以做一个接口。
respect

**Comment by jindaxiang** [comment]
> 1、全部A股等权重市盈率、中位数：
> 网址：https://www.legulegu.com/stockdata/a-ttm-lyr
> 截图：
> ![image](https://user-images.githubusercontent.com/38601513/127522139-8d30ed27-595e-4a80-ba0b-63c569372491.png)
> 
> 2、全部A股等权生市净率、中位数：
> 网址：https://www.legulegu.com/stockdata/all-pb
> ![image](https://user-images.githubusercontent.com/38601513/127522314-8938b95b-3530-4e03-84cb-672af6661290.png)
> 
> 以上两个指标对于判断A股现目前是便宜还是贵有作用，而自己去拿个股K线数据计算挺麻烦的。
> 作者考虑是否后面可以做一个接口。
> respect

已更新，升级到 1.0.57 版本使用，https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html#id140
