### ISSUE TITLE
可否提供 东方财富 的 复权因子？stock_zh_a_hist 接口相关

### ISSUE THREAD

**Issue by J-Liu** [jindaxiang/akshare#1530]
stock_zh_a_hist提供东方财富的日K数据，可以选择前复权/后复权/不复权，可是做回测用后复权数据，显示用前复权，前复权又是经常变化的，存两份也不合适。

希望能和新浪接口一样提供获取 复权因子 的方法或者接口。

**Comment by jindaxiang** [comment]
> stock_zh_a_hist提供东方财富的日K数据，可以选择前复权/后复权/不复权，可是做回测用后复权数据，显示用前复权，前复权又是经常变化的，存两份也不合适。
> 
> 希望能和新浪接口一样提供获取 复权因子 的方法或者接口。

东财数据直接返回复权后数据，并没有提供复权因子
