### ISSUE TITLE
可否让stock_individual_fund_flow可指定日期范围？

### ISSUE THREAD

**Issue by J-Liu** [jindaxiang/akshare#1531]
stock_individual_fund_flow现在返回当前开始回溯100个交易日的资金流向，做回测的时候，时间范围往往是超过100个交易日的，只有近100个交易日的数据往往不够用。

希望可以提供一个可选的日期范围。

**Comment by jindaxiang** [comment]
> stock_individual_fund_flow

目标网站只提供上述数据，建议在本地逐日保存
