### ISSUE TITLE
macro_china.macro_china_gdp_yearly() 获取的gdp数据不全，有误。

### ISSUE THREAD

**Issue by jimmylgz** [jindaxiang/akshare#1544]
今天(2021/8/6)尝试用该指令获取gdp数据，
得到的最新尾部数据如下：

2020-04-17   -6.8
2020-07-16    3.2
2020-10-19    4.9
2021-01-18    6.5
2021-04-16    0.0
Name: gdp, dtype: float64

然而在目标网站上已看到数据已经更新到2021-07-15了，且2021-04-16数据应该为18.3。

谢谢。

**Comment by jindaxiang** [comment]
> 今天(2021/8/6)尝试用该指令获取gdp数据，
> 得到的最新尾部数据如下：
> 
> 2020-04-17 -6.8
> 2020-07-16 3.2
> 2020-10-19 4.9
> 2021-01-18 6.5
> 2021-04-16 0.0
> Name: gdp, dtype: float64
> 
> 然而在目标网站上已看到数据已经更新到2021-07-15了，且2021-04-16数据应该为18.3。
> 
> 谢谢。

哪个接口？

**Comment by jimmylgz** [comment]
接口: macro_china_gdp_yearly

**Comment by jindaxiang** [comment]
> 接口: macro_china_gdp_yearly

已修复，升级到 1.0.54
