### ISSUE TITLE
沪深港通持股-每日个股统计，接口获取数据

### ISSUE THREAD

**Issue by DAMON-CHOENG** [jindaxiang/akshare#1547]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:  
    win10

2. Python 版本: 
    3.8.8

3. AKShare 版本: 
    1.0.54

4. 接口的名称和代码:
import akshare as ak
stock_em_hsgt_stock_statistics_df = ak.stock_em_hsgt_stock_statistics(symbol="南向持股", start_date="20201218", end_date="20201218")
print(stock_em_hsgt_stock_statistics_df)

5. 接口报错的截图或代码:
ValueError: Length mismatch: Expected axis has 0 elements, new values have 16 elements

6. 期望获得的正确结果:
    可能正常获取数据。

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AKShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本:
>    win10
> 2. Python 版本:
>    3.8.8
> 3. AKShare 版本:
>    1.0.54
> 4. 接口的名称和代码:
>    import akshare as ak
>    stock_em_hsgt_stock_statistics_df = ak.stock_em_hsgt_stock_statistics(symbol="南向持股", start_date="20201218", end_date="20201218")
>    print(stock_em_hsgt_stock_statistics_df)
> 5. 接口报错的截图或代码:
>    ValueError: Length mismatch: Expected axis has 0 elements, new values have 16 elements
> 6. 期望获得的正确结果:
>    可能正常获取数据。

该接口只能获取近期的数据
