### ISSUE TITLE
AKShare 接口问题报告: macro_china_freight_index()  下载时间过长

### ISSUE THREAD

**Issue by GXY2017** [jindaxiang/akshare#1554]
建议更新该接口如下：

    def freightcostsina(self, numberofdays):
        url = "http://quotes.sina.cn/mac/view/vMacExcle.php?"
        params = {
            'cate':'industry',
            'event': '22',
            'from': '0',
            'num': numberofdays,
            'condition': '',
        }

        r = requests.get(url, params = params)
        l = r.content.decode('gbk').split('\n')[2:]

        df = pd.DataFrame(data=l).iloc[:, 0].str.split(',', expand=True)

        df2 = pd.DataFrame(data=df.iloc[1:, :].values, columns=list(df.iloc[0, :])) \
            .dropna(axis=1, how='all').dropna(axis=0)

        df2.set_index(['截止日期'], inplace=True)
        df2.index = pd.to_datetime(df2.index).date
        df2.index.name = '截止日期'
        return df2

**Comment by jindaxiang** [comment]
> 建议更新该接口如下：
> 
> ```
> def freightcostsina(self, numberofdays):
>     url = "http://quotes.sina.cn/mac/view/vMacExcle.php?"
>     params = {
>         'cate':'industry',
>         'event': '22',
>         'from': '0',
>         'num': numberofdays,
>         'condition': '',
>     }
> 
>     r = requests.get(url, params = params)
>     l = r.content.decode('gbk').split('\n')[2:]
> 
>     df = pd.DataFrame(data=l).iloc[:, 0].str.split(',', expand=True)
> 
>     df2 = pd.DataFrame(data=df.iloc[1:, :].values, columns=list(df.iloc[0, :])) \
>         .dropna(axis=1, how='all').dropna(axis=0)
> 
>     df2.set_index(['截止日期'], inplace=True)
>     df2.index = pd.to_datetime(df2.index).date
>     df2.index.name = '截止日期'
>     return df2
> ```

已更新该接口，升级到 1.0.55 版本
