### ISSUE TITLE
商品日线历史数据报错

### ISSUE THREAD

**Issue by YjWoo** [jindaxiang/akshare#1563]
商品日线历史数据报错

函数：futures_zh_daily_sina

line 406, in futures_zh_daily_sina
    temp_df.columns = ["date", "open", "high", "low", "close", "volume", "hold"]
ValueError: Length mismatch: Expected axis has 8 elements, new values have 7 elements

经检查，错误原因为新浪数据新增结算价数据，建议修改为：
temp_df.columns = ["date", "open", "high", "low", "close", "volume", "hold","settle"]

**Comment by jindaxiang** [comment]
> 商品日线历史数据报错
> 
> 函数：futures_zh_daily_sina
> 
> line 406, in futures_zh_daily_sina
> temp_df.columns = ["date", "open", "high", "low", "close", "volume", "hold"]
> ValueError: Length mismatch: Expected axis has 8 elements, new values have 7 elements
> 
> 经检查，错误原因为新浪数据新增结算价数据，建议修改为：
> temp_df.columns = ["date", "open", "high", "low", "close", "volume", "hold","settle"]

感谢反馈问题，已修复该问题，请升级到 1.0.59 版本使用
