### ISSUE TITLE
stock_zh_a_tick_163调用失败

### ISSUE THREAD

**Issue by watsonwuh** [jindaxiang/akshare#1575]
**Describe the bug**
ValueError: Excel file format cannot be determined, you must specify an engine manually.

**Additional context**
pd.read_excel这里提示
ValueError: Excel file format cannot be determined, you must specify an engine manually.
貌似163也拿不到内容了，返回是一个错误提示的html片段

**Comment by jindaxiang** [comment]
> **Describe the bug**
> ValueError: Excel file format cannot be determined, you must specify an engine manually.
> 
> **Additional context**
> pd.read_excel这里提示
> ValueError: Excel file format cannot be determined, you must specify an engine manually.
> 貌似163也拿不到内容了，返回是一个错误提示的html片段

是的，目前该数据暂时不能获取

**Comment by watsonwuh** [comment]
> > **Describe the bug**
> > ValueError: Excel file format cannot be determined, you must specify an engine manually.
> > **Additional context**
> > pd.read_excel这里提示
> > ValueError: Excel file format cannot be determined, you must specify an engine manually.
> > 貌似163也拿不到内容了，返回是一个错误提示的html片段
> 
> 是的，目前该数据暂时不能获取

有可用替代API吗？
