### ISSUE TITLE
AttributeError: 'PandasArray' object has no attribute '_str_split'

### ISSUE THREAD

**Issue by lonngxiang** [jindaxiang/akshare#1624]
stock_info_sz_name_code_df = ak.stock_info_sz_name_code(indicator="A股列表")
print(stock_info_sz_name_code_df)

**Comment by jindaxiang** [comment]
> stock_info_sz_name_code_df = ak.stock_info_sz_name_code(indicator="A股列表")
> print(stock_info_sz_name_code_df)

可以正常运行，请核对下版本

**Comment by lonngxiang** [comment]
> > stock_info_sz_name_code_df = ak.stock_info_sz_name_code(indicator="A股列表")
> > print(stock_info_sz_name_code_df)
> 
> 可以正常运行，请核对下版本

你好，1.0.84及升级后1.0.87的都不行

**Comment by lonngxiang** [comment]
> > stock_info_sz_name_code_df = ak.stock_info_sz_name_code(indicator="A股列表")
> > print(stock_info_sz_name_code_df)
> 
> 可以正常运行，请核对下版本

<ipython-input-5-217366830888> in <module>
      1 import akshare as ak
      2 print(ak.__version__)
----> 3 stock_info_a_code_name_df = ak.stock_info_a_code_name()
      4 print(stock_info_a_code_name_df)
      5 # stock_info_sz_name_code_df = ak.stock_info_sz_name_code(indicator="A股列表")

D:\acaconda\lib\site-packages\akshare\stock\stock_info.py in stock_info_a_code_name()
    234     stock_sh.columns = ["公司代码", "公司简称"]
    235 
--> 236     stock_sz = stock_info_sz_name_code(indicator="A股列表")
    237     stock_sz["A股代码"] = stock_sz["A股代码"].astype(str).str.zfill(6)
    238     big_df = big_df.append(stock_sz[["A股代码", "A股简称"]], ignore_index=True)

D:\acaconda\lib\site-packages\akshare\stock\stock_info.py in stock_info_sz_name_code(indicator)
     36     if len(temp_df) > 10:
     37         if indicator == "A股列表":
---> 38             temp_df["A股代码"] = temp_df["A股代码"].astype(str).str.split('.', expand=True).iloc[:, 0].str.zfill(6).str.replace("000nan", "")
     39             temp_df = temp_df[[
     40                 '板块',

D:\acaconda\lib\site-packages\pandas\core\strings\accessor.py in wrapper(self, *args, **kwargs)
     99                 )
    100                 raise TypeError(msg)
--> 101             return func(self, *args, **kwargs)
    102 
    103         wrapper.__name__ = func_name

D:\acaconda\lib\site-packages\pandas\core\strings\accessor.py in split(self, pat, n, expand)
    744     @forbid_nonstring_types(["bytes"])
    745     def split(self, pat=None, n=-1, expand=False):
--> 746         result = self._data.array._str_split(pat, n, expand)
    747         return self._wrap_result(result, returns_string=expand, expand=expand)
    748 

AttributeError: 'PandasArray' object has no attribute '_str_split'

**Comment by jindaxiang** [comment]
> _str_split

把pandas升级到最新版试试，我这边没问题

**Comment by lonngxiang** [comment]
> > _str_split
> 
> 把pandas升级到最新版试试，我这边没问题

好的谢谢回复，确实是pandas版本问题，升级后解决
