### ISSUE TITLE
AKShare 网站保证金比例数据字典里缺少生猪和花生

### ISSUE THREAD

**Issue by lucasguo** [jindaxiang/akshare#1625]
akshare的保证金比例数据字典（https://www.akshare.xyz/zh_CN/latest/data/futures/futures.html?highlight=%E6%9C%9F%E8%B4%A7#id5）里缺少生猪（LH）和花生(PK)，是否可以补充下

**Comment by jindaxiang** [comment]
> akshare的保证金比例数据字典（[https://www.akshare.xyz/zh_CN/latest/data/futures/futures.html?highlight=%E6%9C%9F%E8%B4%A7#id5）里缺少生猪（LH）和花生(PK)，是否可以补充下](https://www.akshare.xyz/zh_CN/latest/data/futures/futures.html?highlight=%E6%9C%9F%E8%B4%A7#id5%EF%BC%89%E9%87%8C%E7%BC%BA%E5%B0%91%E7%94%9F%E7%8C%AA%EF%BC%88LH%EF%BC%89%E5%92%8C%E8%8A%B1%E7%94%9F(PK)%EF%BC%8C%E6%98%AF%E5%90%A6%E5%8F%AF%E4%BB%A5%E8%A1%A5%E5%85%85%E4%B8%8B)

已修复，并添加了其他相关字段，注意该数据仅供参考
