### ISSUE TITLE
AKShare 接口问题报告：2021年9月16日ak.stock_em_hsgt_hold_stock无法获取数据

### ISSUE THREAD

**Issue by xnw176** [jindaxiang/akshare#1666]
**遇到任何问题，请先确认您的 AKShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本：MAC OS 11.6
2. Python 版本：3.8
3. AKShare 版本：1.1.9
4. 接口的名称和代码：ak.stock_em_hsgt_hold_stock
5. 接口报错的截图或代码
~/opt/anaconda3/lib/python3.8/site-packages/akshare/stock_feature/stock_em_hsgt.py in stock_em_hsgt_hold_stock(market, indicator)
    372     temp_df.reset_index(inplace=True)
    373     temp_df['index'] = range(1, len(temp_df)+1)
--> 374     temp_df.columns = [
    375         '序号',
    376         '_',

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py in __setattr__(self, name, value)
   5150         try:
   5151             object.__getattribute__(self, name)
-> 5152             return object.__setattr__(self, name, value)
   5153         except AttributeError:
   5154             pass

pandas/_libs/properties.pyx in pandas._libs.properties.AxisProperty.__set__()

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py in _set_axis(self, axis, labels)
    562     def _set_axis(self, axis: int, labels: Index) -> None:
    563         labels = ensure_index(labels)
--> 564         self._mgr.set_axis(axis, labels)
    565         self._clear_item_cache()
    566 

~/opt/anaconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py in set_axis(self, axis, new_labels)
    224 
    225         if new_len != old_len:
--> 226             raise ValueError(
    227                 f"Length mismatch: Expected axis has {old_len} elements, new "
    228                 f"values have {new_len} elements"

ValueError: Length mismatch: Expected axis has 1 elements, new values have 30 elements

6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> 4\. stock_em_hsgt_hold_stock

感谢反馈问题，请升级到 AKShare 1.1.10 版本，已修复

**Comment by xnw176** [comment]
可以用了，非常感谢
