### ISSUE TITLE
转债比价的数据如何获得？

### ISSUE THREAD

**Issue by yufeiluo** [jindaxiang/akshare#1693]
url = "http://16.push2.eastmoney.com/api/qt/clist/get"
    params = {
        "pn": "1",
        "pz": "5000",
        "po": "1",
        "np": "1",
        "ut": "bd1d9ddb04089700cf9c27f6f7426281",
        "fltt": "2",
        "invt": "2",
        "fid": "f243",
        "fs": "b:MK0354",
        "fields": "f1,f152,f2,f3,f12,f13,f14,f227,f228,f229,f230,f231,f232,f233,f234,f235,f236,f237,f238,f239,f240,f241,f242,f26,f243",
        "_": "1590386857527",
    }
    r = requests.get(url, params=params)
    text_data = r.text

上面的代码可以获得可转债比价表，我的问题是，你如何得到这个接口呢？

[https://imgur.com/a/M1ToLvN](url)

如何用firefox的 inspect element 探测到这个地址呢？
http://16.push2.eastmoney.com/api/qt/clist/get

**Comment by jindaxiang** [comment]
> ```
> url = "http://16.push2.eastmoney.com/api/qt/clist/get"
> params = {
>     "pn": "1",
>     "pz": "5000",
>     "po": "1",
>     "np": "1",
>     "ut": "bd1d9ddb04089700cf9c27f6f7426281",
>     "fltt": "2",
>     "invt": "2",
>     "fid": "f243",
>     "fs": "b:MK0354",
>     "fields": "f1,f152,f2,f3,f12,f13,f14,f227,f228,f229,f230,f231,f232,f233,f234,f235,f236,f237,f238,f239,f240,f241,f242,f26,f243",
>     "_": "1590386857527",
> }
> r = requests.get(url, params=params)
> text_data = r.text
> ```
> 
> 上面的代码可以获得可转债比价表，我的问题是，你如何得到这个接口呢？
> 
> [https://imgur.com/a/M1ToLvN](url)
> 
> 如何用firefox的 inspect element 探测到这个地址呢？
> http://16.push2.eastmoney.com/api/qt/clist/get

可以看相关接口的源码
