### ISSUE TITLE
Parameter description of migration_area_baidu in the document has an error

### ISSUE THREAD

**Issue by YuanchenZhu2020** [jindaxiang/akshare#182]
**Parameter description of migration_area_baidu in the document has an error**
I found that the parameter *indicator* of the function *migration_area_baidu* has an error in the document. The two values of the parameter are the same, both of which are "move_in".

**Comment by YuanchenZhu2020** [comment]
The same error also appears in *migration_scale_baidu*

**Comment by jindaxiang** [comment]
> The same error also appears in _migration_scale_baidu_

Thanks for issues, i have checked the problem and fix it, please revisit the docs
