### ISSUE TITLE
Parameter *end_date* in *migration_scale_baidu* is not work

### ISSUE THREAD

**Issue by YuanchenZhu2020** [jindaxiang/akshare#183]
**Parameter *end_date* in *migration_scale_baidu* is not work**
I try to run the example code in *migration_scale_baidu* but it returns the data between *start_date* and *Yesterday*, not the value of *end_date*.

Environment: Windows 10, Python 3.7

My code:
```Python
import akshare as ak
migration_scale_baidu_df = ak.migration_scale_baidu(
    area = "浙江省",
    indicator = "move_out",
    start_date = "20190112",
    end_date = "20200201")

print(migration_scale_baidu_df)
```

**Comment by jindaxiang** [comment]
> **Parameter _end_date_ in _migration_scale_baidu_ is not work**
> I try to run the example code in _migration_scale_baidu_ but it returns the data between _start_date_ and _Yesterday_, not the value of _end_date_.
> 
> Environment: Windows 10, Python 3.7
> 
> My code:
> 
> ```python
> import akshare as ak
> migration_scale_baidu_df = ak.migration_scale_baidu(
>     area = "浙江省",
>     indicator = "move_out",
>     start_date = "20190112",
>     end_date = "20200201")
> 
> print(migration_scale_baidu_df)
> ```

Thanks, I have fixed this in akshare 0.4.80, please update it.
