### ISSUE TITLE
pip 安装问题

### ISSUE THREAD

**Issue by lemonche** [jindaxiang/akshare#187]
pip install akshare 

安装过程中出现问题：`cannot import name 'StringIO' from 'pandas.compat' `

akshare 中引用的 pandas 版本过低

**Comment by jindaxiang** [comment]
> pip install akshare
> 
> 安装过程中出现问题：`cannot import name 'StringIO' from 'pandas.compat' `
> 
> akshare 中引用的 pandas 版本过低

请按照 0.25.2 以上版本的 pandas
