### ISSUE TITLE
'Unknown identifier', 'arry'

### ISSUE THREAD

**Issue by morkong** [jindaxiang/akshare#231]
我在调用这个接口时，出现了这个错误，这让我不甚其解
`fund1 = ak.fund_em_info(fund=’000009‘, indicator="单位净值走势")`

**Comment by jindaxiang** [comment]
> 我在调用这个接口时，出现了这个错误，这让我不甚其解
> `fund1 = ak.fund_em_info(fund=’000009‘, indicator="单位净值走势")`

I am so sorry for this mistake, this interface "fund_em_info" now can only get "开放式基金净值"; i will update this interface later. Thanks for your issures.

**Comment by jindaxiang** [comment]
> 我在调用这个接口时，出现了这个错误，这让我不甚其解
> `fund1 = ak.fund_em_info(fund=’000009‘, indicator="单位净值走势")`

I had add "fund_em_money_fund_info" to AkShare, you can use interface to fetch "000009" data, please visit https://www.akshare.xyz/zh_CN/latest/data/fund/fund_public.html#id5 to see docs
