### ISSUE TITLE
epidemic_history return wrong data

### ISSUE THREAD

**Issue by ericqianli** [jindaxiang/akshare#245]
epidemic_history API starts to flip country with country_code:

+-------+------------+---------------------+---------+-----------------------+------+-----------+------+-----------+-----------+-----------+-------+------+
| id    | date       | timestamp           | country | country_code          | area | area_code | city | city_code | confirmed | suspected | cured | dead |
+-------+------------+---------------------+---------+-----------------------+------+-----------+------+-----------+-----------+-----------+-------+------+
| 64811 | 2020-05-04 | 2020-05-04 00:00:00 | VE      | 委内瑞拉              | None |           | None |           |       357 |         0 |   148 |   10 |
| 64812 | 2020-05-04 | 2020-05-04 00:00:00 | VG      | 英属维尔京群岛        | None |           | None |           |         6 |         0 |     3 |    1 |
| 64813 | 2020-05-04 | 2020-05-04 00:00:00 | VI      | 美属维尔京群岛        | None |           | None |           |        66 |         0 |    46 |    4 |
| 64814 | 2020-05-04 | 2020-05-04 00:00:00 | VN      | 越南                  | None |           | None |           |       271 |         0 |   225 |    0 |
| 64815 | 2020-05-04 | 2020-05-04 00:00:00 | YE      | 也门                  | None |           | None |           |        10 |         0 |     1 |    2 |
| 64816 | 2020-05-04 | 2020-05-04 00:00:00 | YT      | 马约特                | None |           | None |           |       650 |         0 |   235 |    6 |
| 64817 | 2020-05-04 | 2020-05-04 00:00:00 | ZA      | 南非                  | None |           | None |           |      6783 |         0 |  2549 |  131 |
| 64818 | 2020-05-04 | 2020-05-04 00:00:00 | ZM      | 赞比亚                | None |           | None |           |       124 |         0 |    78 |    3 |
| 64819 | 2020-05-04 | 2020-05-04 00:00:00 | ZW      | 津巴布韦              | None |           | None |           |        34 |         0 |     5 |    4 |
| 64820 | 2020-05-04 | 2020-05-04 00:00:00 | None    | 纳米比亚              | None |           | None |           |        16 |         0 |     8 |    0 |
+-------+------------+---------------------+---------+-----------------------+------+-----------+------+-----------+-----------+-----------+-------+------+

**Comment by jindaxiang** [comment]
> epidemic_history API starts to flip country with country_code:
> 
> +-------+------------+---------------------+---------+-----------------------+------+-----------+------+-----------+-----------+-----------+-------+------+
> | id | date | timestamp | country | country_code | area | area_code | city | city_code | confirmed | suspected | cured | dead |
> +-------+------------+---------------------+---------+-----------------------+------+-----------+------+-----------+-----------+-----------+-------+------+
> | 64811 | 2020-05-04 | 2020-05-04 00:00:00 | VE | 委内瑞拉 | None | | None | | 357 | 0 | 148 | 10 |
> | 64812 | 2020-05-04 | 2020-05-04 00:00:00 | VG | 英属维尔京群岛 | None | | None | | 6 | 0 | 3 | 1 |
> | 64813 | 2020-05-04 | 2020-05-04 00:00:00 | VI | 美属维尔京群岛 | None | | None | | 66 | 0 | 46 | 4 |
> | 64814 | 2020-05-04 | 2020-05-04 00:00:00 | VN | 越南 | None | | None | | 271 | 0 | 225 | 0 |
> | 64815 | 2020-05-04 | 2020-05-04 00:00:00 | YE | 也门 | None | | None | | 10 | 0 | 1 | 2 |
> | 64816 | 2020-05-04 | 2020-05-04 00:00:00 | YT | 马约特 | None | | None | | 650 | 0 | 235 | 6 |
> | 64817 | 2020-05-04 | 2020-05-04 00:00:00 | ZA | 南非 | None | | None | | 6783 | 0 | 2549 | 131 |
> | 64818 | 2020-05-04 | 2020-05-04 00:00:00 | ZM | 赞比亚 | None | | None | | 124 | 0 | 78 | 3 |
> | 64819 | 2020-05-04 | 2020-05-04 00:00:00 | ZW | 津巴布韦 | None | | None | | 34 | 0 | 5 | 4 |
> | 64820 | 2020-05-04 | 2020-05-04 00:00:00 | None | 纳米比亚 | None | | None | | 16 | 0 | 8 | 0 |
> +-------+------------+---------------------+---------+-----------------------+------+-----------+------+-----------+-----------+-----------+-------+------+

1. You shoud update akshare to latest version;
2. The origin data source have a mistake;
3. Now the best solution to this issues is to fix it by yourself via pandas
