### ISSUE TITLE
akshare.futures.requests_fun 模块的错误捕捉bug

### ISSUE THREAD

**Issue by changvin** [jindaxiang/akshare#250]
akshare-0.5.3 

akshare.futures.requests_fun  的 错误捕捉类型为 TimeoutError，其实并不起作用，应该为requests.exceptions.Timeout , 而且 10秒的Timeout时间会比较少，在爬取DCE交易所经常会读超时（高峰时段，一般会大于10秒后返回，所以会一直读超时），希望可以加长超时时间，或者有其他方案

**Comment by jindaxiang** [comment]
> akshare-0.5.3
> 
> akshare.futures.requests_fun 的 错误捕捉类型为 TimeoutError，其实并不起作用，应该为requests.exceptions.Timeout , 而且 10秒的Timeout时间会比较少，在爬取DCE交易所经常会读超时（高峰时段，一般会大于10秒后返回，所以会一直读超时），希望可以加长超时时间，或者有其他方案
感谢提示，已经修改相关的代码
