### ISSUE TITLE
The column name of the output parameter is wrong

### ISSUE THREAD

**Issue by morkong** [jindaxiang/akshare#255]
The column name of the output parameter in 
[https://www.akshare.xyz/zh_CN/latest/data/fund/fund_public.html#id9](https://www.akshare.xyz/zh_CN/latest/data/fund/fund_public.html#id9)  is wrong, it should be“ 净值日期   单位净值   累计净值    日增长率    申购状态   赎回状态”  ,It should n’t be “净值日期   每万份收益 7日年化收益率  申购状态  赎回状态”.

**Comment by jindaxiang** [comment]
> The column name of the output parameter in
> https://www.akshare.xyz/zh_CN/latest/data/fund/fund_public.html#id9 is wrong, it should be“ 净值日期 单位净值 累计净值 日增长率 申购状态 赎回状态” ,It should n’t be “净值日期 每万份收益 7日年化收益率 申购状态 赎回状态”.

Thanks for your issues, 已经修复，请升级到 akshare 0.5.5
