### ISSUE TITLE
Get the time of the Last trading day

### ISSUE THREAD

**Issue by morkong** [jindaxiang/akshare#265]
It is recommended to add an interface,Get the time of the Last trading day,When obtaining real-time market data, you can more intuitively understand which day is the data

**Comment by jindaxiang** [comment]
> It is recommended to add an interface,Get the time of the Last trading day,When obtaining real-time market data, you can more intuitively understand which day is the data

ok, which interface?

**Comment by morkong** [comment]
fund_em_open_fund_daily，Is that OK?

**Comment by jindaxiang** [comment]
> fund_em_open_fund_daily，Is that OK?

Yes, It have been fix in akshare 0.5.12, please update it.
