### ISSUE TITLE
fund_em_graded_fund_info  Add "accumulated net value"

### ISSUE THREAD

**Issue by morkong** [jindaxiang/akshare#267]
Most of the data of classified funds have "accumulated net value". In the “ fund_em_graded_fund_info” interface, I think there should also be this part of data.

**Comment by jindaxiang** [comment]
> Most of the data of classified funds have "accumulated net value". In the “ fund_em_graded_fund_info” interface, I think there should also be this part of data.

Thanks for your issues, I have fixed the error, Please upgrade akshare to 0.5.11
