### ISSUE TITLE
获取全球指数时，交易量字符转换出问题

### ISSUE THREAD

**Issue by leesGb** [jindaxiang/akshare#354]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Traceback (most recent call last):
  File "h:/project/stock/new/test.py", line 9, in <module>
    mm = ak.index_investing_global(country="台湾", index_name="台湾加权指数", period="每日", start_date="2000-01-01", end_date="2020-06-19")#ak.index_investing_global_country_name_url("日本")#
  File "C:\Users\lees\AppData\Roaming\Python\Python37\site-packages\akshare\index\index_investing.py", line 383, in index_investing_global
    .astype(float)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5698, in astype
    new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 582, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 442, in apply
    applied = getattr(b, f)(**kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 625, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 897, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: '1,975.92'

**Comment by jindaxiang** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.
> 
> Traceback (most recent call last):
> File "h:/project/stock/new/test.py", line 9, in
> mm = ak.index_investing_global(country="台湾", index_name="台湾加权指数", period="每日", start_date="2000-01-01", end_date="2020-06-19")#ak.index_investing_global_country_name_url("日本")#
> File "C:\Users\lees\AppData\Roaming\Python\Python37\site-packages\akshare\index\index_investing.py", line 383, in index_investing_global
> .astype(float)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5698, in astype
> new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 582, in astype
> return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 442, in apply
> applied = getattr(b, f)(**kwargs)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 625, in astype
> values = astype_nansafe(vals1d, dtype, copy=True)
> File "D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\cast.py", line 897, in astype_nansafe
> return arr.astype(dtype, copy=True)
> ValueError: could not convert string to float: '1,975.92'

Thanks for your issues, i have checked the error and fixed it in akshare version 0.5.47, please update to latest version of akshare.
