### ISSUE TITLE
宏观的结果中index日期，有的是str，有的是datetime

### ISSUE THREAD

**Issue by leeleilei** [jindaxiang/akshare#370]
返回值的index 类型不统一，需要优化成datetime
返回值有些是string，有些是float和int，也不完全统一
字段column名称有些错乱

例如今天发现的
df1 = ak.macro_china_market_margin_sz()
df2 = ak.macro_china_market_margin_sh()

------
我尝试提交一个pull request，但估计是一个批量问题，之前也遇到过一次没有记录。
辛苦了。

**Comment by jindaxiang** [comment]
会陆续处理这个问题

**Comment by jindaxiang** [comment]
> 返回值的index 类型不统一，需要优化成datetime
> 返回值有些是string，有些是float和int，也不完全统一
> 字段column名称有些错乱
> 
> 例如今天发现的
> df1 = ak.macro_china_market_margin_sz()
> df2 = ak.macro_china_market_margin_sh()
> 
> 我尝试提交一个pull request，但估计是一个批量问题，之前也遇到过一次没有记录。
> 辛苦了。

akshare 0.5.57 have resolved this issue
