### ISSUE TITLE
建议增加股票的财务数据，如PETTM等

### ISSUE THREAD

**Issue by wanghan0501** [jindaxiang/akshare#392]
建议增加股票的财务数据，如PETTM等，想自己计算又发现ak.stock_zh_a_daily返回的是流通股本，不是总股本

**Comment by jindaxiang** [comment]
> 建议增加股票的财务数据，如PETTM等，想自己计算又发现ak.stock_zh_a_daily返回的是流通股本，不是总股本

目前正在增加该部分数据
