### ISSUE TITLE
epidemic_163 not returning data in expected format

### ISSUE THREAD

**Issue by ericqianli** [jindaxiang/akshare#4]
According to the documentation, calling history indicator on epidemic_163 should return data grouped by **area**. But in fact it is not.

**Query**
`import akshare as ak`
`epidemic_163_df = ak.epidemic_163(indicator="实时")`
`print(epidemic_163_df)`

**Expected Result**
      day   time country  area  dead  confirm  suspect  heal  city district
0    1.12             中国  湖北武汉     1       41        0   NaN  None     None
1    1.13             中国  湖北武汉     1       41        0   NaN  None     None
2    1.14             中国  湖北武汉     1       41        0   NaN  None     None
3    1.15             中国  湖北武汉     2       41        0   NaN  None     None
4    1.16             中国  湖北武汉     2       45        0   NaN  None     None
..    ...    ...     ...   ...   ...      ...      ...   ...   ...      ...
220  1.26  09:00      中国    台湾     0        3        0   0.0               
221  1.26  09:00      中国    新疆     0        4        0   0.0               
222  1.26  09:00      中国    澳门     0        5        0   0.0               
223  1.26  09:00      中国   内蒙古     0        7        0   0.0               
224  1.26  09:00      中国    青海     0        4        0   0.0 

**Actual Result**
     date confirm suspect dead heal
0   01.21     440      37    9   25
1   01.13      41       0    1    0
2   01.14      41       0    1    0
3   01.15      41       0    2    5
4   01.16      45       0    2    8
..    ...     ...     ...  ...  ...
11  01.20     291      54    6   25
12  01.25    1429    1965   42   38
13  01.26    2081    2684   56   49
14  01.27    2858    5794   82   58
15  01.28    4599    6973  106   68

**Comment by jindaxiang** [comment]
Hello, i have checked the error, version 0.3.70 had fixed this problem.
you can `pip install akshare --upgrade` to 0.3.70

**Comment by ericqianli** [comment]
I upgraded to version 0.3.70 but the problem still exists. Can you take a look?

**Comment by jindaxiang** [comment]
i find your python version is 3.8.0, python3.8 have not been test

**Comment by jindaxiang** [comment]
```
    epidemic_hist_163_df = epidemic_163(indicator="历史")
    print(epidemic_hist_163_df)
```

>       day   time country  area  dead  confirm  suspect  heal  city district
0    1.12             中国  湖北武汉     1       41        0   NaN  None     None
1    1.13             中国  湖北武汉     1       41        0   NaN  None     None
2    1.14             中国  湖北武汉     1       41        0   NaN  None     None
3    1.15             中国  湖北武汉     2       41        0   NaN  None     None
4    1.16             中国  湖北武汉     2       45        0   NaN  None     None
..    ...    ...     ...   ...   ...      ...      ...   ...   ...      ...
220  1.26  09:00      中国    台湾     0        3        0   0.0               
221  1.26  09:00      中国    新疆     0        4        0   0.0               
222  1.26  09:00      中国    澳门     0        5        0   0.0               
223  1.26  09:00      中国   内蒙古     0        7        0   0.0               
224  1.26  09:00      中国    青海     0        4        0   0.0               

[225 rows x 10 columns]

**Comment by ericqianli** [comment]
Thanks for checking out. What's the latest stable Python version supported?

**Comment by jindaxiang** [comment]
Now, Python 3. 7. 5 version is the best




| |
Daxiang Jin
Institute of Finance and Data Science
|
|
Southwest Jiaotong University
18328746465
jindaxiang@163.com
Jiuli Campus, SWJTU
610031
|

Signature is customized by Netease Mail Master

On 02/03/2020 06:37, ericqianli wrote:

Thanks for checking out. What's the latest stable Python version supported?

**Comment by jindaxiang** [comment]
Now, Python 3. 7. 5 version is the best
