### ISSUE TITLE
US Equity data fetch error

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#40]
**Describe the bug**
Cannot fetch US equity data using stock_us_daily_df = ak.stock_us_daily(symbol="AMZN")

**To Reproduce**
stock_us_daily_df = ak.stock_us_daily(symbol="AMZN")

**Screenshots**
![image](https://user-images.githubusercontent.com/359830/76216861-b88fe880-61e7-11ea-9a1d-bd79066e2230.png)

**Comment by jindaxiang** [comment]
Hello
1. first update your akshare to latest version
2. i test the latest akshare, then it can fetch the data as follows
![image](https://user-images.githubusercontent.com/18234520/76219878-7e5b3100-6251-11ea-95ad-3dd08ed3535d.png)

**Comment by edwardsun** [comment]
The issue is indeed NOT reproducible in the current version. Closing the ticket. Many thanks!
