### ISSUE TITLE
Linux 上运行报错

### ISSUE THREAD

**Issue by wangjunbao2018** [jindaxiang/akshare#441]
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

**Comment by jindaxiang** [comment]
10. Linux 系统显示 `execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.`

    1. 需要安装 `nodejs`
    2. 参考[文章](https://blog.csdn.net/qq_36853469/article/details/106401389)
