### ISSUE TITLE
Contos 上运行报错

### ISSUE THREAD

**Issue by wangjunbao2018** [jindaxiang/akshare#450]
**Describe the bug**
Contos 上 import akashare as ak 运行报错

```
import akshare as ak
  File "/usr/local/lib/python3.6/site-packages/akshare/__init__.py", line 1059, in <module>
    from akshare.stock_feature.stock_a_pb import stock_a_pb
  File "/usr/local/lib/python3.6/site-packages/akshare/stock_feature/stock_a_pb.py", line 317, in <module>

```
**Screenshots**
![image](https://user-images.githubusercontent.com/42427383/88523365-692d4600-d02a-11ea-8a81-6042a990232a.png)

**Desktop (please complete the following information):**
 - OS: Linux version 4.18.0-147.8.1.el8_1.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.3.1 20190507 (Red Hat 8.3.1-4) (GCC)) #1 SMP Thu Apr 9 13:49:54 UTC 2020

**Comment by jindaxiang** [comment]
https://www.akshare.xyz/zh_CN/latest/answer.html
