### ISSUE TITLE
stock_em_account返回数据出错

### ISSUE THREAD

**Issue by dehewujiang** [jindaxiang/akshare#454]
![image](https://user-images.githubusercontent.com/11341369/88773392-9efe3600-d1b4-11ea-997b-91d067adacb8.png)
【数据日期】和【期末投资者(万户)-A股账户】数据似乎出错了

**Comment by jindaxiang** [comment]
升级到最新的 AkShare 后报错？

**Comment by jindaxiang** [comment]
> ![image](https://user-images.githubusercontent.com/11341369/88773392-9efe3600-d1b4-11ea-997b-91d067adacb8.png)
> 【数据日期】和【期末投资者(万户)-A股账户】数据似乎出错了

返回数据没问题，更新了接口的返回数据格式，请查看文档
