### ISSUE TITLE
我是否可指定代理IP抽取？

### ISSUE THREAD

**Issue by zhoufann9188** [jindaxiang/akshare#467]
非常感谢你的软件，我最近用了一段时间觉得非常好用

美中不足的是，请问我是否可以像request那样，在调用的时候指定代理IP地址和端口？

因为这样我就不需要单独弄一台机器跑数据了（目前需要单独一个机器，不断的变化自己的IP，但是会影响机器上的其它程序）

期待作者的回复，谢谢

**Comment by jindaxiang** [comment]
暂时可以通过以下代码来修改 代理IP 示例如下：
import socks  # pip install PySocks
import socket
import akshare as ak
socks.set_default_proxy(socks.HTTP, "127.0.0.1", 10809)
socket.socket = socks.socksocket

ak.covid_19_csse_daily()
