### ISSUE TITLE
中金所得日线数据格式发生更改

### ISSUE THREAD

**Issue by changvin** [jindaxiang/akshare#468]
中金所得日线数据格式发生更改， futures.get_cffex_daily 在获取数据后的字段对应不上，造成数据错误。
原因是数据的field 与返回的数据row index 强依赖造成的。建议利用返回数据的列名做映射。

**Comment by jindaxiang** [comment]
感谢反馈bug，请升级到 AkShare 0.5.92 版本，已经修复问题。
