### ISSUE TITLE
指数历史数据开始时间晚于指数真实数据

### ISSUE THREAD

**Issue by leeleilei** [jindaxiang/akshare#473]
获取到的指数历史数据开始时间晚于指数上架时间，比如

![image](https://user-images.githubusercontent.com/538984/89484284-c23a6e00-d7d0-11ea-97bc-89beb762e552.png)

第一条数据是2013年，实际养老指数在2005年已经存在。

数据不完整的话分析意义就下降很多，想知道这个是数据源的问题吗？有没有其他建议的方案来规避这个问题？

**Comment by leeleilei** [comment]
我又看了下是新浪数据问题，开始时间太晚。
东方财富等数据源较为完整，后续有计划切换或者备用吗？

**Comment by jindaxiang** [comment]
> 获取到的指数历史数据开始时间晚于指数上架时间，比如
> 
> ![image](https://user-images.githubusercontent.com/538984/89484284-c23a6e00-d7d0-11ea-97bc-89beb762e552.png)
> 
> 第一条数据是2013年，实际养老指数在2005年已经存在。
> 
> 数据不完整的话分析意义就下降很多，想知道这个是数据源的问题吗？有没有其他建议的方案来规避这个问题？

哪个接口

**Comment by jindaxiang** [comment]
> 获取到的指数历史数据开始时间晚于指数上架时间，比如
> 
> ![image](https://user-images.githubusercontent.com/538984/89484284-c23a6e00-d7d0-11ea-97bc-89beb762e552.png)
> 
> 第一条数据是2013年，实际养老指数在2005年已经存在。
> 
> 数据不完整的话分析意义就下降很多，想知道这个是数据源的问题吗？有没有其他建议的方案来规避这个问题？

这个目前是数据源的问题：
![image](https://user-images.githubusercontent.com/18234520/89505961-f1ff6b00-d7fc-11ea-87ae-e171d10382a8.png)

**Comment by jindaxiang** [comment]
> 我又看了下是新浪数据问题，开始时间太晚。
> 东方财富等数据源较为完整，后续有计划切换或者备用吗？

升级到 AkShare 0.5.94 版本，使用 stock_zh_index_daily_em 接口获取
