### ISSUE TITLE
希望能增加：可转债转股价变动接口

### ISSUE THREAD

**Issue by zhouzyc** [jindaxiang/akshare#474]
1.首先非常感谢akshare的开源。非常牛逼强大的一个开源库
2.希望能够有一个接口获取可转债转股价变动记录接口

**Comment by jindaxiang** [comment]
> 1.首先非常感谢akshare的开源。非常牛逼强大的一个开源库
> 2.希望能够有一个接口获取可转债转股价变动记录接口

感谢支持，有合适的数据源网站嘛？

**Comment by zhouzyc** [comment]
你好：https://app.jisilu.cn/data/cbnew/#cb 有相应数据
![image](https://user-images.githubusercontent.com/18420689/89505915-e6ac3f80-d7fc-11ea-845a-17490f95c63f.png)

**Comment by jindaxiang** [comment]
升级到 AkShare 0.5.94 版本，使用 bond_cov_jsl接口获取

**Comment by zhouzyc** [comment]
非常感谢。akshare👍
