### ISSUE TITLE
index_stock_cons函数返回结果带有重复记录

### ISSUE THREAD

**Issue by wuzhe1234** [jindaxiang/akshare#499]
In[4]: ak.index_stock_cons('000300').drop_duplicates()
Out[4]: 
       品种代码  品种名称        纳入日期
0    601077  渝农商行  2020-06-15
1    603369   今世缘  2020-06-15
2    000977  浪潮信息  2020-06-15
3    603658  安图生物  2020-06-15
4    601816  京沪高铁  2020-06-15
..      ...   ...         ...
295  000157  中联重科  2005-04-08
296  000069  华侨城A  2005-04-08
297  000063  中兴通讯  2005-04-08
298  000001  深发展A  2005-04-08
299  000002   万科A  2005-04-08
[281 rows x 3 columns]

可以看到去掉重复记录后只有沪深300只有281条记录了, 运行环境: python3.8, pandas1.1, akshare0.6.6, requests2.24, beautifulsoup4 4.9.1, ak.index_stock_hist可能也有同样问题

**Comment by jindaxiang** [comment]
> In[4]: ak.index_stock_cons('000300').drop_duplicates()
> Out[4]:
> 品种代码 品种名称 纳入日期
> 0 601077 渝农商行 2020-06-15
> 1 603369 今世缘 2020-06-15
> 2 000977 浪潮信息 2020-06-15
> 3 603658 安图生物 2020-06-15
> 4 601816 京沪高铁 2020-06-15
> .. ... ... ...
> 295 000157 中联重科 2005-04-08
> 296 000069 华侨城A 2005-04-08
> 297 000063 中兴通讯 2005-04-08
> 298 000001 深发展A 2005-04-08
> 299 000002 万科A 2005-04-08
> [281 rows x 3 columns]
> 
> 可以看到去掉重复记录后只有沪深300只有281条记录了, 运行环境: python3.8, pandas1.1, akshare0.6.6, requests2.24, beautifulsoup4 4.9.1, ak.index_stock_hist可能也有同样问题

已检查，应该是新浪源数据的问题，升级到 akshare 0.6.7 新增 index_stock_cons_sina 接口获取主流指数成份
