### ISSUE TITLE
Add history PE, PB data of us stocks. 添加美股个股历史PE、PB数据.

### ISSUE THREAD

**Issue by tyePhDCandy** [jindaxiang/akshare#509]
**Is your feature request related to a problem? Please describe.**
No. Please add history PE, PB data of us stocks, if possible. 添加美股个股历史PE、PB数据.

**Describe the solution you'd like**
None.

**Describe alternatives you've considered**
None.

**Additional context**
Please add history PE, PB data of us stocks, if possible. 添加美股个股历史PE、PB数据.

**Comment by jindaxiang** [comment]
有无合适的数据源？
