### ISSUE TITLE
美股历史数据, 前复权后数据为NaN

### ISSUE THREAD

**Issue by broven** [jindaxiang/akshare#519]
akshare 0.6.15
```python
stock_us_daily_df = ak.stock_us_daily(symbol="BABA", adjust="qfq")
stock_hk_daily_df
open | high | low | close | volume
-- | -- | -- | -- | --

NaN | NaN | NaN | NaN | 74549578.0
NaN | NaN | NaN | NaN | 53617241.0
NaN | NaN | NaN | NaN | 41816834.0
NaN | NaN | NaN | NaN | 36509531.0
NaN | NaN | NaN | NaN | 26592325.0
... | ... | ... | ... | ...
NaN | NaN | NaN | NaN | 22881516.0
NaN | NaN | NaN | NaN | 32079272.0
NaN | NaN | NaN | NaN | 43488850.0
NaN | NaN | NaN | NaN | 30708120.0
NaN | NaN | NaN | NaN | 3194933

```

**Comment by jindaxiang** [comment]
> akshare 0.6.15
> 
> ```python
> stock_us_daily_df = ak.stock_us_daily(symbol="BABA", adjust="qfq")
> stock_hk_daily_df
> open | high | low | close | volume
> -- | -- | -- | -- | --
> 
> NaN | NaN | NaN | NaN | 74549578.0
> NaN | NaN | NaN | NaN | 53617241.0
> NaN | NaN | NaN | NaN | 41816834.0
> NaN | NaN | NaN | NaN | 36509531.0
> NaN | NaN | NaN | NaN | 26592325.0
> ... | ... | ... | ... | ...
> NaN | NaN | NaN | NaN | 22881516.0
> NaN | NaN | NaN | NaN | 32079272.0
> NaN | NaN | NaN | NaN | 43488850.0
> NaN | NaN | NaN | NaN | 30708120.0
> NaN | NaN | NaN | NaN | 3194933
> ```

感谢反馈问题，请升级到 akshare 0.6.16 已经修复本错误
