### ISSUE TITLE
沪深300数据有重复值

### ISSUE THREAD

**Issue by congcong009** [jindaxiang/akshare#529]
使用index_stock_cons(index="000300")进行数据读取，获得返回的结果中，有38个重复个股，导致去重后的沪深300指数样本股不完整，重复数据如下图所示：

![image](https://user-images.githubusercontent.com/2680017/91793892-1c9de180-ec4c-11ea-9985-b11faadc40f2.png)

**Comment by jindaxiang** [comment]
> 使用index_stock_cons(index="000300")进行数据读取，获得返回的结果中，有38个重复个股，导致去重后的沪深300指数样本股不完整，重复数据如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/2680017/91793892-1c9de180-ec4c-11ea-9985-b11faadc40f2.png)

是的，是数据源的问题，再没找到其他替代数据源的情况下，没办法处理

**Comment by congcong009** [comment]
又查了下其他数据源，基本上都多多少少有重复的值。
