### ISSUE TITLE
get_futures_daily取czce数据，当日还没生成时报错

### ISSUE THREAD

**Issue by smartgang** [jindaxiang/akshare#530]
在2020年9月2日下午4点前用下面函数取数
czce_daily_bar = ak.get_futures_daily(start_date="20200601", end_date="20200902", market="CZCE", index_bar=False)
会报如下错误：
    if html[1][0] not in ["品种月份", "品种代码"]:
IndexError: list index out of range

其他几个交易所不会报这个错。

**Comment by jindaxiang** [comment]
请在4点后使用
