### ISSUE TITLE
调用 currency_hist 获取 越南盾等行情时，出现异常

### ISSUE THREAD

**Issue by kcrazy** [jindaxiang/akshare#534]
`ak.currency_hist(symbol="usd-vnd", start_date="19020101", end_date="20200829")`
出现：
ValueError: could not convert string to float: '21,220.0'

**Comment by jindaxiang** [comment]
> `ak.currency_hist(symbol="usd-vnd", start_date="19020101", end_date="20200829")`
> 出现：
> ValueError: could not convert string to float: '21,220.0'

感谢反馈问题，请升级到 AkShare 0.6.23  版本，已修复

**Comment by kcrazy** [comment]
usd-iqd 伊拉克第纳尔 还是有这个问题

**Comment by kcrazy** [comment]
usd-mmk 缅元也是
