### ISSUE TITLE
crontab 时报错Could not find an available JavaScript runtime

### ISSUE THREAD

**Issue by shenghuoli** [jindaxiang/akshare#546]
操作系统Centos8 64位,root用户
下载了Nodejs，并且将node和npm使用软链接到/usb/bin目录下
如果在命令行下执行python a.py没有问题，
但使用crontab做定时任务时提示错误为：
Traceback (most recent call last):
  File "/data/stock/jobs/minute_job.py", line 2, in <module>
    import akshare as ak
  File "/root/anaconda3/lib/python3.8/site-packages/akshare/__init__.py", line 1108, in <module>
    from akshare.stock_feature.stock_a_pb import stock_a_pb
  File "/root/anaconda3/lib/python3.8/site-packages/akshare/stock_feature/stock_a_pb.py", line 317, in <module>
    js_functions = execjs.compile(hash_code)
  File "/root/anaconda3/lib/python3.8/site-packages/execjs/__init__.py", line 61, in compile
    return get().compile(source, cwd)
  File "/root/anaconda3/lib/python3.8/site-packages/execjs/_runtimes.py", line 21, in get
    return get_from_environment() or _find_available_runtime()
  File "/root/anaconda3/lib/python3.8/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
    raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

**Comment by jindaxiang** [comment]
> 操作系统Centos8 64位,root用户
> 下载了Nodejs，并且将node和npm使用软链接到/usb/bin目录下
> 如果在命令行下执行python a.py没有问题，
> 但使用crontab做定时任务时提示错误为：
> Traceback (most recent call last):
> File "/data/stock/jobs/minute_job.py", line 2, in
> import akshare as ak
> File "/root/anaconda3/lib/python3.8/site-packages/akshare/**init**.py", line 1108, in
> from akshare.stock_feature.stock_a_pb import stock_a_pb
> File "/root/anaconda3/lib/python3.8/site-packages/akshare/stock_feature/stock_a_pb.py", line 317, in
> js_functions = execjs.compile(hash_code)
> File "/root/anaconda3/lib/python3.8/site-packages/execjs/**init**.py", line 61, in compile
> return get().compile(source, cwd)
> File "/root/anaconda3/lib/python3.8/site-packages/execjs/_runtimes.py", line 21, in get
> return get_from_environment() or _find_available_runtime()
> File "/root/anaconda3/lib/python3.8/site-packages/execjs/_runtimes.py", line 49, in _find_available_runtime
> raise exceptions.RuntimeUnavailableError("Could not find an available JavaScript runtime.")
> execjs._exceptions.RuntimeUnavailableError: Could not find an available JavaScript runtime.

目前还没有遇到这个问题，请自行百度下
