### ISSUE TITLE
文档勘误

### ISSUE THREAD

**Issue by congcong009** [jindaxiang/akshare#550]
在宏观经济数据类目下：
https://www.akshare.xyz/zh_CN/latest/data/macro/macro.html#id1

CPI和PPI的输出参数，目前为

名称 | 类型 | 默认显示 | 描述
-- | -- | -- | --
**日期** | str | Y | 日期-索引
**年率** | float | Y | 年率

应该为
名称 | 类型 | 默认显示 | 描述
-- | -- | -- | --
**index** | str | Y | 日期-索引
**cpi/ppi** | float | Y | 年率

**Comment by congcong009** [comment]
发现本页的输出参数基本上都有错误，当前文档为中文字段，而输出都是英文，时间为index，数据项略有区别

**Comment by jindaxiang** [comment]
感谢反馈问题，请升级到 AkShare 0.6.32 已修复
