### ISSUE TITLE
stock_em_hsgt_institution_statistics not return results

### ISSUE THREAD

**Issue by LaCatFly** [jindaxiang/akshare#552]
Hello,

Tried to use this function above, it appears not coming back with any info. Could you please take a look? I am using the latests version of Akshare and just run this line below:

em_df=ak.stock_em_hsgt_institution_statistics(market="北向持股", start_date="20200813", end_date="20200814")

**Comment by jindaxiang** [comment]
> stock_em_hsgt_institution_statistics

Sorry for to tell you that, this interface can only get recently 30 days data
