### ISSUE TITLE
源码阅读问题请教

### ISSUE THREAD

**Issue by anbency** [jindaxiang/akshare#556]
本人正在阅读akshare的源码，想请教下这个接口：
def stock_zh_a_daily(symbol: str = "sz000613", adjust: str = "") -> pd.DataFrame

    res = requests.get(**zh_sina_a_stock_hist_url**.format(symbol))
    js_code = execjs.compile(**hk_js_decode**)

这个zh_sina_a_stock_hist_url和hk_js_decode两部分是如何从网页上找到的？我用浏览器查看个股页面源码没有找到这些链接http://finance.sina.com.cn/realstock/company/sh603881/nc.shtml

**Comment by jindaxiang** [comment]
> 本人正在阅读akshare的源码，想请教下这个接口：
> def stock_zh_a_daily(symbol: str = "sz000613", adjust: str = "") -> pd.DataFrame
> 
> ```
> res = requests.get(**zh_sina_a_stock_hist_url**.format(symbol))
> js_code = execjs.compile(**hk_js_decode**)
> ```
> 
> 这个zh_sina_a_stock_hist_url和hk_js_decode两部分是如何从网页上找到的？我用浏览器查看个股页面源码没有找到这些链接http://finance.sina.com.cn/realstock/company/sh603881/nc.shtml

ajax 和 js 里面

**Comment by anbency** [comment]
研究了两天，没看出来这是怎么抓取的。想请问下这部分是怎么分析的，需要哪些知识点？
