### ISSUE TITLE
0.6.33版本 调用 currency_hist 获取 伊拉克，缅甸等行情时，出现异常

### ISSUE THREAD

**Issue by kcrazy** [jindaxiang/akshare#558]
#555
但是我已经是 0.6.33 版本，伊拉克第纳尔还是不行

```
File ".../akshare/fx/currency_investing.py", line 73, in currency_hist
df_data["涨跌幅"] = pd.DataFrame(round(df_data['涨跌幅'].str.replace('%', '').astype(float) / 100, 6))

ValueError: could not convert string to float: '530,545.16'
```

我仔细看了一下，原因是 2004-01-05 会取到 530,545.16% 这样的数字
因为我的所有货币的调用，起始日期都是从 1902-01-01 开始的，所以有些货币会有这种情况出现

**Comment by jindaxiang** [comment]
> #555
> 但是我已经是 0.6.33 版本，伊拉克第纳尔还是不行
> 
> ```
> File ".../akshare/fx/currency_investing.py", line 73, in currency_hist
> df_data["涨跌幅"] = pd.DataFrame(round(df_data['涨跌幅'].str.replace('%', '').astype(float) / 100, 6))
> 
> ValueError: could not convert string to float: '530,545.16'
> ```
> 
> 我仔细看了一下，原因是 2004-01-05 会取到 530,545.16% 这样的数字
> 因为我的所有货币的调用，起始日期都是从 1902-01-01 开始的，所以有些货币会有这种情况出现

感谢反馈问题，已修复该问题，请升级到 AkShare 0.6.34 版本
