### ISSUE TITLE
KeyError and bad zip data from historical daily data

### ISSUE THREAD

**Issue by daisypupu** [jindaxiang/akshare#567]
```
import akshare as ak
get_futures_daily_df = ak.get_futures_daily(start_date="20030109", end_date="20030114", market="DCE", index_bar=False)
```
returns `KeyError`:
```
KeyError                                  Traceback (most recent call last)
<ipython-input-18-9e6cf2daa44e> in <module>
      6 #for exch in exchanges:
      7 #    for
----> 8 get_futures_daily_df = ak.get_futures_daily(start_date="20030109", end_date="20030114", market="DCE", index_bar=False)
      9 #print(get_futures_daily_df[get_futures_daily_df['symbol'] == "A1007"])
     10 print('daisy', get_futures_daily_df)

~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
    439     df_list = list()
    440     while start_date <= end_date:
--> 441         df = f(date=str(start_date).replace("-", ""))
    442         if df is not None:
    443             df_list.append(df)

~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_dce_daily(date)
    379     data_df = data_df[~data_df["商品名称"].str.contains("小计")]
    380     data_df = data_df[~data_df["商品名称"].str.contains("总计")]
--> 381     data_df["variety"] = data_df["商品名称"].map(lambda x: cons.DCE_MAP[x])
    382     data_df["symbol"] = data_df["variety"] + data_df["交割月份"].astype(int).astype(str)
    383     del data_df["商品名称"]

c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\series.py in map(self, arg, na_action)
   3968         dtype: object
   3969         """
-> 3970         new_values = super()._map_values(arg, na_action=na_action)
   3971         return self._constructor(new_values, index=self.index).__finalize__(
   3972             self, method="map"

c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\base.py in _map_values(self, mapper, na_action)
   1158 
   1159         # mapper is a function
-> 1160         new_values = map_f(values, mapper)
   1161 
   1162         return new_values

pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()

~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in <lambda>(x)
    379     data_df = data_df[~data_df["商品名称"].str.contains("小计")]
    380     data_df = data_df[~data_df["商品名称"].str.contains("总计")]
--> 381     data_df["variety"] = data_df["商品名称"].map(lambda x: cons.DCE_MAP[x])
    382     data_df["symbol"] = data_df["variety"] + data_df["交割月份"].astype(int).astype(str)
    383     del data_df["商品名称"]

KeyError: '大豆'```
```

This should return Empty if there's no data, None is it's not a trading date.

And bad zip file from
```get_futures_daily_df = ak.get_futures_daily(start_date="20081101", end_date="20081107", market="CFFEX", index_bar=False)
---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
<ipython-input-29-6845f4f04823> in <module>
      6 #for exch in exchanges:
      7 #    for
----> 8 get_futures_daily_df = ak.get_futures_daily(start_date="20081101", end_date="20081107", market="CFFEX", index_bar=False)
      9 #print(get_futures_daily_df[get_futures_daily_df['symbol'] == "A1007"])
     10 print('daisy', get_futures_daily_df)

~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
    439     df_list = list()
    440     while start_date <= end_date:
--> 441         df = f(date=str(start_date).replace("-", ""))
    442         if df is not None:
    443             df_list.append(df)

~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_cffex_daily(date)
     49     r = requests.get(url)
     50 
---> 51     with zipfile.ZipFile(BytesIO(r.content)) as file:
     52         with file.open(f"{date}_1.csv") as my_file:
     53             data = my_file.read().decode("gb2312")

c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel)
   1220         try:
   1221             if mode == 'r':
-> 1222                 self._RealGetContents()
   1223             elif mode in ('w', 'x'):
   1224                 # set the modified flag so central directory gets written

c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\zipfile.py in _RealGetContents(self)
   1287             raise BadZipFile("File is not a zip file")
   1288         if not endrec:
-> 1289             raise BadZipFile("File is not a zip file")
   1290         if self.debug > 1:
   1291             print(endrec)

BadZipFile: File is not a zip file
```

```
get_futures_daily_df = ak.get_futures_daily(start_date='20200918', end_date='20200918', market='DCE', index_bar=False)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-42-872a1fba4a04> in <module>
----> 1 get_futures_daily_df = ak.get_futures_daily(start_date='20200918', end_date='20200918', market='CFFEX', index_bar=False)

~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
    439     df_list = list()
    440     while start_date <= end_date:
--> 441         df = f(date=str(start_date).replace("-", ""))
    442         if df is not None:
    443             df_list.append(df)

~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_cffex_daily(date)
     61     variety_list = [re.compile(r"[a-zA-Z_]+").findall(item)[0] for item in symbol_list]
     62     data_df.columns = ["symbol", "open", "high", "low", "volume", "turnover",
---> 63                        "open_interest", "_", "close", "settle", "pre_settle", "_", "_", "_", "_"]
     64     data_df["date"] = date
     65     data_df["variety"] = variety_list

c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\generic.py in __setattr__(self, name, value)
   5147         try:
   5148             object.__getattribute__(self, name)
-> 5149             return object.__setattr__(self, name, value)
   5150         except AttributeError:
   5151             pass

pandas\_libs\properties.pyx in pandas._libs.properties.AxisProperty.__set__()

c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\generic.py in _set_axis(self, axis, labels)
    562     def _set_axis(self, axis: int, labels: Index) -> None:
    563         labels = ensure_index(labels)
--> 564         self._mgr.set_axis(axis, labels)
    565         self._clear_item_cache()
    566 

c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\internals\managers.py in set_axis(self, axis, new_labels)
    225         if new_len != old_len:
    226             raise ValueError(
--> 227                 f"Length mismatch: Expected axis has {old_len} elements, new "
    228                 f"values have {new_len} elements"
    229             )

ValueError: Length mismatch: Expected axis has 14 elements, new values have 15 elements
```

**Comment by jindaxiang** [comment]
Thanks for your issues

> ```
> import akshare as ak
> get_futures_daily_df = ak.get_futures_daily(start_date="20030109", end_date="20030114", market="DCE", index_bar=False)
> ```
> 
> returns `KeyError`:
> 
> ```
> KeyError                                  Traceback (most recent call last)
> <ipython-input-18-9e6cf2daa44e> in <module>
>       6 #for exch in exchanges:
>       7 #    for
> ----> 8 get_futures_daily_df = ak.get_futures_daily(start_date="20030109", end_date="20030114", market="DCE", index_bar=False)
>       9 #print(get_futures_daily_df[get_futures_daily_df['symbol'] == "A1007"])
>      10 print('daisy', get_futures_daily_df)
> 
> ~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
>     439     df_list = list()
>     440     while start_date <= end_date:
> --> 441         df = f(date=str(start_date).replace("-", ""))
>     442         if df is not None:
>     443             df_list.append(df)
> 
> ~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_dce_daily(date)
>     379     data_df = data_df[~data_df["商品名称"].str.contains("小计")]
>     380     data_df = data_df[~data_df["商品名称"].str.contains("总计")]
> --> 381     data_df["variety"] = data_df["商品名称"].map(lambda x: cons.DCE_MAP[x])
>     382     data_df["symbol"] = data_df["variety"] + data_df["交割月份"].astype(int).astype(str)
>     383     del data_df["商品名称"]
> 
> c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\series.py in map(self, arg, na_action)
>    3968         dtype: object
>    3969         """
> -> 3970         new_values = super()._map_values(arg, na_action=na_action)
>    3971         return self._constructor(new_values, index=self.index).__finalize__(
>    3972             self, method="map"
> 
> c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\base.py in _map_values(self, mapper, na_action)
>    1158 
>    1159         # mapper is a function
> -> 1160         new_values = map_f(values, mapper)
>    1161 
>    1162         return new_values
> 
> pandas\_libs\lib.pyx in pandas._libs.lib.map_infer()
> 
> ~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in <lambda>(x)
>     379     data_df = data_df[~data_df["商品名称"].str.contains("小计")]
>     380     data_df = data_df[~data_df["商品名称"].str.contains("总计")]
> --> 381     data_df["variety"] = data_df["商品名称"].map(lambda x: cons.DCE_MAP[x])
>     382     data_df["symbol"] = data_df["variety"] + data_df["交割月份"].astype(int).astype(str)
>     383     del data_df["商品名称"]
> 
> KeyError: '大豆'```
> ```
> 
> This should return Empty if there's no data, None is it's not a trading date.
> 
> And bad zip file from
> 
> ```
> ---------------------------------------------------------------------------
> BadZipFile                                Traceback (most recent call last)
> <ipython-input-29-6845f4f04823> in <module>
>       6 #for exch in exchanges:
>       7 #    for
> ----> 8 get_futures_daily_df = ak.get_futures_daily(start_date="20081101", end_date="20081107", market="CFFEX", index_bar=False)
>       9 #print(get_futures_daily_df[get_futures_daily_df['symbol'] == "A1007"])
>      10 print('daisy', get_futures_daily_df)
> 
> ~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
>     439     df_list = list()
>     440     while start_date <= end_date:
> --> 441         df = f(date=str(start_date).replace("-", ""))
>     442         if df is not None:
>     443             df_list.append(df)
> 
> ~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_cffex_daily(date)
>      49     r = requests.get(url)
>      50 
> ---> 51     with zipfile.ZipFile(BytesIO(r.content)) as file:
>      52         with file.open(f"{date}_1.csv") as my_file:
>      53             data = my_file.read().decode("gb2312")
> 
> c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\zipfile.py in __init__(self, file, mode, compression, allowZip64, compresslevel)
>    1220         try:
>    1221             if mode == 'r':
> -> 1222                 self._RealGetContents()
>    1223             elif mode in ('w', 'x'):
>    1224                 # set the modified flag so central directory gets written
> 
> c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\zipfile.py in _RealGetContents(self)
>    1287             raise BadZipFile("File is not a zip file")
>    1288         if not endrec:
> -> 1289             raise BadZipFile("File is not a zip file")
>    1290         if self.debug > 1:
>    1291             print(endrec)
> 
> BadZipFile: File is not a zip file
> ```
> 
> ```
> get_futures_daily_df = ak.get_futures_daily(start_date='20200918', end_date='20200918', market='DCE', index_bar=False)
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-42-872a1fba4a04> in <module>
> ----> 1 get_futures_daily_df = ak.get_futures_daily(start_date='20200918', end_date='20200918', market='CFFEX', index_bar=False)
> 
> ~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
>     439     df_list = list()
>     440     while start_date <= end_date:
> --> 441         df = f(date=str(start_date).replace("-", ""))
>     442         if df is not None:
>     443             df_list.append(df)
> 
> ~\AppData\Roaming\Python\Python37\site-packages\akshare\futures\futures_daily_bar.py in get_cffex_daily(date)
>      61     variety_list = [re.compile(r"[a-zA-Z_]+").findall(item)[0] for item in symbol_list]
>      62     data_df.columns = ["symbol", "open", "high", "low", "volume", "turnover",
> ---> 63                        "open_interest", "_", "close", "settle", "pre_settle", "_", "_", "_", "_"]
>      64     data_df["date"] = date
>      65     data_df["variety"] = variety_list
> 
> c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\generic.py in __setattr__(self, name, value)
>    5147         try:
>    5148             object.__getattribute__(self, name)
> -> 5149             return object.__setattr__(self, name, value)
>    5150         except AttributeError:
>    5151             pass
> 
> pandas\_libs\properties.pyx in pandas._libs.properties.AxisProperty.__set__()
> 
> c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\generic.py in _set_axis(self, axis, labels)
>     562     def _set_axis(self, axis: int, labels: Index) -> None:
>     563         labels = ensure_index(labels)
> --> 564         self._mgr.set_axis(axis, labels)
>     565         self._clear_item_cache()
>     566 
> 
> c:\users\daisy.z\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\internals\managers.py in set_axis(self, axis, new_labels)
>     225         if new_len != old_len:
>     226             raise ValueError(
> --> 227                 f"Length mismatch: Expected axis has {old_len} elements, new "
>     228                 f"values have {new_len} elements"
>     229             )
> 
> ValueError: Length mismatch: Expected axis has 14 elements, new values have 15 elements
> ```

Thanks for your issues, please update AkShare to 0.6.38
