### ISSUE TITLE
调取国家债券指数名称时报错

### ISSUE THREAD

**Issue by congcong009** [jindaxiang/akshare#570]
调用函数为：
ak.bond_investing_global_country_name_url(country=”美国”) 

文档位置：
https://www.akshare.xyz/zh_CN/latest/data/bond/bond.html#id21

返回错误：

```
df = pd.DataFrame(ak.bond_investing_global_country_name_url(country="美国"))
  File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
    index = extract_index(arrays)
  File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 355, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
```

**Comment by jindaxiang** [comment]
> 调用函数为：
> ak.bond_investing_global_country_name_url(country=”美国”)
> 
> 文档位置：
> https://www.akshare.xyz/zh_CN/latest/data/bond/bond.html#id21
> 
> 返回错误：
> 
> ```
> df = pd.DataFrame(ak.bond_investing_global_country_name_url(country="美国"))
>   File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
>     mgr = init_dict(data, index, columns, dtype=dtype)
>   File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 254, in init_dict
>     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
>   File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 64, in arrays_to_mgr
>     index = extract_index(arrays)
>   File "/Users/######/.conda/envs/######/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 355, in extract_index
>     raise ValueError("If using all scalar values, you must pass an index")
> ValueError: If using all scalar values, you must pass an index
> ```

运行正常，没发现该问题
