### ISSUE TITLE
中证指数-国债期货

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#576]
您好，

不知道akshare有没有计划加入中证指数网站上的一些内容。
比如这个http://www.csindex.com.cn/zh-CN/bond-valuation/bond-futures-deliverable-coupons-related-indicators 
如果能通过api下载历史数据的话，对于国债期货就尤其有用。

非常感谢您提供了这样一个优秀的工具。

**Comment by jindaxiang** [comment]
> 您好，
> 
> 不知道akshare有没有计划加入中证指数网站上的一些内容。
> 比如这个http://www.csindex.com.cn/zh-CN/bond-valuation/bond-futures-deliverable-coupons-related-indicators
> 如果能通过api下载历史数据的话，对于国债期货就尤其有用。
> 
> 非常感谢您提供了这样一个优秀的工具。

升级到 AkShare，bond_futures_deliverable_coupons 接口
