### ISSUE TITLE
[feature] 消费者信心指数

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#582]
您好，
非常感谢您提供这个优秀的工具。我想问一下，有没有可能增加这个数据项
https://data.eastmoney.com/cjsj/xfzxx.html
谢谢

**Comment by jindaxiang** [comment]
> 您好，
> 非常感谢您提供这个优秀的工具。我想问一下，有没有可能增加这个数据项
> https://data.eastmoney.com/cjsj/xfzxx.html
> 谢谢

已增加，升级到 AkShare 0.6.45
