### ISSUE TITLE
[feature]存款准备金率

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#585]
您好，请问能否在akshare中加入存款准备金率的调整?
https://data.eastmoney.com/cjsj/reserverequirementratio.aspx?p=1
非常感谢您！

**Comment by jindaxiang** [comment]
> 您好，请问能否在akshare中加入存款准备金率的调整?
> https://data.eastmoney.com/cjsj/reserverequirementratio.aspx?p=1
> 非常感谢您！

已新增，请更新到 AkShare 0.6.46 使用
