### ISSUE TITLE
您好，baidu相关的几个指数提取报错。

### ISSUE THREAD

**Issue by brbisheng** [jindaxiang/akshare#586]
平台为google colab。

例子为doc里提供的样例：
`baidu_search_index_df = ak.baidu_search_index(word="螺纹钢", start_date='2010-12-27', end_date='2019-12-01', cookie=cookie);
print(baidu_search_index_df);`

提示：
TypeError: string indices must be integers.

谢谢

**Comment by jindaxiang** [comment]
> 平台为google colab。
> 
> 例子为doc里提供的样例：
> `baidu_search_index_df = ak.baidu_search_index(word="螺纹钢", start_date='2010-12-27', end_date='2019-12-01', cookie=cookie); print(baidu_search_index_df);`
> 
> 提示：
> TypeError: string indices must be integers.
> 
> 谢谢

接口没有问题，请参考文档使用
