### ISSUE TITLE
ticker series from continuous time series 

### ISSUE THREAD

**Issue by daisypupu** [jindaxiang/akshare#591]
1. 新浪连续合约是否是按主力连续合约里的规则拼接的?
2. Would love to see an API providing ticker and roll adjustment for creating continuous time series. There are many many ways to stitch futures time series. An API that takes parameters like OI multiple, trade multiple would be great. For example, OI multiple = 1.1, trade multiple = 1.0 means roll when OI of next contract in line > 1.1 * OI_front_month && trade volume > 1.0 * trade_volume_front_month. With tickers and roll adjustment, users can perform roll adjustment as they like. Wind lets user set roll parameters and export roll-adjustment time series but they don't give the ticker series.

**Comment by jindaxiang** [comment]
> 1. 新浪连续合约是否是按主力连续合约里的规则拼接的?
> 2. Would love to see an API providing ticker and roll adjustment for creating continuous time series. There are many many ways to stitch futures time series. An API that takes parameters like OI multiple, trade multiple would be great. For example, OI multiple = 1.1, trade multiple = 1.0 means roll when OI of next contract in line > 1.1 * OI_front_month && trade volume > 1.0 * trade_volume_front_month. With tickers and roll adjustment, users can perform roll adjustment as they like. Wind lets user set roll parameters and export roll-adjustment time series but they don't give the ticker series.

新浪连续合约未公布拼接的细节内容，使用的时候请注意数据源的一致性
