### ISSUE TITLE
akshare.futures.cot.get_rank_sum return wrong result

### ISSUE THREAD

**Issue by nixgnef** [jindaxiang/akshare#592]
**Describe the bug**

a simple bug example:

|symbol | variety | vol_top5 | vol_chg_top5|
|  ----  | ----  |----  |----  |
|J | J | 123867 | 5623|
|AP | AP | 83,87326,99026,82025,26625,104 | 12,103-1,7872,5711572,033|

We can see that _akshare.futures.cot.get_rank_sum_ return wrong result  when vars_list has a var from czce

Because  the return value of _get_czce_rank_table_  has different format with _get_dce_rank_table_ and others, it has ',' in the numbers.

**Fix the bug**

insert the next code block into  _akshare.futures.cot.get_rank_sum_  after line 145 in cot.py

```
                if var in czce_var:
                    for col in [item for item in table.columns if item.find('open_interest')>-1]+['vol','vol_chg']:
                        table[col] = [float(value.replace(',','')) if value!='-' else 0.0 for value in table[col]]

```

**Comment by jindaxiang** [comment]
> **Describe the bug**
> 
> a simple bug example:
> 
> symbol	variety	vol_top5	vol_chg_top5
> J	J	123867	5623
> AP	AP	83,87326,99026,82025,26625,104	12,103-1,7872,5711572,033
> We can see that _akshare.futures.cot.get_rank_sum_ return wrong result when vars_list has a var from czce
> 
> Because the return value of _get_czce_rank_table_ has different format with _get_dce_rank_table_ and others, it has ',' in the numbers.
> 
> **Fix the bug**
> 
> insert the next code block into _akshare.futures.cot.get_rank_sum_ after line 145 in cot.py
> 
> ```
>                 if var in czce_var:
>                     for col in [item for item in table.columns if item.find('open_interest')>-1]+['vol','vol_chg']:
>                         table[col] = [float(value.replace(',','')) if value!='-' else 0.0 for value in table[col]]
> ```

Thanks for your code for fixing the errors, please update AkShare to 0.6.48

**Comment by nixgnef** [comment]
@jindaxiang  Uh... In fact, I feel a little sorry.  It seems that a better  way to fix this bug is to modify _akshare.futures.cot.get_czce_rank_table_ .

**Comment by jindaxiang** [comment]
> @jindaxiang Uh... In fact, I feel a little sorry. It seems that a better way to fix this bug is to modify _akshare.futures.cot.get_czce_rank_table_ .

That' ok, this interface will be adjusted in future
