### ISSUE TITLE
GDP相关指标

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#595]
您好，
请问有没有可能在akshare中加入
1. 进出口数据：http://data.eastmoney.com/cjsj/hgjck.html
2. 消费品零售：http://data.eastmoney.com/cjsj/xfp.html

非常感谢！

**Comment by jindaxiang** [comment]
> 您好，
> 请问有没有可能在akshare中加入
> 
> 1. 进出口数据：http://data.eastmoney.com/cjsj/hgjck.html
> 2. 消费品零售：http://data.eastmoney.com/cjsj/xfp.html
> 
> 非常感谢！

已更新，请升级到 AkShare 0.6.50
