### ISSUE TITLE
[features]新浪宏观数据

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#599]
您好，

不知道您是否有计划加入一些新浪网上的宏观数据? 这些宏观数据都非常有价值，而且好像不是特别常见。比如:
社会用电量：http://finance.sina.com.cn/mac/#industry-6-0-31-1
运输: http://finance.sina.com.cn/mac/#industry-10-0-31-1
邮政：http://finance.sina.com.cn/mac/#industry-11-0-31-1
存款性公司情况：http://finance.sina.com.cn/mac/#fininfo-17-0-31-2
央行资产负债表：http://finance.sina.com.cn/mac/#fininfo-8-0-31-2
![image](https://user-images.githubusercontent.com/359830/94810692-59cbcf80-03c2-11eb-83c1-1a7bb188bae8.png)
尤其是很多**月度**数据，都是一些领先指标，会非常有价值。

非常感谢您的无私帮助！

**Comment by jindaxiang** [comment]
> 您好，
> 
> 不知道您是否有计划加入一些新浪网上的宏观数据? 这些宏观数据都非常有价值，而且好像不是特别常见。比如:
> 社会用电量：http://finance.sina.com.cn/mac/#industry-6-0-31-1
> 运输: http://finance.sina.com.cn/mac/#industry-10-0-31-1
> 邮政：http://finance.sina.com.cn/mac/#industry-11-0-31-1
> 存款性公司情况：http://finance.sina.com.cn/mac/#fininfo-17-0-31-2
> 央行资产负债表：http://finance.sina.com.cn/mac/#fininfo-8-0-31-2
> ![image](https://user-images.githubusercontent.com/359830/94810692-59cbcf80-03c2-11eb-83c1-1a7bb188bae8.png)
> 尤其是很多**月度**数据，都是一些领先指标，会非常有价值。
> 
> 非常感谢您的无私帮助！

请升级到 AkShare 0.6.55 使用，已更新
