### ISSUE TITLE
[feature] FR007 swap

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#607]
您好，
有没有可能增加这样一个数据: 7天回购的利率互换
http://www.chinamoney.com.cn/chinese/bkcurvfxhis/?cfgItemType=72&curveType=FR007

尤其是其中的**收盘**曲线

再次感谢您的贡献

**Comment by jindaxiang** [comment]
> 您好，
> 有没有可能增加这样一个数据: 7天回购的利率互换
> http://www.chinamoney.com.cn/chinese/bkcurvfxhis/?cfgItemType=72&curveType=FR007
> 
> 尤其是其中的**收盘**曲线
> 
> 再次感谢您的贡献

升级到 AkShare 0.6.56 已更新

**Comment by NP-Prob** [comment]
> > 您好，
> > 有没有可能增加这样一个数据: 7天回购的利率互换
> > http://www.chinamoney.com.cn/chinese/bkcurvfxhis/?cfgItemType=72&curveType=FR007
> > 尤其是其中的**收盘**曲线
> > 再次感谢您的贡献
> 
> 升级到 AkShare 0.6.56 已更新

您好，最新的版本似乎无法获取到这个数据了，请问这是直接从官网拉取数据吗？是不是官网不再提供该数据了呢？
感谢！
