### ISSUE TITLE
[feature]每日空气质量

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#610]
您好，

不知道akshare是否有计划加入下面的数据：每日空气质量(历史数据), 比如
https://www.aqistudy.cn/historydata/daydata.php?city=上海&month=201312

如果数据量大的话，可以考虑在api中加入**城市**和**月份**作为参数，这样可能比较灵活一些

再次感谢您的无私贡献

**Comment by jindaxiang** [comment]
> 您好，
> 
> 不知道akshare是否有计划加入下面的数据：每日空气质量(历史数据), 比如
> [https://www.aqistudy.cn/historydata/daydata.php?city=上海&month=201312](https://www.aqistudy.cn/historydata/daydata.php?city=%E4%B8%8A%E6%B5%B7&month=201312)
> 
> 如果数据量大的话，可以考虑在api中加入**城市**和**月份**作为参数，这样可能比较灵活一些
> 
> 再次感谢您的无私贡献

在空气质量接口中已经存在，请阅读相关文档

**Comment by edwardsun** [comment]
您好，

akshare现存文档中的空气质量数据可能历史不够长。
链接中提供的数据源有着更长历史的每日数据，可能从研究的角度来说更具有价值。

![image](https://user-images.githubusercontent.com/359830/95334948-c0e2fb80-087c-11eb-8ce1-59ca07376024.png)
![image](https://user-images.githubusercontent.com/359830/95334977-c9d3cd00-087c-11eb-955e-901586700519.png)

非常感谢

**Comment by jindaxiang** [comment]
> 您好，
> 
> akshare现存文档中的空气质量数据可能历史不够长。
> 链接中提供的数据源有着更长历史的每日数据，可能从研究的角度来说更具有价值。
> 
> ![image](https://user-images.githubusercontent.com/359830/95334948-c0e2fb80-087c-11eb-8ce1-59ca07376024.png)
> ![image](https://user-images.githubusercontent.com/359830/95334977-c9d3cd00-087c-11eb-955e-901586700519.png)
> 
> 非常感谢

分段获取即可

**Comment by edwardsun** [comment]
很管用，非常感谢！
