### ISSUE TITLE
能新增抓取国债、AAA超短期融资券、AAA中期票据、AAA公司债券、AAA政府专项债数据吗？

### ISSUE THREAD

**Issue by JasonJasonXU** [jindaxiang/akshare#612]
目前ak用chinabond的数据源有以下三个
    中债国债收益率曲线  
  中债商业银行普通债收益率曲线(AAA)  
 中债中短期票据收益率曲线(AAA)

能用chinamoney的网页，抓取国债、AAA超短期融资券、AAA中期票据、AAA公司债券、AAA政府专项债五个数据。
数据来源，http://www.chinamoney.com.cn/chinese/bkcurvclosedy/ 点下载后可以跳转到更详细的数据页面

http://www.chinamoney.com.cn/chinese/bkcurvclosedycomphis/?bondType=CYCC000&compareBodeType=CYCC84A&startDate=2020-09-30&endDate=2020-09-30

或者用chinabond的数据源增加AAA超短期融资券、AAA中期票据、AAA公司债券、AAA政府专项债 这4个品种。
多谢。

**Comment by jindaxiang** [comment]
> 目前ak用chinabond的数据源有以下三个
> 中债国债收益率曲线
> 中债商业银行普通债收益率曲线(AAA)
> 中债中短期票据收益率曲线(AAA)
> 
> 能用chinamoney的网页，抓取国债、AAA超短期融资券、AAA中期票据、AAA公司债券、AAA政府专项债五个数据。
> 数据来源，http://www.chinamoney.com.cn/chinese/bkcurvclosedy/ 点下载后可以跳转到更详细的数据页面
> 
> http://www.chinamoney.com.cn/chinese/bkcurvclosedycomphis/?bondType=CYCC000&compareBodeType=CYCC84A&startDate=2020-09-30&endDate=2020-09-30
> 
> 或者用chinabond的数据源增加AAA超短期融资券、AAA中期票据、AAA公司债券、AAA政府专项债 这4个品种。
> 多谢。

请升级到 AkShare 0.6.59 已更新 bond_china_close_return 接口

**Comment by JasonJasonXU** [comment]
奥利给
