### ISSUE TITLE
抓取龙虎榜数据有误

### ISSUE THREAD

**Issue by jamesleo** [jindaxiang/akshare#613]
网站：http://vip.stock.finance.sina.com.cn/q/go.php/vInvestConsult/kind/lhb/index.phtml?tradedate=2020-07-30
2020-7-30 数据
示例所抓取的 涨幅偏离值达7%的证券 数据正确
接下来还有2个表
1.连续三个交易日内，涨幅偏离值累计达20%的证券  (结果不再举例，看下面一个例子）
2.换手率达20%的证券
抓取的数据都错了，还差得比较远
stock_sina_lhb_detail_20change_df = ak.stock_sina_lhb_detail_daily(trade_date="20200730", symbol="换手率达20%的证券")
>>> print(stock_sina_lhb_detail_20change_df)
   序号    股票代码  股票名称   收盘价  对应值        成交量       成交额
0   1  300028   金亚退  0.31    0  1061.0149  326.8418
1   2  300090   盛运退  0.12    0  5190.7250  622.2574
2   3  300156   神雾退  0.13    0  2070.3548  269.2403
3   4  002220   天宝退  0.24    0   223.9757   52.8805
4   5  600175  退市美都  0.17    0  2367.0804  412.0600
5   6  600069  退市银鸽  0.20    0   421.6500   84.3300
6   7  900951  退市大化  0.05    0    40.1000    1.8100
而实际网页显示的数据是：
//----------------------------
换手率达20%的证券
--
序号 | 股票代码 | 股票名称 | 收盘价(元) | 对应值(%) | 成交量(万股) | 成交额(万元) | 查看详情
1 | 002030 | 达安基因 | 40.83 | 20.64 | 17674.6085 | 702130.7001 | 查看交易详情
2 | 000518 | 四环生物 | 5.81 | 23.31 | 24000.9936 | 136374.7225 | 查看交易详情
3 | 000820 | *ST节能 | 1.03 | 26.31 | 7568.0517 | 7423.7282 | 查看交易详情
4 | 300840 | 酷特智能 | 23.87 | 43.46 | 2607.5349 | 60256.8008 | 查看交易详情
5 | 300842 | 帝科股份 | 90.41 | 35.29 | 882.2652 | 78374.1226 | 查看交易详情
6 | 300846 | 首都在线 | 32.15 | 63.16 | 3157.7971 | 104546.0573 | 查看交易详情
7 | 300847 | 中船汉光 | 30.5 | 69.31 | 3419.6702 | 111387.6114 | 查看交易详情
8 | 300850 | 新强联 | 58.97 | 34.71 | 919.8237 | 52536.5437 | 查看交易详情
9 | 002610 | 爱康科技 | 2.78 | 23.14 | 101493.1314 | 276012.6241 | 查看交易详情
10 | 603733 | 仙鹤股份 | 21.01 | 55.48 | 3440.1524 | 71863.2000 | 查看交易详情
11 | 603949 | 雪龙集团 | 27.36 | 45.13 | 1691.0997 | 46940.7800 | 查看交易详情
12 | 603976 | 正川股份 | 84.44 | 43.25 | 1656.3628 | 134557.5400 | 查看交易详情
13 | 002910 | 庄园牧场 | 11.55 | 20.76 | 1538.4387 | 17984.6406 | 查看交易详情
14 | 002980 | 华盛昌 | 75.81 | 22.28 | 742.6531 | 55296.4670 | 查看交易详情

**Comment by jindaxiang** [comment]
> 网站：http://vip.stock.finance.sina.com.cn/q/go.php/vInvestConsult/kind/lhb/index.phtml?tradedate=2020-07-30
> 2020-7-30 数据
> 示例所抓取的 涨幅偏离值达7%的证券 数据正确
> 接下来还有2个表
> 1.连续三个交易日内，涨幅偏离值累计达20%的证券 (结果不再举例，看下面一个例子）
> 2.换手率达20%的证券
> 抓取的数据都错了，还差得比较远
> stock_sina_lhb_detail_20change_df = ak.stock_sina_lhb_detail_daily(trade_date="20200730", symbol="换手率达20%的证券")
> 
> > > > print(stock_sina_lhb_detail_20change_df)
> > > > 序号    股票代码  股票名称   收盘价  对应值        成交量       成交额
> > > > 0   1  300028   金亚退  0.31    0  1061.0149  326.8418
> > > > 1   2  300090   盛运退  0.12    0  5190.7250  622.2574
> > > > 2   3  300156   神雾退  0.13    0  2070.3548  269.2403
> > > > 3   4  002220   天宝退  0.24    0   223.9757   52.8805
> > > > 4   5  600175  退市美都  0.17    0  2367.0804  412.0600
> > > > 5   6  600069  退市银鸽  0.20    0   421.6500   84.3300
> > > > 6   7  900951  退市大化  0.05    0    40.1000    1.8100
> > > > 而实际网页显示的数据是：
> > > > //----------------------------
> > > > 换手率达20%的证券
> > > > --
> > > > 序号 | 股票代码 | 股票名称 | 收盘价(元) | 对应值(%) | 成交量(万股) | 成交额(万元) | 查看详情
> > > > 1 | 002030 | 达安基因 | 40.83 | 20.64 | 17674.6085 | 702130.7001 | 查看交易详情
> > > > 2 | 000518 | 四环生物 | 5.81 | 23.31 | 24000.9936 | 136374.7225 | 查看交易详情
> > > > 3 | 000820 | *ST节能 | 1.03 | 26.31 | 7568.0517 | 7423.7282 | 查看交易详情
> > > > 4 | 300840 | 酷特智能 | 23.87 | 43.46 | 2607.5349 | 60256.8008 | 查看交易详情
> > > > 5 | 300842 | 帝科股份 | 90.41 | 35.29 | 882.2652 | 78374.1226 | 查看交易详情
> > > > 6 | 300846 | 首都在线 | 32.15 | 63.16 | 3157.7971 | 104546.0573 | 查看交易详情
> > > > 7 | 300847 | 中船汉光 | 30.5 | 69.31 | 3419.6702 | 111387.6114 | 查看交易详情
> > > > 8 | 300850 | 新强联 | 58.97 | 34.71 | 919.8237 | 52536.5437 | 查看交易详情
> > > > 9 | 002610 | 爱康科技 | 2.78 | 23.14 | 101493.1314 | 276012.6241 | 查看交易详情
> > > > 10 | 603733 | 仙鹤股份 | 21.01 | 55.48 | 3440.1524 | 71863.2000 | 查看交易详情
> > > > 11 | 603949 | 雪龙集团 | 27.36 | 45.13 | 1691.0997 | 46940.7800 | 查看交易详情
> > > > 12 | 603976 | 正川股份 | 84.44 | 43.25 | 1656.3628 | 134557.5400 | 查看交易详情
> > > > 13 | 002910 | 庄园牧场 | 11.55 | 20.76 | 1538.4387 | 17984.6406 | 查看交易详情
> > > > 14 | 002980 | 华盛昌 | 75.81 | 22.28 | 742.6531 | 55296.4670 | 查看交易详情

感谢反馈问题，请升级到 AkShare 0.6.57 已修复
