### ISSUE TITLE
龙虎榜数据-5日-10日均出错

### ISSUE THREAD

**Issue by jamesleo** [jindaxiang/akshare#618]
根据接口手册，尝试了抓取个股上榜信息（今天是10月8日，过去5天没有数据）
import akshare as ak
>>> stock_sina_lhb_ggtj_df = ak.stock_sina_lhb_ggtj(recent_day="5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python38\lib\site-packages\akshare\stock_feature\stock_sina_lhb.py", line 73, in stock_sina_lhb_ggtj
    last_page_num = int(soup.find_all(attrs={"class": "page"})[-2].text)
IndexError: list index out of range

如果把最近日期改为 10 天，则：
 stock_sina_lhb_ggtj_df = ak.stock_sina_lhb_ggtj(recent_day="10")
 25%|█████████████████████████████████                                                                                                  50%|█████████████████████████████████ █████████████████████████████████                                75%|█████████████████████████████████████████████████████████████████████████████████100%|█████████████████████████████████████████████ ████████████████████████████████████100%|█████████████████████ ███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  4.20it/s]
>>> print(stock_sina_lhb_ggtj_df)
Empty DataFrame
Columns: [股票代码, 股票名称, 上榜次数, 累积购买额, 累积卖出额, 净额, 买入席位数, 卖出席位数]
Index: []
貌似也没有抓取成功
Empty DataFrame ？

**Comment by jindaxiang** [comment]
> ak.stock_sina_lhb_ggtj(recent_day="5")

感谢反馈问题，请升级到 AkShare 0.6.60
