### ISSUE TITLE
[feature]原油，黄金，美元指数

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#619]
您好，
请问akshare是否有计划加入一些国际性的金融数据，比如：
WTI原油: https://www.investing.com/currencies/wti-usd-historical-data
Brent原油: https://www.investing.com/currencies/xbr-usd-historical-data
美元指数: https://www.investing.com/indices/usdollar-historical-data
黄金现货: https://www.investing.com/currencies/xau-usd-historical-data

非常感谢！

**Comment by jindaxiang** [comment]
> 您好，
> 请问akshare是否有计划加入一些国际性的金融数据，比如：
> WTI原油: https://www.investing.com/currencies/wti-usd-historical-data
> Brent原油: https://www.investing.com/currencies/xbr-usd-historical-data
> 美元指数: https://www.investing.com/indices/usdollar-historical-data
> 黄金现货: https://www.investing.com/currencies/xau-usd-historical-data
> 
> 非常感谢！

已经有上述接口

**Comment by edwardsun** [comment]
> 已经有上述接口

您好，akshare中确实有相应的期货数据，但也确实没有**现货**数据。上述列表中的品种都是现货数据。
谢谢您。

**Comment by jindaxiang** [comment]
> > 已经有上述接口
> 
> 您好，akshare中确实有相应的期货数据，但也确实没有**现货**数据。上述列表中的品种都是现货数据。
> 谢谢您。

通过    
currency_hist_df = currency_hist(symbol="wti-usd", start_date="20190101", end_date="20201011")
接口获取，
美元指数通过 index_investing_global 接口获取
