### ISSUE TITLE
请教，历史分笔数据返回为空

### ISSUE THREAD

**Issue by NedLi** [jindaxiang/akshare#621]
尊敬的作者您好！

非常感谢您的辛勤劳动，创作并分享了很好的Python包！

在学习使用akshare的历史分笔数据功能的过程，中某些股票的历史分笔数据返回为空。例如，

import akshare as ak

stock_zh_a_tick_tx_df = ak.stock_zh_a_tick_tx(code="sh601865", trade_date="20190301")

stock_zh_a_tick_tx_df = ak.stock_zh_a_tick_163(code="sh601865", trade_date="20190301")

print(stock_zh_a_tick_tx_df)

以上分别返回：
“Empty DataFrame
Columns: [暂无数据]”

“无当前交易日数据，请稍后再试
None”

请问有没有解决办法，谢谢！

**Comment by jindaxiang** [comment]
> 尊敬的作者您好！
> 
> 非常感谢您的辛勤劳动，创作并分享了很好的Python包！
> 
> 在学习使用akshare的历史分笔数据功能的过程，中某些股票的历史分笔数据返回为空。例如，
> 
> import akshare as ak
> 
> stock_zh_a_tick_tx_df = ak.stock_zh_a_tick_tx(code="sh601865", trade_date="20190301")
> 
> stock_zh_a_tick_tx_df = ak.stock_zh_a_tick_163(code="sh601865", trade_date="20190301")
> 
> print(stock_zh_a_tick_tx_df)
> 
> 以上分别返回：
> “Empty DataFrame
> Columns: [暂无数据]”
> 
> “无当前交易日数据，请稍后再试
> None”
> 
> 请问有没有解决办法，谢谢！

感谢反馈问题，目前这两个接口只能获取近期的 tick 数据

**Comment by NedLi** [comment]
谢谢回复，祝愿这个包越办越好！
