### ISSUE TITLE
bond_investing: 涨跌幅

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#638]
您好，
在bond_investing.py中有一行代码是这样的：

df_data = df_data[["收盘", "开盘", "高", "低", **"涨跌幅"**]]
#df_data["涨跌幅"] = df_data["涨跌幅"].str.replace("%", "")

债券收益率中，收益率按百分比计算的涨跌幅没有什么实际用途。
一般而言，pnl=久期*收益率变化, 所以实际上不按百分比计算。
另外，有些国债的收益率是负数，这时百分比计算涨跌幅会失去意义。

另2: 获取部分国家债券，比如挪威1年期国债的时候，涨跌幅的计算会导致异常抛出

所以建议直接去掉 涨跌幅 这一列。

谢谢您

**Comment by jindaxiang** [comment]
> 您好，
> 在bond_investing.py中有一行代码是这样的：
> 
> df_data = df_data[["收盘", "开盘", "高", "低", **"涨跌幅"**]]
> #df_data["涨跌幅"] = df_data["涨跌幅"].str.replace("%", "")
> 
> 债券收益率中，收益率按百分比计算的涨跌幅没有什么实际用途。
> 一般而言，pnl=久期*收益率变化, 所以实际上不按百分比计算。
> 另外，有些国债的收益率是负数，这时百分比计算涨跌幅会失去意义。
> 
> 另2: 获取部分国家债券，比如挪威1年期国债的时候，涨跌幅的计算会导致异常抛出
> 
> 所以建议直接去掉 涨跌幅 这一列。
> 
> 谢谢您

感谢反馈问题，由于是源网站提供的数据就一并提供计算好的涨跌幅数据，主要是由于 "," 引起的报错
请升级到 AkShare 0.6.70 ，已修复
