### ISSUE TITLE
Refactor suggestion

### ISSUE THREAD

**Issue by daisypupu** [jindaxiang/akshare#643]
https://github.com/jindaxiang/akshare/blob/master/akshare/futures/receipt.py#L377

when start_day == end_day and not a business day, this line throws KeyError exception. I'd suggest adding below before this line:
```
if records.empty:
  return records
```

**Comment by jindaxiang** [comment]
> https://github.com/jindaxiang/akshare/blob/master/akshare/futures/receipt.py#L377
> 
> when start_day == end_day and not a business day, this line throws KeyError exception. I'd suggest adding below before this line:
> 
> ```
> if records.empty:
>   return records
> ```

感谢反馈问题，请升级到 AkShare 0.6.72，已修复
