### ISSUE TITLE
ValueError from get_receipt

### ISSUE THREAD

**Issue by daisypupu** [jindaxiang/akshare#644]
```res = ak.get_receipt(start_day="20201014", end_day="20201014", vars_list=['AG', 'AL', 'AU', 'BU', 'CU', 'FU', 'HC', 'NI', 'PB', 'RB', 'RU', 'SN', 'SP', 'SS', 'ZN', 'LU', 'NR', 'WR', 'A', 'B', 'BB', 'C', 'CS', 'EB', 'EG', 'FB', 'I', 'J', 'JD', 'JM', 'L', 'M', 'P', 'PG', 'PP', 'RR', 'V', 'Y', 'AP', 'CF', 'CJ', 'CY', 'FG', 'JR', 'LR', 'MA', 'OI', 'PM', 'RI', 'RM', 'RS', 'SA', 'SF', 'SM', 'SR', 'TA', 'UR', 'WH', 'ZC'])```

Output:
2020-10-15
白糖SR
一号棉CF
棉纱CY
菜粕RM
菜籽油OI
菜籽RS
普麦PM
早籼稻RI
晚籼稻LR
粳稻JR
苹果AP
红枣CJ
甲醇MA
玻璃FG
动力煤ZC
硅铁SF
锰硅SM
尿素UR
纯碱SA

ValueError                                Traceback (most recent call last)

...
    371                 if market != 'cffex' and get_vars != []:
    372                     if f is not None:
--> 373                         records = records.append(f(start_day, get_vars))
    374 
    375         start_day += datetime.timedelta(days=1)

...\akshare\futures\receipt.py in get_shfe_receipt_2(date, vars_list)
    146     for var in set(data['VARNAME'].tolist()):
    147         data_cut = data[data['VARNAME'] == var]
--> 148         data_dict = {'var': chinese_to_english(re.sub(r"\W|[a-zA-Z]", "", var)),
    149                      'receipt': int(data_cut['WRTWGHTS'].tolist()[-1]),
    150                      'receipt_chg': int(data_cut['WRTCHANGE'].tolist()[-1]),

...\akshare\futures\symbol_var.py in chinese_to_english(chinese_var)
    237         "LU"
    238     ]
--> 239     pos = chinese_list.index(chinese_var)
    240     return english_list[pos]
    241 

ValueError: '纸浆厂库' is not in list

**Comment by jindaxiang** [comment]
> `res = ak.get_receipt(start_day="20201014", end_day="20201014", vars_list=['AG', 'AL', 'AU', 'BU', 'CU', 'FU', 'HC', 'NI', 'PB', 'RB', 'RU', 'SN', 'SP', 'SS', 'ZN', 'LU', 'NR', 'WR', 'A', 'B', 'BB', 'C', 'CS', 'EB', 'EG', 'FB', 'I', 'J', 'JD', 'JM', 'L', 'M', 'P', 'PG', 'PP', 'RR', 'V', 'Y', 'AP', 'CF', 'CJ', 'CY', 'FG', 'JR', 'LR', 'MA', 'OI', 'PM', 'RI', 'RM', 'RS', 'SA', 'SF', 'SM', 'SR', 'TA', 'UR', 'WH', 'ZC'])`
> 
> Output:
> 2020-10-15
> 白糖SR
> 一号棉CF
> 棉纱CY
> 菜粕RM
> 菜籽油OI
> 菜籽RS
> 普麦PM
> 早籼稻RI
> 晚籼稻LR
> 粳稻JR
> 苹果AP
> 红枣CJ
> 甲醇MA
> 玻璃FG
> 动力煤ZC
> 硅铁SF
> 锰硅SM
> 尿素UR
> 纯碱SA
> 
> ValueError Traceback (most recent call last)
> 
> ...
> 371 if market != 'cffex' and get_vars != []:
> 372 if f is not None:
> --> 373 records = records.append(f(start_day, get_vars))
> 374
> 375 start_day += datetime.timedelta(days=1)
> 
> ...\akshare\futures\receipt.py in get_shfe_receipt_2(date, vars_list)
> 146 for var in set(data['VARNAME'].tolist()):
> 147 data_cut = data[data['VARNAME'] == var]
> --> 148 data_dict = {'var': chinese_to_english(re.sub(r"\W|[a-zA-Z]", "", var)),
> 149 'receipt': int(data_cut['WRTWGHTS'].tolist()[-1]),
> 150 'receipt_chg': int(data_cut['WRTCHANGE'].tolist()[-1]),
> 
> ...\akshare\futures\symbol_var.py in chinese_to_english(chinese_var)
> 237 "LU"
> 238 ]
> --> 239 pos = chinese_list.index(chinese_var)
> 240 return english_list[pos]
> 241
> 
> ValueError: '纸浆厂库' is not in list

感谢反馈问题，请升级到 AkShare 0.6.72，已修复
