### ISSUE TITLE
[bug] eastmoney数据运行出错

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#649]
**Describe the bug**
akshare部分函数在eastmoney网站上抓取数据出错。

**To Reproduce**
1. ak.macro_china_new_financial_credit()
2. ak.macro_china_fx_gold()
3. ak.macro_china_wbck()
4. ak.macro_china_gdzctz()
5. ak.macro_china_ppi(); ak.macro_china_cpi()
6. ak.macro_china_hgjck()

**Expected behavior**
正常情况下都能抓取数据，如果网站访问正常，则应该能顺利抓取数据

**Screenshots**
举例: 出错函数
![image](https://user-images.githubusercontent.com/359830/96365652-230aee80-1110-11eb-9e2e-9a14c25db0a6.png)
目标地址却能顺利访问
![image](https://user-images.githubusercontent.com/359830/96365682-61081280-1110-11eb-8980-59617074c3b3.png)

**Desktop (please complete the following information):**
ubuntu 20.04

**Comment by jindaxiang** [comment]
> **Describe the bug**
> akshare部分函数在eastmoney网站上抓取数据出错。
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. ak.macro_china_new_financial_credit()
> 2. ak.macro_china_fx_gold()
> 3. ak.macro_china_wbck()
> 4. ak.macro_china_gdzctz()
> 5. ak.macro_china_ppi(); ak.macro_china_cpi()
> 6. ak.macro_china_hgjck()
> 
> **Expected behavior**
> 正常情况下都能抓取数据，如果网站访问正常，则应该能顺利抓取数据
> 
> **Screenshots**
> 举例: 出错函数
> ![image](https://user-images.githubusercontent.com/359830/96365652-230aee80-1110-11eb-9e2e-9a14c25db0a6.png)
> 目标地址却能顺利访问
> ![image](https://user-images.githubusercontent.com/359830/96365682-61081280-1110-11eb-8980-59617074c3b3.png)
> 
> **Desktop (please complete the following information):**
> ubuntu 20.04

感谢反馈问题，由于东方财富网站接口变动，相关接口已经修复，请升级到 AkShare 0.6.74

**Comment by edwardsun** [comment]
您好,
上面还有几个函数好像还是出错。

ak.macro_china_pmi()
ak.macro_china_wbck()
ak.macro_china_gdzctz()
ak.macro_china_ppi()
ak.macro_china_ppi()
ak.macro_china_hgjck()


比如:
![image](https://user-images.githubusercontent.com/359830/96388655-436e9380-1178-11eb-84b0-0ef323b22b15.png)

**Comment by jindaxiang** [comment]
> macro_china_hgjck

没有发现相关的问题

**Comment by edwardsun** [comment]
> 没有发现相关的问题

好的，谢谢您
