### ISSUE TITLE
AkShare 接口问题报告（获取国内商品期货历史行情数据部分市场报异常）

### ISSUE THREAD

**Issue by tashaxing** [jindaxiang/akshare#674]
**调用接口获取SHFE市场的历史行情数据报异常**
1. 操作系统版本
windows7
2. Python 版本
3.7.4
3. AkShare 版本
0.6.84
4. 接口的名称和代码
`get_futures_daily_df = ak.get_futures_daily(start_date="20200701", end_date="20200716", market="SHFE", index_bar=True)
get_futures_daily_df`
5. 接口报错的截图或代码
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
D:\apps\Miniconda3\lib\site-packages\pandas\core\series.py in __setitem__(self, key, value)
   1013         try:
-> 1014             self._set_with_engine(key, value)
   1015         except com.SettingWithCopyError:

D:\apps\Miniconda3\lib\site-packages\pandas\core\series.py in _set_with_engine(self, key, value)
   1053         try:
-> 1054             self.index._engine.set_value(values, key, value)
   1055             return

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.set_value()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.set_value()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

TypeError: '['volume', 'open_interest', 'turnover']' is an invalid key

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-37-962cce8e10d5> in <module>
----> 1 get_futures_daily_df = ak.get_futures_daily(start_date="20200701", end_date="20200716", market="SHFE", index_bar=True)
      2 get_futures_daily_df

D:\apps\Miniconda3\lib\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
    452             df_list.append(df)
    453             if index_bar:
--> 454                 df_list.append(get_futures_index(df))
    455         start_date += datetime.timedelta(days=1)
    456 

D:\apps\Miniconda3\lib\site-packages\akshare\futures\futures_daily_bar.py in get_futures_index(df)
    476             index_df = pd.Series(index=df_cut.columns, dtype="object")
    477             index_df[["volume", "open_interest", "turnover"]] = df_cut[
--> 478                 ["volume", "open_interest", "turnover"]
    479             ].sum()
    480             if "efp" in df_cut.iloc[-1, 0]:

D:\apps\Miniconda3\lib\site-packages\pandas\core\series.py in __setitem__(self, key, value)
   1040                     pass
   1041 
-> 1042             self._set_with(key, value)
   1043 
   1044         if cacher_needs_updating:

D:\apps\Miniconda3\lib\site-packages\pandas\core\series.py in _set_with(self, key, value)
   1096                 self._set_values(key.astype(np.bool_), value)
   1097             else:
-> 1098                 self._set_labels(key, value)
   1099 
   1100     def _set_labels(self, key, value):

D:\apps\Miniconda3\lib\site-packages\pandas\core\series.py in _set_labels(self, key, value)
   1104         if mask.any():
   1105             raise ValueError(f"{key[mask]} not contained in the index")
-> 1106         self._set_values(indexer, value)
   1107 
   1108     def _set_values(self, key, value):

D:\apps\Miniconda3\lib\site-packages\pandas\core\series.py in _set_values(self, key, value)
   1109         if isinstance(key, Series):
   1110             key = key._values
-> 1111         self._data = self._data.setitem(indexer=key, value=value)
   1112         self._maybe_update_cacher()
   1113 

D:\apps\Miniconda3\lib\site-packages\pandas\core\internals\managers.py in setitem(self, **kwargs)
    559 
    560     def setitem(self, **kwargs):
--> 561         return self.apply("setitem", **kwargs)
    562 
    563     def putmask(self, **kwargs):

D:\apps\Miniconda3\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, filter, **kwargs)
    440                 applied = b.apply(f, **kwargs)
    441             else:
--> 442                 applied = getattr(b, f)(**kwargs)
    443             result_blocks = _extend_blocks(applied, result_blocks)
    444 

D:\apps\Miniconda3\lib\site-packages\pandas\core\internals\blocks.py in setitem(self, indexer, value)
    875 
    876         # length checking
--> 877         check_setitem_lengths(indexer, value, values)
    878         exact_match = (
    879             len(arr_value.shape)

D:\apps\Miniconda3\lib\site-packages\pandas\core\indexers.py in check_setitem_lengths(indexer, value, values)
    112             ):
    113                 raise ValueError(
--> 114                     "cannot set using a list-like indexer "
    115                     "with a different length than the value"
    116                 )

ValueError: cannot set using a list-like indexer with a different length than the value`
6. 期望获得的正确结果
获取到数据dataframe

**Comment by jindaxiang** [comment]
> 4\. 20200716

可以正常获取数据

**Comment by tashaxing** [comment]
你别关issue啊，并没有解决呀
参数里 index_bar=True 就不行，index_bar=False就可以
报错是
ValueError: cannot set using a list-like indexer with a different length than the value

**Comment by jindaxiang** [comment]
> 你别关issue啊，并没有解决呀
> 参数里 index_bar=True 就不行，index_bar=False就可以
> 报错是
> ValueError: cannot set using a list-like indexer with a different length than the value

运行相关代码并复现该 bug，请升级到最新版使用

**Comment by tashaxing** [comment]
我升级到了最新版akshare 0.6.89，试了下还是报这个错
运行这句代码
get_futures_daily_df = ak.get_futures_daily(start_date="20200701", end_date="20200716", market="SHFE", index_bar=True) 
你能复现下吗

**Comment by jindaxiang** [comment]
> 我升级到了最新版akshare 0.6.89，试了下还是报这个错
> 运行这句代码
> get_futures_daily_df = ak.get_futures_daily(start_date="20200701", end_date="20200716", market="SHFE", index_bar=True)
> 你能复现下吗

Win10 和 Ubuntu20.04 + Python 3.8.5 + AkShare 0.6.89 可以获取数据
