### ISSUE TITLE
建议增加一些实时数据

### ISSUE THREAD

**Issue by ent-crawl** [jindaxiang/akshare#678]

**Comment by ent-crawl** [comment]
建议增加开放式基金的近三个月，六个月，近一年，近三年和近五年的收益率，就像天天基金网上的基金排行那样

**Comment by jindaxiang** [comment]
> 建议增加开放式基金的近三个月，六个月，近一年，近三年和近五年的收益率，就像天天基金网上的基金排行那样

感谢反馈意见，请升级到 AkShare 0.6.90 版本，已更新相关接口：https://www.akshare.xyz/zh_CN/latest/data/fund/fund_public.html#id13
