### ISSUE TITLE
[feature]回购/逆回购利率

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#686]
您好，
请问akshare有没有计划加入 回购利率 历史？
http://www.chinamoney.com.cn/chinese/bkfrr/
谢谢

**Comment by jindaxiang** [comment]
> 您好，
> 请问akshare有没有计划加入 回购利率 历史？
> http://www.chinamoney.com.cn/chinese/bkfrr/
> 谢谢

请升级到 AkShare 0.6.92，已更新：repo_rate_hist 接口
