### ISSUE TITLE
[bug]macro_china_market_margin_sh返回值缺少数据

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#696]
**Describe the bug**
ak.macro_china_market_margin_sh()的返回值缺少最近日期那页

**To Reproduce**

![image](https://user-images.githubusercontent.com/359830/97782611-e22bc480-1b68-11eb-95ac-659177436743.png)
![image](https://user-images.githubusercontent.com/359830/97782710-739b3680-1b69-11eb-98bd-d16144bcea08.png)

**Expected behavior**
返回值需要返回最近日期前一交易日的两融数据

**Screenshots**
见图

**Comment by jindaxiang** [comment]
> macro_china_market_margin_sh

感谢反馈问题，请升级到 AkShare 0.6.95 已更新
