### ISSUE TITLE
akshare throws exeception

### ISSUE THREAD

**Issue by cuizhiqiang0** [jindaxiang/akshare#7]
I use akshare with version 0.3.75 .
and I use ak.stock_zh_a_spot() to get all symbols which involve sh603290。But when I use ak.stock_zh_a_daily(symbol='sh603290') I got a exeception. This can be reproduced stably。

**Comment by jindaxiang** [comment]
`    
stock_zh_a_daily_df = stock_zh_a_daily(symbol="sh603290")
print(stock_zh_a_daily_df)
`
`
             open   high    low  close  volume
date                                          
2020-02-04  15.29  18.35  15.29  18.35  345569
`

**Comment by jindaxiang** [comment]
No errors

**Comment by cuizhiqiang0** [comment]
now is works well. sh603290  just came out today

**Comment by jindaxiang** [comment]
yeah, it may be data updated in sina!
