### ISSUE TITLE
error pulling SHFE daily data on 20020104, 20040625, 20070604, 20081226, 20090119

### ISSUE THREAD

**Issue by daisypupu** [jindaxiang/akshare#705]
```df = ak.get_futures_daily(start_date="20090119", end_date="20090119", market="SHFE", index_bar=False)```

```---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-5-3a79d5879f6f> in <module>
----> 1 df = ak.get_futures_daily(start_date="20090119", end_date="20090119", market="SHFE", index_bar=False)

\appdata\local\programs\python\python39\lib\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
    448     df_list = list()
    449     while start_date <= end_date:
--> 450         df = f(date=str(start_date).replace("-", ""))
    451         if df is not None:
    452             df_list.append(df)

\appdata\local\programs\python\python39\lib\site-packages\akshare\futures\futures_daily_bar.py in get_shfe_daily(date)
    307         return None
    308     try:
--> 309         json_data = json.loads(
    310             requests_link(
    311                 cons.SHFE_DAILY_URL % (day.strftime("%Y%m%d")),

\appdata\local\programs\python\python39\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    344             parse_int is None and parse_float is None and
    345             parse_constant is None and object_pairs_hook is None and not kw):
--> 346         return _default_decoder.decode(s)
    347     if cls is None:
    348         cls = JSONDecoder

\appdata\local\programs\python\python39\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

\appdata\local\programs\python\python39\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by jindaxiang** [comment]
> `df = ak.get_futures_daily(start_date="20090119", end_date="20090119", market="SHFE", index_bar=False)`
> 
> ```
> JSONDecodeError                           Traceback (most recent call last)
> <ipython-input-5-3a79d5879f6f> in <module>
> ----> 1 df = ak.get_futures_daily(start_date="20090119", end_date="20090119", market="SHFE", index_bar=False)
> 
> \appdata\local\programs\python\python39\lib\site-packages\akshare\futures\futures_daily_bar.py in get_futures_daily(start_date, end_date, market, index_bar)
>     448     df_list = list()
>     449     while start_date <= end_date:
> --> 450         df = f(date=str(start_date).replace("-", ""))
>     451         if df is not None:
>     452             df_list.append(df)
> 
> \appdata\local\programs\python\python39\lib\site-packages\akshare\futures\futures_daily_bar.py in get_shfe_daily(date)
>     307         return None
>     308     try:
> --> 309         json_data = json.loads(
>     310             requests_link(
>     311                 cons.SHFE_DAILY_URL % (day.strftime("%Y%m%d")),
> 
> \appdata\local\programs\python\python39\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
>     344             parse_int is None and parse_float is None and
>     345             parse_constant is None and object_pairs_hook is None and not kw):
> --> 346         return _default_decoder.decode(s)
>     347     if cls is None:
>     348         cls = JSONDecoder
> 
> \appdata\local\programs\python\python39\lib\json\decoder.py in decode(self, s, _w)
>     335 
>     336         """
> --> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>     338         end = _w(s, end).end()
>     339         if end != len(s):
> 
> \appdata\local\programs\python\python39\lib\json\decoder.py in raw_decode(self, s, idx)
>     353             obj, end = self.scan_once(s, idx)
>     354         except StopIteration as err:
> --> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
>     356         return obj, end
> 
> JSONDecodeError: Expecting value: line 1 column 1 (char 0)```
> ```

感谢反馈问题，http://www.shfe.com.cn/statements/dataview.html?paramid=kx 网页相应数据缺失
