### ISSUE TITLE
module 'akshare' has no attribute 'stock_us_name'

### ISSUE THREAD

**Issue by ingf** [jindaxiang/akshare#713]
**Describe the bug**

**To Reproduce**
```
import akshare as ak
us_stock = ak.stock_us_name()
print(us_stock)
```

**Expected behavior**
print us_stock

**Screenshots**

**Desktop (please complete the following information):**
 - OS: colab

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jindaxiang** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> ```
> import akshare as ak
> us_stock = ak.stock_us_name()
> print(us_stock)
> ```
> 
> **Expected behavior**
> print us_stock
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: colab
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Thanks for your issues, please use `get_us_stock_name`  to fetch data
