### ISSUE TITLE
传入日期和指数代码，获取指数在该日期时的成分股票

### ISSUE THREAD

**Issue by morkong** [jindaxiang/akshare#723]
在使用时akShare时，我想根据index_stock_hist和index_stock_cons中获取的数据，筛选出指数在给定日期时的成分股票，比如我想获取”000001“指数2015年10月21日时的成分股票，但是在有限的数据中，我无法筛选出那时候的成分股票。如果能够有一个接口能实现传入日期和指数代码，就可以得到指数在该日期时的成分股票就好了。

**Comment by jindaxiang** [comment]
> 在使用时akShare时，我想根据index_stock_hist和index_stock_cons中获取的数据，筛选出指数在给定日期时的成分股票，比如我想获取”000001“指数2015年10月21日时的成分股票，但是在有限的数据中，我无法筛选出那时候的成分股票。如果能够有一个接口能实现传入日期和指数代码，就可以得到指数在该日期时的成分股票就好了。

这是一个好主意
