### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by TaylorScut** [jindaxiang/akshare#724]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
Windows 10
2. Python 版本
Python3.7.9
3. AkShare 版本
0.7.5
4. 接口的名称和代码
get_country_bond

import akshare as ak
bond_df = ak.get_country_bond(country="中国", index_name="中国10年期国债", start_date='2010/01/01', end_date='2020/11/10')
5. 接口报错的截图或代码
AttributeError: module 'akshare' has no attribute 'get_country_bond'

6. 期望获得的正确结果
估计get_country_bond代码被遗漏了

**Comment by jindaxiang** [comment]
> get_country_bond

感谢反馈该问题，目前文档已更新，该接口重名为为 bond_investing_global，参考网址：https://www.akshare.xyz/zh_CN/latest/data/bond/bond.html?highlight=bond_investing_global#id21
