### ISSUE TITLE
AkShare 导入失败

### ISSUE THREAD

**Issue by lystrosaurus** [jindaxiang/akshare#731]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
window 64
2. Python 版本
3.8.5
3. AkShare 版本
![image](https://user-images.githubusercontent.com/3240489/99067148-2ac19400-25e5-11eb-9546-aaa9c0f2d86b.png)

4. 接口的名称和代码
5. 接口报错的截图或代码

```pyrhon
>>> import akshare as ak
Traceback (most recent call last):
  File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Users\fatty\Anaconda3\lib\site-packages\akshare\__init__.py", line 1146, in <module>
    from akshare.fortune.hurun import hurun_rank
  File "D:\Users\fatty\Anaconda3\lib\site-packages\akshare\fortune\hurun.py", line 8, in <module>
    import numpy as np
  File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import core
  File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "D:\Users\fatty\Anaconda3\python.exe"
  * The NumPy version is: "1.19.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

```

6. 期望获得的正确结果

第一步就失败了，我需要帮助，都是最新的，谢谢

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    window 64
> 2. Python 版本
>    3.8.5
> 3. AkShare 版本
>    ![image](https://user-images.githubusercontent.com/3240489/99067148-2ac19400-25e5-11eb-9546-aaa9c0f2d86b.png)
> 4. 接口的名称和代码
> 5. 接口报错的截图或代码
> 
> ```
> >>> import akshare as ak
> Traceback (most recent call last):
>   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
>     from . import multiarray
>   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
>     from . import overrides
>   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
>     from numpy.core._multiarray_umath import (
> ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\Users\fatty\Anaconda3\lib\site-packages\akshare\__init__.py", line 1146, in <module>
>     from akshare.fortune.hurun import hurun_rank
>   File "D:\Users\fatty\Anaconda3\lib\site-packages\akshare\fortune\hurun.py", line 8, in <module>
>     import numpy as np
>   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
>     from . import core
>   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
>     raise ImportError(msg)
> ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the numpy C-extensions failed. This error can happen for
> many reasons, often due to issues with your setup or how NumPy was
> installed.
> 
> We have compiled some common reasons and troubleshooting tips at:
> 
>     https://numpy.org/devdocs/user/troubleshooting-importerror.html
> 
> Please note and check the following:
> 
>   * The Python version is: Python3.8 from "D:\Users\fatty\Anaconda3\python.exe"
>   * The NumPy version is: "1.19.4"
> 
> and make sure that they are the versions you expect.
> Please carefully study the documentation linked above for further help.
> 
> Original error was: No module named 'numpy.core._multiarray_umath'
> ```
> 
> 1. 期望获得的正确结果
> 
> 第一步就失败了，我需要帮助，都是最新的，谢谢

pip install --upgrade numpy

**Comment by lystrosaurus** [comment]
> > **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> > ```
> > pip install akshare --upgrade  # Python 版本需要大于 3.7
> > ```
> > 
> > 
> > **描述遇到的问题**
> > 
> > 1. 操作系统版本
> >    window 64
> > 2. Python 版本
> >    3.8.5
> > 3. AkShare 版本
> >    ![image](https://user-images.githubusercontent.com/3240489/99067148-2ac19400-25e5-11eb-9546-aaa9c0f2d86b.png)
> > 4. 接口的名称和代码
> > 5. 接口报错的截图或代码
> > 
> > ```
> > >>> import akshare as ak
> > Traceback (most recent call last):
> >   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
> >     from . import multiarray
> >   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
> >     from . import overrides
> >   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
> >     from numpy.core._multiarray_umath import (
> > ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> >   File "D:\Users\fatty\Anaconda3\lib\site-packages\akshare\__init__.py", line 1146, in <module>
> >     from akshare.fortune.hurun import hurun_rank
> >   File "D:\Users\fatty\Anaconda3\lib\site-packages\akshare\fortune\hurun.py", line 8, in <module>
> >     import numpy as np
> >   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\__init__.py", line 140, in <module>
> >     from . import core
> >   File "D:\Users\fatty\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
> >     raise ImportError(msg)
> > ImportError:
> > 
> > IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> > 
> > Importing the numpy C-extensions failed. This error can happen for
> > many reasons, often due to issues with your setup or how NumPy was
> > installed.
> > 
> > We have compiled some common reasons and troubleshooting tips at:
> > 
> >     https://numpy.org/devdocs/user/troubleshooting-importerror.html
> > 
> > Please note and check the following:
> > 
> >   * The Python version is: Python3.8 from "D:\Users\fatty\Anaconda3\python.exe"
> >   * The NumPy version is: "1.19.4"
> > 
> > and make sure that they are the versions you expect.
> > Please carefully study the documentation linked above for further help.
> > 
> > Original error was: No module named 'numpy.core._multiarray_umath'
> > ```
> > 
> > 
> > 
> > 1. 期望获得的正确结果
> > 
> > 第一步就失败了，我需要帮助，都是最新的，谢谢
> 
> pip install --upgrade numpy


![image](https://user-images.githubusercontent.com/3240489/99202083-f4ecfd00-27e8-11eb-852c-780c0b00e046.png)

已经是最新的了，网上查询过这个错误，也是提示更新，不管用，还有什么其他的可能原因吗？不是python开发者，都是按文档操作来的，谢谢。

**Comment by lystrosaurus** [comment]
解决了：
1：pip uninstall numpy
2：conda install numpy
3：conda install pandas
4：conda install kiwisolver
现在可以正常导入了，谢谢
