### ISSUE TITLE
中国人民银行数据统计

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#787]
你好，

请问akshare有没有计划加入央行的各个统计数据的历史记录

http://www.pbc.gov.cn/diaochatongjisi/116219/116319/index.html

这里面每个表都极具价值。

非常感谢！

**Comment by jindaxiang** [comment]
> 你好，
> 
> 请问akshare有没有计划加入央行的各个统计数据的历史记录
> 
> http://www.pbc.gov.cn/diaochatongjisi/116219/116319/index.html
> 
> 这里面每个表都极具价值。
> 
> 非常感谢！

在中国宏观已经涵盖大部分数据
