### ISSUE TITLE
希望可以覆盖国证指数数据

### ISSUE THREAD

**Issue by scanfyu** [jindaxiang/akshare#791]
**Is your feature request related to a problem? Please describe.**
希望在数据中可以覆盖到国证指数数据

**Describe the solution you'd like**
地址：http://www.cnindex.com.cn/

**Describe alternatives you've considered**
样例接口：http://www.cnindex.com.cn/syl/index/index_syl.json
样例返回值：{"date":"2020-11-27","shmarket":[{"ca":"87","dwer":"17.02","enTn":"Energy","swer":"12.83","tc":"C01","tn":"能源"},{"ca":"639","dwer":"24.43","enTn":"Materials","swer":"25.31","tc":"C02","tn":"原材料"},{"ca":"998","dwer":"22.89","enTn":"Industrials","swer":"23.92","tc":"C03","tn":"工业"},{"ca":"630","dwer":"28.59","enTn":"Consumer Staples","swer":"26.31","tc":"C04","tn":"可选消费"},{"ca":"221","dwer":"35.66","enTn":"Consumer Discretionary","swer":"44.84","tc":"C05","tn":"主要消费"},{"ca":"355","dwer":"42.76","enTn":"Health Care","swer":"53.23","tc":"C06","tn":"医药卫生"},{"ca":"125","dwer":"10.16","enTn":"Financials","swer":"9.79","tc":"C07","tn":"金融"},{"ca":"675","dwer":"46.88","enTn":"Information Technology","swer":"51.85","tc":"C08","tn":"信息技术"},{"ca":"116","dwer":"44.12","enTn":"Telecommunication Services","swer":"47.30","tc":"C09","tn":"电信业务"},{"ca":"116","dwer":"16.41","enTn":"Utilities","swer":"19.15","tc":"C10","tn":"公用事业"},{"ca":"138","dwer":"8.90","enTn":"Real Estate","swer":"8.94","tc":"C11","tn":"房地产"}],"szmarket":[{"ca":"28","dwer":"11.24","enTn":"Agriculture","swer":"17.41","tc":"A","tn":"农、林、牧、渔业"},{"ca":"27","dwer":"24.17","enTn":"Mining","swer":"24.68","tc":"B","tn":"采矿业"},{"ca":"1567","dwer":"35.94","enTn":"Manufacture","swer":"41.04","tc":"C","tn":"制造业"},{"ca":"45","dwer":"13.46","enTn":"Utilities","swer":"16.96","tc":"D","tn":"电力、热力、燃气及水生产和供应业"},{"ca":"54","dwer":"16.86","enTn":"Construction","swer":"19.83","tc":"E","tn":"建筑业"},{"ca":"69","dwer":"26.56","enTn":"Wholesale and retail","swer":"18.84","tc":"F","tn":"批发和零售业"},{"ca":"34","dwer":"35.53","enTn":"Transportation","swer":"26.70","tc":"G","tn":"交通运输、仓储和邮政业"},{"ca":"6","dwer":"NA","enTn":"Hotels and Catering","swer":"37.81","tc":"H","tn":"住宿和餐饮业"},{"ca":"233","dwer":"40.37","enTn":"IT","swer":"49.44","tc":"I","tn":"信息传输、软件和信息技术服务业"},{"ca":"40","dwer":"18.55","enTn":"Finance","swer":"21.75","tc":"J","tn":"金融业"},{"ca":"57","dwer":"8.62","enTn":"Real Estate","swer":"8.56","tc":"K","tn":"房地产业"}]}

**Additional context**
希望可以覆盖到，感谢。

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 希望在数据中可以覆盖到国证指数数据
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 地址：http://www.cnindex.com.cn/
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 样例接口：http://www.cnindex.com.cn/syl/index/index_syl.json
> 样例返回值：{"date":"2020-11-27","shmarket":[{"ca":"87","dwer":"17.02","enTn":"Energy","swer":"12.83","tc":"C01","tn":"能源"},{"ca":"639","dwer":"24.43","enTn":"Materials","swer":"25.31","tc":"C02","tn":"原材料"},{"ca":"998","dwer":"22.89","enTn":"Industrials","swer":"23.92","tc":"C03","tn":"工业"},{"ca":"630","dwer":"28.59","enTn":"Consumer Staples","swer":"26.31","tc":"C04","tn":"可选消费"},{"ca":"221","dwer":"35.66","enTn":"Consumer Discretionary","swer":"44.84","tc":"C05","tn":"主要消费"},{"ca":"355","dwer":"42.76","enTn":"Health Care","swer":"53.23","tc":"C06","tn":"医药卫生"},{"ca":"125","dwer":"10.16","enTn":"Financials","swer":"9.79","tc":"C07","tn":"金融"},{"ca":"675","dwer":"46.88","enTn":"Information Technology","swer":"51.85","tc":"C08","tn":"信息技术"},{"ca":"116","dwer":"44.12","enTn":"Telecommunication Services","swer":"47.30","tc":"C09","tn":"电信业务"},{"ca":"116","dwer":"16.41","enTn":"Utilities","swer":"19.15","tc":"C10","tn":"公用事业"},{"ca":"138","dwer":"8.90","enTn":"Real Estate","swer":"8.94","tc":"C11","tn":"房地产"}],"szmarket":[{"ca":"28","dwer":"11.24","enTn":"Agriculture","swer":"17.41","tc":"A","tn":"农、林、牧、渔业"},{"ca":"27","dwer":"24.17","enTn":"Mining","swer":"24.68","tc":"B","tn":"采矿业"},{"ca":"1567","dwer":"35.94","enTn":"Manufacture","swer":"41.04","tc":"C","tn":"制造业"},{"ca":"45","dwer":"13.46","enTn":"Utilities","swer":"16.96","tc":"D","tn":"电力、热力、燃气及水生产和供应业"},{"ca":"54","dwer":"16.86","enTn":"Construction","swer":"19.83","tc":"E","tn":"建筑业"},{"ca":"69","dwer":"26.56","enTn":"Wholesale and retail","swer":"18.84","tc":"F","tn":"批发和零售业"},{"ca":"34","dwer":"35.53","enTn":"Transportation","swer":"26.70","tc":"G","tn":"交通运输、仓储和邮政业"},{"ca":"6","dwer":"NA","enTn":"Hotels and Catering","swer":"37.81","tc":"H","tn":"住宿和餐饮业"},{"ca":"233","dwer":"40.37","enTn":"IT","swer":"49.44","tc":"I","tn":"信息传输、软件和信息技术服务业"},{"ca":"40","dwer":"18.55","enTn":"Finance","swer":"21.75","tc":"J","tn":"金融业"},{"ca":"57","dwer":"8.62","enTn":"Real Estate","swer":"8.56","tc":"K","tn":"房地产业"}]}
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 希望可以覆盖到，感谢。

已更新到 AkShare，请升级到 0.7.32 版本使用，具体接口为：index_cni_hist
