### ISSUE TITLE
bond ytm historical data

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#8]
您好，
请问akshare是否有国债历史收益率的数据呢？
手动的话，可以从http://yield.chinabond.com.cn/cbweb-pbc-web/pbc/showHistory?locale=cn_ZH
上下载。但是不知道是否可以通过python程序化抓取。
![image](https://user-images.githubusercontent.com/359830/73790784-0dff5280-476f-11ea-8ac5-2ed69446d829.png)

多谢！

**Comment by jindaxiang** [comment]
yeah, it is a nice interface for bond research, i have update akshare to 0.3.78 and add the 'bond_china_yield' interface for fetching this data! Please updating your akshare to latest version!
