### ISSUE TITLE
Missing data 2016-09-19 futures_dce_position_rank

### ISSUE THREAD

**Issue by scottluu** [jindaxiang/akshare#813]
**Describe the bug**
When comparing the website (http://www.dce.com.cn/DCE/Market_Data/Market%20Statistics/index.html)
and the results returned from `akshare.futures_dce_position_rank()`, the website contains data that `akshare.futures_dce_position_rank()` doesnt have

**To Reproduce**
1. Go to http://www.dce.com.cn/DCE/Market_Data/Market%20Statistics/index.html
2. Choose 2016-09-19 for the date
3. Make sure `all` is selected
4. Click futures
5. In the table, see that data for c1707 appears
6. 
```python
import akshare
dict_frames = akshare.futures_dce_position_rank(date='2016-09-19')
print(dict_frames["c1707"])
```

**Expected behavior**
The data from step 5 and step 6 would be identical

**Screenshots**
<img width="802" alt="dce" src="https://user-images.githubusercontent.com/10699038/101526047-25443900-395a-11eb-8e39-9f748d509356.PNG">

**Desktop (please complete the following information):**
 - OS: centos
 - Browser: chrome
 - Version: 0.7.43

**Comment by jindaxiang** [comment]
> futures_dce_position_rank

Hello,
futures_dce_position_rank is used for http://www.dce.com.cn/dalianshangpin/xqsj/tjsj26/rtj/rcjccpm/index.html
you must mistake the interface
