### ISSUE TITLE
AkShare 接口问题报告 stock_hk_daily

### ISSUE THREAD

**Issue by dengwanc** [jindaxiang/akshare#815]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
2. Python 版本
3. AkShare 版本
4. 接口的名称和代码
```
ak.stock_hk_daily(symbol='00772', adjust="qfq")
# 港股以下证券代码均有问题
01833
00772
03690
00780
01797
01810
```
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/8290205/101663718-017e1180-3a86-11eb-8dbd-7f52502c7836.png)

6. 期望获得的正确结果
返回正确的 OHLC

**Comment by jindaxiang** [comment]
> 03690

感谢反馈问题，请升级到 AkShare 0.7.44 版本，已修复
