### ISSUE TITLE
Empty results on 20160919 for futures_dce_position_rank

### ISSUE THREAD

**Issue by scottluu** [jindaxiang/akshare#826]
**Describe the bug**
`akshare.futures_dce_position_rank()` returns no results

**Cause**
* When akshare makes the `post` request to download the zip file, the zip file contains files for TWO dates
`20160919` and `20160915`.
* `20160915` is not a trading date, so the files are empty, therefore it overwrites the results for `20160919`

**Solution**
Each filename in the zipfile starts with YYYYMMDD, there needs to be a check for the prefix date in the filename
example
```python
with zipfile.ZipFile(BytesIO(r.content), "r") as z:
    for i in z.namelist():
        file_name = i.encode('cp437').decode('GBK')
        if not file_name.startswith(date.strftime("%Y%m%d")):
            continue
        try:
```

**To Reproduce**
To see that the zip file returns files for two different dates:
```python
import datetime
import zipfile
import pandas as pd
from io import BytesIO

import requests


pd.set_option("display.max_rows", 4, "display.max_columns", None)

date = datetime.datetime(year=2016, month=9, day=19)
url = "http://www.dce.com.cn/publicweb/quotesdata/exportMemberDealPosiQuotesBatchData.html"
headers = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Accept-Encoding": "gzip, deflate",
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
    "Cache-Control": "no-cache",
    "Connection": "keep-alive",
    "Content-Length": "160",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "www.dce.com.cn",
    "Origin": "http://www.dce.com.cn",
    "Pragma": "no-cache",
    "Referer": "http://www.dce.com.cn/publicweb/quotesdata/memberDealPosiQuotes.html",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
}
payload = {
    "memberDealPosiQuotes.variety": "a",
    "memberDealPosiQuotes.trade_type": "0",
    "contract.contract_id": "a2009",
    "contract.variety_id": "a",
    "year": date.year,
    "month": date.month - 1,
    "day": date.day,
    "batchExportFlag": "batch",
}
r = requests.post(url, payload, headers=headers)
big_dict = dict()
with zipfile.ZipFile(BytesIO(r.content), "r") as z:
    for i in z.namelist():
        print(i)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jindaxiang** [comment]
> **Describe the bug**
> `akshare.futures_dce_position_rank()` returns no results
> 
> **Cause**
> 
> * When akshare makes the `post` request to download the zip file, the zip file contains files for TWO dates
>   `20160919` and `20160915`.
> * `20160915` is not a trading date, so the files are empty, therefore it overwrites the results for `20160919`
> 
> **Solution**
> Each filename in the zipfile starts with YYYYMMDD, there needs to be a check for the prefix date in the filename
> example
> 
> ```python
> with zipfile.ZipFile(BytesIO(r.content), "r") as z:
>     for i in z.namelist():
>         file_name = i.encode('cp437').decode('GBK')
>         if not file_name.startswith(date.strftime("%Y%m%d")):
>             continue
>         try:
> ```
> 
> **To Reproduce**
> To see that the zip file returns files for two different dates:
> 
> ```python
> import datetime
> import zipfile
> import pandas as pd
> from io import BytesIO
> 
> import requests
> 
> 
> pd.set_option("display.max_rows", 4, "display.max_columns", None)
> 
> date = datetime.datetime(year=2016, month=9, day=19)
> url = "http://www.dce.com.cn/publicweb/quotesdata/exportMemberDealPosiQuotesBatchData.html"
> headers = {
>     "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
>     "Accept-Encoding": "gzip, deflate",
>     "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
>     "Cache-Control": "no-cache",
>     "Connection": "keep-alive",
>     "Content-Length": "160",
>     "Content-Type": "application/x-www-form-urlencoded",
>     "Host": "www.dce.com.cn",
>     "Origin": "http://www.dce.com.cn",
>     "Pragma": "no-cache",
>     "Referer": "http://www.dce.com.cn/publicweb/quotesdata/memberDealPosiQuotes.html",
>     "Upgrade-Insecure-Requests": "1",
>     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
> }
> payload = {
>     "memberDealPosiQuotes.variety": "a",
>     "memberDealPosiQuotes.trade_type": "0",
>     "contract.contract_id": "a2009",
>     "contract.variety_id": "a",
>     "year": date.year,
>     "month": date.month - 1,
>     "day": date.day,
>     "batchExportFlag": "batch",
> }
> r = requests.post(url, payload, headers=headers)
> big_dict = dict()
> with zipfile.ZipFile(BytesIO(r.content), "r") as z:
>     for i in z.namelist():
>         print(i)
> ```
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context**
> Add any other context about the problem here.

Thanks for your solution about this interface, I have modified the code according to your sample!
Please update to AkShare 0.7.48
