### ISSUE TITLE
AkShare 接口问题报告--可转债转股价数据错误

### ISSUE THREAD

**Issue by shenglinqian** [jindaxiang/akshare#829]
**描述遇到的问题**
1. 操作系统版本--ubuntu-16
2. Python 版本--python 3.8
3. AkShare 版本-- lastest
4. 接口的名称和代码 -- bond_zh_cov_df = ak.bond_zh_cov()
5. 接口报错的截图或代码 -- bond_zh_cov_df = ak.bond_zh_cov()
6. 期望获得的正确结果
国贸转债的转股价结果是9.03，但是目标网页东财显示是7.19

**Comment by jindaxiang** [comment]
> 6\. 国贸转债

感谢反馈问题，请升级到 AkShare 0.7.47 版本，已修复
