### ISSUE TITLE
import akshare get JSONDecodeError: ('Unknown identifier', 'tml')

### ISSUE THREAD

**Issue by ziliangok** [jindaxiang/akshare#83]
import akshare as ak

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-124-c3439955029c> in <module>
----> 1 import akshare as ak

~\AppData\Roaming\Python\Python36\site-packages\akshare\__init__.py in <module>
   1359 外盘期货实时行情
   1360 """
-> 1361 from akshare.futures.hf_futures_sina import (
   1362     futures_hf_spot,
   1363     hf_subscribe_exchange_symbol,

~\AppData\Roaming\Python\Python36\site-packages\akshare\futures\hf_futures_sina.py in <module>
     50 
     51 
---> 52 def futures_hf_spot(subscribe_list=hf_subscribe_exchange_symbol()):
     53     """
     54     订阅数据处理

~\AppData\Roaming\Python\Python36\site-packages\akshare\futures\hf_futures_sina.py in hf_subscribe_exchange_symbol()
     45     res.encoding = "gb2312"
     46     data_json = demjson.decode(
---> 47         res.text[res.text.find("var oHF_1 = ") + 12: res.text.find("var oHF_2 = ") - 2]
     48     )
     49     return list(data_json.keys())

~\AppData\Roaming\Python\Python36\site-packages\demjson.py in decode(txt, encoding, **kwargs)
   5697                        encoding=encoding,
   5698                        return_errors=(return_errors or write_errors),
-> 5699                        return_stats=(return_stats or write_stats) )
   5700 
   5701     if write_errors:

~\AppData\Roaming\Python\Python36\site-packages\demjson.py in decode(self, txt, encoding, return_errors, return_stats)
   4913             errors = [err for err in state.errors if err.severity in ('fatal','error')]
   4914             if errors:
-> 4915                 raise errors[0]
   4916             if return_stats:
   4917                 return result_type(state.obj, None, state.stats)

JSONDecodeError: ('Unknown identifier', 'tml')

python 3.6.2
demjson 2.2.4
akshare 0.4.43

**Comment by jindaxiang** [comment]
Hello，please check node. js

**Comment by camilotorresmestra** [comment]
Why does it happen, tho?
