### ISSUE TITLE
xlrd新版不支持xlsx，期望更换excel解析库

### ISSUE THREAD

**Issue by skywolf123** [jindaxiang/akshare#854]
xlrd的2.0.1版本已经不支持xlsx，期望更换excel解析库，或者暂时限制xlrd的版本为1.2.0

**Comment by jindaxiang** [comment]
> xlrd的2.0.1版本已经不支持xlsx，期望更换excel解析库，或者暂时限制xlrd的版本为1.2.0

具体有影响哪个接口？

**Comment by skywolf123** [comment]
stock_info_sz_name_code

**Comment by jindaxiang** [comment]
> xlrd的2.0.1版本已经不支持xlsx，期望更换excel解析库，或者暂时限制xlrd的版本为1.2.0

感谢反馈问题，已经锁定版本，相关接口可以升级 pandas 到最新版本

**Comment by ssz25** [comment]
这个问题  好几个接口不能用哦  限制xlrd版本貌似也没用

**Comment by jindaxiang** [comment]
> 这个问题 好几个接口不能用哦 限制xlrd版本貌似也没用

哪几个接口不能用？
