### ISSUE TITLE
开放式基金-实时数据,fund_em_open_fund_daily()接口获取不到净值

### ISSUE THREAD

**Issue by xiaofeng1986** [jindaxiang/akshare#858]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本:OSX 11.1
2. Python 版本: python 3.9.0
3. AkShare 版本: akshare-0.7.59
4. 接口的名称和代码: 开放式基金-实时数据,fund_em_open_fund_daily()
5. 接口报错的截图或代码

**12/28开始获取不到数据，上周五12/25使用还是正常。**

![image](https://user-images.githubusercontent.com/6204598/103249032-44a61300-49a8-11eb-9d8b-174fc0bc4c7e.png)

接口事例
import akshare as ak
fund_em_open_fund_daily_df = ak.fund_em_open_fund_daily()
print(fund_em_open_fund_daily_df)

6. 期望获得的正确结果
![image](https://user-images.githubusercontent.com/6204598/103249078-80d97380-49a8-11eb-8cec-099910c670c0.png)

**Comment by jindaxiang** [comment]
> fund_em_open_fund_daily_df = ak.fund_em_open_fund_daily()
> print(fund_em_open_fund_daily_df)

感谢反馈问题，请升级到 AkShare 0.7.60 版本
