### ISSUE TITLE
开放式基金-实时数据,fund_em_open_fund_daily()接口获取不到信息

### ISSUE THREAD

**Issue by ZhangYishanSarah** [jindaxiang/akshare#862]
1.python版本是3.7.4
2.akshare版本是 0.7.60
3.fund_em_open_fund_daily_df = ak.fund_em_open_fund_daily()
print(fund_em_open_fund_daily_df)
抓取数据只有十行，无净值信息
![image](https://user-images.githubusercontent.com/61174386/103270688-83ad8600-49f3-11eb-8699-c878e40878af.png)

**Comment by jindaxiang** [comment]
> 1.python版本是3.7.4
> 2.akshare版本是 0.7.60
> 3.fund_em_open_fund_daily_df = ak.fund_em_open_fund_daily()
> print(fund_em_open_fund_daily_df)
> 抓取数据只有十行，无净值信息
> ![image](https://user-images.githubusercontent.com/61174386/103270688-83ad8600-49f3-11eb-8699-c878e40878af.png)

已检查，接口可以正常使用
