### ISSUE TITLE
被新浪的反爬限制，请问怎么样可以规避

### ISSUE THREAD

**Issue by sos0sso0** [jindaxiang/akshare#864]
错误提示：
HTTPSConnectionPool(host='vip.stock.finance.sina.com.cn', port=443): Max retries exceeded with url: /corp/go.php/vFD_FinanceSummary/stockid/600867.phtml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000240A18F53A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by jindaxiang** [comment]
> 错误提示：
> HTTPSConnectionPool(host='vip.stock.finance.sina.com.cn', port=443): Max retries exceeded with url: /corp/go.php/vFD_FinanceSummary/stockid/600867.phtml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000240A18F53A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

稍后尝试
