### ISSUE TITLE
2021年的交易日期未更新

### ISSUE THREAD

**Issue by changvin** [jindaxiang/akshare#871]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```
现在到了2021年，交易日期是通过读取文件文件实现的，需要更新交易日期文件 （calendar.json）

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> 现在到了2021年，交易日期是通过读取文件文件实现的，需要更新交易日期文件 （calendar.json）

感谢反馈问题，已经修复，请升级到 AkShare 0.7.61 版本
