### ISSUE TITLE
能否增加关于股票行业分类、概念分类相关的接口？

### ISSUE THREAD

**Issue by yinshurman** [jindaxiang/akshare#874]
** 由于每天都有新股上市，要是能有一个关于每个股票的行业、地域、概念分类相关的接口就好了，类比于tushare中的那些分类接口,[参考此处](http://tushare.org/classifying.html#id2)可惜tushare已经不维护了 
**

**Comment by wei-hai** [comment]
+1

**Comment by whatthezzzz** [comment]
1

**Comment by jindaxiang** [comment]
此接口容易被屏蔽

**Comment by leewi9** [comment]
行业数据感觉可以自己另外整理，不过如果能集成最好了

**Comment by jindaxiang** [comment]
> ** 由于每天都有新股上市，要是能有一个关于每个股票的行业、地域、概念分类相关的接口就好了，类比于tushare中的那些分类接口,[参考此处](http://tushare.org/classifying.html#id2)可惜tushare已经不维护了
> **

已经增加同花顺的分类接口，此 Issues 关闭
