### ISSUE TITLE
公募基金--基本净值--历史净值。历史净值接口不能用了，（发现时间：2021-1-3）

### ISSUE THREAD

**Issue by HanMuJiang** [jindaxiang/akshare#881]
https://www.akshare.xyz/zh_CN/latest/data/stock/stock.html#id59  

不能使用接口所在层级如下：公募基金--基本净值--历史净值。历史净值接口不能用了，（发现时间：2021-1-3）

示例代码及报错情况如下

1.#场外基金历史净值
import akshare as ak
fund_em_info_df = ak.fund_em_open_fund_info(fund="000905", indicator="单位净值走势")
print(fund_em_info_df)

报错如下：
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-1-d99d21fceb36> in <module>
      1 #场外基金历史净值
      2 import akshare as ak
----> 3 fund_em_info_df = ak.fund_em_open_fund_info(fund="000905", indicator="单位净值走势")
      4 print(fund_em_info_df)
      5 

C:\ProgramData\Anaconda3\lib\site-packages\akshare\fund\fund_em.py in fund_em_open_fund_info(fund, indicator)
    129     # 单位净值走势
    130     if indicator == "单位净值走势":
--> 131         data_json = demjson.decode(
    132             text[
    133                 text.find("Data_netWorthTrend")

C:\ProgramData\Anaconda3\lib\site-packages\demjson.py in decode(txt, encoding, **kwargs)
   5694 
   5695     # Now do the actual JSON decoding
-> 5696     result = j.decode( txt,
   5697                        encoding=encoding,
   5698                        return_errors=(return_errors or write_errors),

C:\ProgramData\Anaconda3\lib\site-packages\demjson.py in decode(self, txt, encoding, return_errors, return_stats)
   4913             errors = [err for err in state.errors if err.severity in ('fatal','error')]
   4914             if errors:
-> 4915                 raise errors[0]
   4916             if return_stats:
   4917                 return result_type(state.obj, None, state.stats)

JSONDecodeError: ('Unknown identifier', 'a')

2.#场内基金历史净值
import akshare as ak
fund_em_etf_fund_info_df = ak.fund_em_etf_fund_info(fund="163406")
print(fund_em_etf_fund_info_df)

报错如下：
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-2-0c300ed743e8> in <module>
      1 #场内基金历史净值
      2 import akshare as ak
----> 3 fund_em_etf_fund_info_df = ak.fund_em_etf_fund_info(fund="163406")
      4 print(fund_em_etf_fund_info_df)

C:\ProgramData\Anaconda3\lib\site-packages\akshare\fund\fund_em.py in fund_em_etf_fund_info(fund)
    655     r = requests.get(url, params=params, headers=headers)
    656     text_data = r.text
--> 657     data_json = demjson.decode(text_data[text_data.find("{") : -1])
    658     temp_df = pd.DataFrame(data_json["Data"]["LSJZList"])
    659     temp_df.columns = [

C:\ProgramData\Anaconda3\lib\site-packages\demjson.py in decode(txt, encoding, **kwargs)
   5694 
   5695     # Now do the actual JSON decoding
-> 5696     result = j.decode( txt,
   5697                        encoding=encoding,
   5698                        return_errors=(return_errors or write_errors),

C:\ProgramData\Anaconda3\lib\site-packages\demjson.py in decode(self, txt, encoding, return_errors, return_stats)
   4913             errors = [err for err in state.errors if err.severity in ('fatal','error')]
   4914             if errors:
-> 4915                 raise errors[0]
   4916             if return_stats:
   4917                 return result_type(state.obj, None, state.stats)

JSONDecodeError: Missing value for object property, expected ":"

第二个错误在其他接口也经常出现

望查收，修复，感谢

**Comment by jindaxiang** [comment]
> 163406

感谢反馈问题
1. 问题1：是由于该 http://fund.eastmoney.com/000905.html 没有净值数据
2. 问题2：运行正常，未发现反馈的问题

**Comment by HanMuJiang** [comment]
你好：
&nbsp; &nbsp; &nbsp; 收到来信，非常感谢！
&nbsp; &nbsp; &nbsp; 我在两周前调用公募基金历史数据的接口，前两周正常，最近几天怎么跑都失败，麻烦看下正常吗？
&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;我用官文档的例子跑的，如下：






场内基金








&nbsp; &nbsp;可否帮我看下哪里有问题吗？非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jindaxiang/akshare"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月7日(星期四) 下午5:02
收件人:&nbsp;"jindaxiang/akshare"<akshare@noreply.github.com&gt;;
抄送:&nbsp;"北京师范大学软件工程硕士韩龙"<2282470722@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jindaxiang/akshare] 公募基金--基本净值--历史净值。历史净值接口不能用了，（发现时间：2021-1-3） (#881)





  
163406
  
感谢反馈问题
  
问题1：是由于该 http://fund.eastmoney.com/000905.html 没有净值数据
 
问题2：运行正常，未发现反馈的问题

**Comment by HanMuJiang** [comment]
你好：
&nbsp; &nbsp; &nbsp; 重新换了电脑，安装新的包，依旧报错啊，！！！！麻烦看下是不是接口的问题？？？？


&nbsp; &nbsp; &nbsp; 我在两周前调用公募基金历史数据的接口，前两周正常，最近几天怎么跑都失败，麻烦看下正常吗？
&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp;我用官文档的例子跑的，如下：






场内基金








&nbsp; &nbsp;可否帮我看下哪里有问题吗？非常感谢




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "jindaxiang/akshare"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月7日(星期四) 下午5:02
收件人:&nbsp;"jindaxiang/akshare"<akshare@noreply.github.com&gt;;
抄送:&nbsp;"北京师范大学软件工程硕士韩龙"<2282470722@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jindaxiang/akshare] 公募基金--基本净值--历史净值。历史净值接口不能用了，（发现时间：2021-1-3） (#881)





  
163406
  
感谢反馈问题
  
问题1：是由于该 http://fund.eastmoney.com/000905.html 没有净值数据
 
问题2：运行正常，未发现反馈的问题

**Comment by jindaxiang** [comment]
> 你好： &nbsp; &nbsp; &nbsp; 重新换了电脑，安装新的包，依旧报错啊，！！！！麻烦看下是不是接口的问题？？？？ &nbsp; &nbsp; &nbsp; 我在两周前调用公募基金历史数据的接口，前两周正常，最近几天怎么跑都失败，麻烦看下正常吗？ &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;我用官文档的例子跑的，如下： 场内基金 &nbsp; &nbsp;可否帮我看下哪里有问题吗？非常感谢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "jindaxiang/akshare" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月7日(星期四) 下午5:02 收件人:&nbsp;"jindaxiang/akshare"<akshare@noreply.github.com&gt;; 抄送:&nbsp;"北京师范大学软件工程硕士韩龙"<2282470722@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [jindaxiang/akshare] 公募基金--基本净值--历史净值。历史净值接口不能用了，（发现时间：2021-1-3） (#881) 163406 感谢反馈问题 问题1：是由于该 http://fund.eastmoney.com/000905.html 没有净值数据 问题2：运行正常，未发现反馈的问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

无法看到你问题
