### ISSUE TITLE
stock_zh_a_minute 获取数据为NaN

### ISSUE THREAD

**Issue by yuxuechao** [jindaxiang/akshare#896]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 w10
2. Python 版本  3.7
3. AkShare 版本 最新master
4. 接口的名称和代码 
5.stock_zh_a_minute（）
 merged_df = pd.merge(temp_df, result_df, left_index=True, right_index=True)
5. 接口报错的截图或代码
![image](https://user-images.githubusercontent.com/24352648/104194320-1c182180-545c-11eb-9d33-88b770918a28.png)
获取数值为Nan
6. 期望获得的正确结果
正常价格

**Comment by jindaxiang** [comment]
> 4\. stock_zh_a_minute

感谢反馈问题，请升级到 AkShare 0.7.74 版本
