### ISSUE TITLE
AkShare 接口问题报告

### ISSUE THREAD

**Issue by gigibang** [jindaxiang/akshare#897]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本 win10
2. Python 版本 Python 3.8.5
3. AkShare 版本 akshare-0.7.73
4. 接口的名称和代码 stock_zh_a_daily
5. 接口报错的截图或代码
6. 
![image](https://user-images.githubusercontent.com/13517101/104263093-f717c300-54dc-11eb-9aa8-27c25bdb9f6c.png)

6. 期望获得的正确结果 可以使用start_date和end_date

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本 win10
> 2. Python 版本 Python 3.8.5
> 3. AkShare 版本 akshare-0.7.73
> 4. 接口的名称和代码 stock_zh_a_daily
> 5. 接口报错的截图或代码
> 
> ![image](https://user-images.githubusercontent.com/13517101/104263093-f717c300-54dc-11eb-9aa8-27c25bdb9f6c.png)
> 
> 1. 期望获得的正确结果 可以使用start_date和end_date

接口测试使用正常
