### ISSUE TITLE
bond_china_yield issue and suggestion

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#9]
Hi,
Thank you for implementing bond_china_yield function.
There are two minor suggestions.
1. currently the function only returns 11 month of data, as shown below.
![image](https://user-images.githubusercontent.com/359830/73849443-f3bd8700-47f7-11ea-879d-7c54a73d09a2.png)

2. would be great to have a signature of bond_china_yield(startdate, enddate)

Just my 2c.
thanks.

**Comment by jindaxiang** [comment]
yeah, It is a very good question, now akshare 0.3.79 version have finish it!
```
import akshare as ak
bond_china_yield_df = bond_china_yield(start_date="2018-01-01", end_date="2019-01-01")
print(bond_china_yield_df)
```
here is the document for this functions: https://akshare.readthedocs.io/zh_CN/latest/data/bond/bond.html#id7
