### ISSUE TITLE
希望市盈率、市净率等姑表指数数据可以添加每天全量采集接口，现在是个股历史，要更新的话，得全量下载，而不能只更新当天

### ISSUE THREAD

**Issue by harryhan1989** [jindaxiang/akshare#909]
希望市盈率、市净率等姑表指数数据可以添加每天全量采集接口，现在是个股历史，要更新的话，得全量下载，而不能只更新当天

**Comment by jindaxiang** [comment]
> 希望市盈率、市净率等姑表指数数据可以添加每天全量采集接口，现在是个股历史，要更新的话，得全量下载，而不能只更新当天

根据现有的数据接口，目前只能做到全量采集
