### ISSUE TITLE
调取历史现货价格和基差接口失败

### ISSUE THREAD

**Issue by allenwoods** [jindaxiang/akshare#917]
#### 系统环境和版本:
```shell
❯ uname
Linux
❯ python -V
Python 3.7.9
❯ pip freeze | grep akshare
akshare==0.7.83
```
#### 问题:
使用生意社接口获取历史基差数据失败
```python
In [1]: import akshare as ak
In [2]: ak.futures_spot_price_daily(start_day="20110110", end_day="20110110", vars_list=["CU", "RB"])
2011-01-10
2011-01-10日生意社数据连接失败，第1次尝试，最多5次
2011-01-10日生意社数据连接失败，第2次尝试，最多5次
2011-01-10日生意社数据连接失败，第3次尝试，最多5次
2011-01-10日生意社数据连接失败，第4次尝试，最多5次
2011-01-10日生意社数据连接失败，第5次尝试，最多5次
2011-01-10日生意社数据连接失败, 如果当前交易日是 2018-09-12, 由于生意社源数据缺失, 无法访问, 否则为重复访问已超过5次，您的地址被网站墙了，请保存好返回数据，稍后从该日期起重试
```
然而, 访问对应网址 http://www.100ppi.com/sf2/day-2011-01-10.html 会发现该日数据存在.

#### 问题猜测和修复方案
问题似乎是由于网址更新引起的: `sf -> sf2`, 同时, 内容格式也有一定变化, 修改`SYS_SPOT_PRICE_URL`无法直接解决问题. 使用以下代码可以获取新API中数据

```python
import datetime
from typing import List
import pandas as pd
from akshare.futures.requests_fun import pandas_read_html_link as read_link

def join_head(content: pd.DataFrame) -> List:
    headers = []
    for s1, s2 in zip(content.iloc[0], content.iloc[1]):
        if s1 != s2:
            s = f'{s1}{s2}'
        else:
            s = s1
        headers.append(s)
    return headers

def get_basis(date: datetime.datetime) -> pd.DataFrame:
    url = date.strftime('http://www.100ppi.com/sf2/day-%Y-%m-%d.html')
    content = read_link(url)
    main = content[1]
    # Header
    header = join_head(main)
    # Values
    values = main[main[4].str.endswith('%')]
    values.columns = header
    # Basis
    basis = pd.concat(content[2:-1])
    basis.columns = ['主力合约基差', '主力合约基差(%)']
    basis['商品'] = values['商品'].tolist()
    basis = pd.merge(values[["商品", "现货价格", "主力合约代码", "主力合约价格"]], basis)
    basis = pd.merge(basis, values[["商品", "180日内主力基差最高", "180日内主力基差最低", "180日内主力基差平均"]])
    return basis

if __name__ == '__main__':
    day = datetime.datetime(2011,1,4).date()
    df = get_basis(day)
    print(df)

```
输出为:

  | 商品 | 现货价格 | 主力合约代码 | 主力合约价格 | 主力合约基差 | 主力合约基差(%) | 180日内主力基差最高 | 180日内主力基差最低 | 180日内主力基差平均
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 铜 | 70350 | 1104 | 72510 | -2160 | -3.07% | NaN | NaN | NaN
1 | 螺纹钢 | 0 | 1105 | 4823 | -4823 | 0.00% | NaN | NaN | NaN
2 | 锌 | 19100 | 1104 | 19795 | -695 | -3.64% | NaN | NaN | NaN
3 | 铝 | 16300 | 1103 | 16890 | -590 | -3.62% | NaN | NaN | NaN
4 | 黄金 | 302.15 | 1106 | 308.13 | -5 | -1.65% | NaN | NaN | NaN
5 | 线材 | 0 | 1105 | 4779 | -4779 | 0.00% | NaN | NaN | NaN
6 | 燃料油 | 4702.5 | 1103 | 4786 | -83 | -1.77% | NaN | NaN | NaN
7 | 天然橡胶 | 36000 | 1105 | 37455 | -1455 | -4.04% | NaN | NaN | NaN
8 | PTA | 9850 | TA105 | 10544 | -694 | -7.05% | 630 | -2054 | -439.62
9 | 白糖 | 0 | SR109 | 7216 | -7216 | 0.00% | NaN | NaN | NaN
10 | 棉花 | 27500 | CF109 | 28125 | -625 | -2.27% | NaN | NaN | NaN
11 | 菜籽油 | 0 | RO105 | 10456 | -10456 | 0.00% | NaN | NaN | NaN
12 | 硬麦 | 0 | WT105 | 2192 | -2192 | 0.00% | NaN | NaN | NaN
13 | 棕榈油 | 0 | 1109 | 9896 | -9896 | 0.00% | NaN | NaN | NaN
14 | 聚氯乙烯 | 8070 | 1105 | 8480 | -410 | -5.08% | NaN | NaN | NaN
15 | 聚乙烯 | 11125 | 1105 | 12620 | -1495 | -13.44% | NaN | NaN | NaN
16 | 豆一 | 0 | 1201 | 4516 | -4516 | 0.00% | NaN | NaN | NaN
17 | 豆粕 | 3450 | 1109 | 3434 | 16 | 0.46% | NaN | NaN | NaN
18 | 豆油 | 0 | 1109 | 10588 | -10588 | 0.00% | NaN | NaN | NaN
19 | 玉米 | 1860 | 1109 | 2339 | -479 | -25.75% | NaN | NaN | NaN

**Comment by jindaxiang** [comment]
> ```python
>     day = datetime.datetime(2011,1,4).date()
>     df = get_basis(day)
>     print(df)
> ```

非常感谢反馈问题，由于原网站不再提供该数据，只能获取近期年份的数据；
升级到 AkShare 0.7.85 版本，新增 futures_spot_price_previous 函数，该函数目前是根据您提供的代码修改，暂时可以使用，后续会统一修正后正式写入文档
