### ISSUE TITLE
AkShare 接口问题报告: 部分港股的qfq和hfq颠倒

### ISSUE THREAD

**Issue by nangongwubu** [jindaxiang/akshare#927]
港股中芯国际00981的qfq和hfq反了
ak.stock_hk_daily(symbol='00981', adjust="qfq")
-------------------------------------------------

open | high | low | close | volume
-- | -- | -- | -- | --

24.25 | 25.50 | 24.00 | 24.75 | 966484000.0
24.25 | 24.25 | 23.00 | 23.25 | 359188000.0
22.25 | 22.25 | 21.00 | 21.00 | 268134000.0
21.50 | 23.50 | 21.25 | 22.75 | 275087200.0
23.00 | 24.00 | 23.00 | 23.25 | 168859000.0
... | ... | ... | ... | ...
260.00 | 270.00 | 254.00 | 270.00 | 164619864.0
276.00 | 280.00 | 251.00 | 262.00 | 166048380.0
265.50 | 282.00 | 264.50 | 281.50 | 184938215.0
284.00 | 289.50 | 267.00 | 276.50 | 181322903.0
278.50 | 295.00 | 277.50 | 292.50 | 153883173.0

**Comment by jindaxiang** [comment]
> ## 港股中芯国际00981的qfq和hfq反了
> ak.stock_hk_daily(symbol='00981', adjust="qfq")
> open	high	low	close	volume
> 24.25 | 25.50 | 24.00 | 24.75 | 966484000.0
> 24.25 | 24.25 | 23.00 | 23.25 | 359188000.0
> 22.25 | 22.25 | 21.00 | 21.00 | 268134000.0
> 21.50 | 23.50 | 21.25 | 22.75 | 275087200.0
> 23.00 | 24.00 | 23.00 | 23.25 | 168859000.0
> ... | ... | ... | ... | ...
> 260.00 | 270.00 | 254.00 | 270.00 | 164619864.0
> 276.00 | 280.00 | 251.00 | 262.00 | 166048380.0
> 265.50 | 282.00 | 264.50 | 281.50 | 184938215.0
> 284.00 | 289.50 | 267.00 | 276.50 | 181322903.0
> 278.50 | 295.00 | 277.50 | 292.50 | 153883173.0

由于该股票的复权因子数据问题，正在处理

**Comment by jindaxiang** [comment]
> ## 港股中芯国际00981的qfq和hfq反了
> ak.stock_hk_daily(symbol='00981', adjust="qfq")
> open	high	low	close	volume
> 24.25 | 25.50 | 24.00 | 24.75 | 966484000.0
> 24.25 | 24.25 | 23.00 | 23.25 | 359188000.0
> 22.25 | 22.25 | 21.00 | 21.00 | 268134000.0
> 21.50 | 23.50 | 21.25 | 22.75 | 275087200.0
> 23.00 | 24.00 | 23.00 | 23.25 | 168859000.0
> ... | ... | ... | ... | ...
> 260.00 | 270.00 | 254.00 | 270.00 | 164619864.0
> 276.00 | 280.00 | 251.00 | 262.00 | 166048380.0
> 265.50 | 282.00 | 264.50 | 281.50 | 184938215.0
> 284.00 | 289.50 | 267.00 | 276.50 | 181322903.0
> 278.50 | 295.00 | 277.50 | 292.50 | 153883173.0

感谢反馈问题，请升级到 AkShare 0.7.89 版本
