### ISSUE TITLE
“中国股票指数成份-最新成份” 获取的成份出现重复

### ISSUE THREAD

**Issue by GuoShihanRicky** [jindaxiang/akshare#928]
`ak.index_stock_cons(index="000300")`
获取000300指数成份，输出DataFrame有300行，但是其中有重复数据，如“000651”格力电器出现两次；同时有数据缺失，如“000066”中国长城。
![image](https://user-images.githubusercontent.com/50944657/105005634-90604f80-5a70-11eb-87d1-630641d86bcf.png)

**Comment by jindaxiang** [comment]
> `ak.index_stock_cons(index="000300")`
> 获取000300指数成份，输出DataFrame有300行，但是其中有重复数据，如“000651”格力电器出现两次；同时有数据缺失，如“000066”中国长城。
> ![image](https://user-images.githubusercontent.com/50944657/105005634-90604f80-5a70-11eb-87d1-630641d86bcf.png)

是的，这是由于数据源的问题，已经在文档接口中进行说明
