### ISSUE TITLE
bond_spot_deal 成交量数据无法获取

### ISSUE THREAD

**Issue by uestcmee** [jindaxiang/akshare#939]
同业交易中心在更新成交量数据之后，使用 `ak.bond_spot_deal()`仍然无法获取成交量数据

尝试将`china_bond.py`中的`bond_spot_deal`函数中`keys_list`变量中的`dmiPrvsClsngContraRate`修改为`dmiTtlTradedAmntLabel`可以解决问题。

**Comment by jindaxiang** [comment]
> bond_spot_deal

感谢反馈问题，请升级到 AkShare 0.7.97 版本，已修复
