### ISSUE TITLE
建议stock_report_fund_hold函数增加一个空值判断

### ISSUE THREAD

**Issue by flybobdog** [jindaxiang/akshare#945]
**Describe the bug**
stock_report_fund_hold在获取最新一个季度的持仓数据时，会因为没有数据，获得一个空的数据，并抛出错误。

’ ValueError: Length mismatch: Expected axis has 1 elements, new values have 14 elements‘
这样想批量获得多种机构的持仓数据就会被中断。
所以我建议增加一个空值判断，跳过空值。
`r = requests.get(url, params=params)
  data_text = r.text
  data_json = demjson.decode(data_text[data_text.find("{"):])
  if data_json['data']==[]:
      return
  temp_df = pd.DataFrame(data_json["data"])`

**Comment by jindaxiang** [comment]
> **Describe the bug**
> stock_report_fund_hold在获取最新一个季度的持仓数据时，会因为没有数据，获得一个空的数据，并抛出错误。
> 
> ’ ValueError: Length mismatch: Expected axis has 1 elements, new values have 14 elements‘
> 这样想批量获得多种机构的持仓数据就会被中断。
> 所以我建议增加一个空值判断，跳过空值。
> `r = requests.get(url, params=params) data_text = r.text data_json = demjson.decode(data_text[data_text.find("{"):]) if data_json['data']==[]: return temp_df = pd.DataFrame(data_json["data"])`

提供下测试的代码看看，具体什么错误

**Comment by jindaxiang** [comment]
> **Describe the bug**
> stock_report_fund_hold在获取最新一个季度的持仓数据时，会因为没有数据，获得一个空的数据，并抛出错误。
> 
> ’ ValueError: Length mismatch: Expected axis has 1 elements, new values have 14 elements‘
> 这样想批量获得多种机构的持仓数据就会被中断。
> 所以我建议增加一个空值判断，跳过空值。
> `r = requests.get(url, params=params) data_text = r.text data_json = demjson.decode(data_text[data_text.find("{"):]) if data_json['data']==[]: return temp_df = pd.DataFrame(data_json["data"])`

感谢反馈问题，请升级到 AkShare 0.7.98 版本，已修复
