### ISSUE TITLE
没有news_cctv接口

### ISSUE THREAD

**Issue by w0807c** [jindaxiang/akshare#946]
Traceback (most recent call last):
  File "D:/My_Workspaces/untitled3/Page.py", line 18, in <module>
    news_cctv_df = ak.news_cctv(date="20210123")
AttributeError: module 'akshare' has no attribute 'news_cctv'

**Comment by jindaxiang** [comment]
> Traceback (most recent call last):
> File "D:/My_Workspaces/untitled3/Page.py", line 18, in
> news_cctv_df = ak.news_cctv(date="20210123")
> AttributeError: module 'akshare' has no attribute 'news_cctv'

需要升级到最新版
