### ISSUE TITLE
feature: [郑商所数据]

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#950]
您好，
请问akshare 有没有计划加入 郑商所的一些数据，比如 期货转现货统计数据？包括所有历史查询
http://www.czce.com.cn/cn/jysj/qzxtj/H770311index_1.htm
还有交割配对统计 http://www.czce.com.cn/cn/jysj/jgpd/H770308index_1.htm
![image](https://user-images.githubusercontent.com/359830/105750620-ef95f680-5f7f-11eb-8f2b-83e8a0d32fb4.png)

交割量 http://www.czce.com.cn/cn/jysj/ydjgcx/H770316index_1.htm
谢谢

**Comment by jindaxiang** [comment]
> 您好，
> 请问akshare 有没有计划加入 郑商所的一些数据，比如 期货转现货统计数据？包括所有历史查询
> http://www.czce.com.cn/cn/jysj/qzxtj/H770311index_1.htm
> 还有交割配对统计 http://www.czce.com.cn/cn/jysj/jgpd/H770308index_1.htm
> ![image](https://user-images.githubusercontent.com/359830/105750620-ef95f680-5f7f-11eb-8f2b-83e8a0d32fb4.png)
> 
> 交割量 http://www.czce.com.cn/cn/jysj/ydjgcx/H770316index_1.htm
> 谢谢

感谢反馈问题，请升级到 AkShare 0.8.9 版本，目前已经更新：futures_to_spot_czce,  futures_to_spot_shfe, 
 futures_delivery_dce,  futures_delivery_czce,  futures_delivery_match_dce,  futures_delivery_match_czce；详情访问
https://www.akshare.xyz/zh_CN/latest/data/futures/futures.html#id34
