### ISSUE TITLE
feature:[大商所数据]

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#951]
您好，
请问akshare有计划加入大商所的交割数据吗？包括交割配对表和交割数据

http://www.dce.com.cn/dalianshangpin/xqsj/tjsj26/jgtj/jgpdb/index.html
http://www.dce.com.cn/dalianshangpin/xqsj/tjsj26/jgtj/jgsj/index.html

谢谢

**Comment by jindaxiang** [comment]
> 您好，
> 请问akshare有计划加入大商所的交割数据吗？包括交割配对表和交割数据
> 
> http://www.dce.com.cn/dalianshangpin/xqsj/tjsj26/jgtj/jgpdb/index.html
> http://www.dce.com.cn/dalianshangpin/xqsj/tjsj26/jgtj/jgsj/index.html
> 
> 谢谢

感谢反馈问题，请升级到 AkShare 0.8.9 版本，目前已经更新：futures_to_spot_czce,  futures_to_spot_shfe, 
 futures_delivery_dce,  futures_delivery_czce,  futures_delivery_match_dce,  futures_delivery_match_czce；详情访问
https://www.akshare.xyz/zh_CN/latest/data/futures/futures.html#id34
