### ISSUE TITLE
feature:[上期所统计]

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#952]
您好，
请问akshare 有计划加入这些上期所的数据吗，包括交割量和期转现量？
http://www.shfe.com.cn/statements/dataview.html?paramid=kx
![image](https://user-images.githubusercontent.com/359830/105750096-3a633e80-5f7f-11eb-9764-7db4820f5b7e.png)

谢谢

**Comment by jindaxiang** [comment]
> 您好，
> 请问akshare 有计划加入这些上期所的数据吗，包括交割量和期转现量？
> http://www.shfe.com.cn/statements/dataview.html?paramid=kx
> ![image](https://user-images.githubusercontent.com/359830/105750096-3a633e80-5f7f-11eb-9764-7db4820f5b7e.png)
> 
> 谢谢

感谢反馈问题，请升级到 AkShare 0.8.9 版本，目前已经更新：futures_to_spot_czce,  futures_to_spot_shfe, 
 futures_delivery_dce,  futures_delivery_czce,  futures_delivery_match_dce,  futures_delivery_match_czce；详情访问
https://www.akshare.xyz/zh_CN/latest/data/futures/futures.html#id34
