### ISSUE TITLE
[feature]上期所交割情况

### ISSUE THREAD

**Issue by edwardsun** [jindaxiang/akshare#972]
您好，
请问akshare有没有计划加入上期所的交割数据？
http://www.shfe.com.cn/statements/dataview.html?paramid=kx
![image](https://user-images.githubusercontent.com/359830/106683534-ae5ea180-6592-11eb-8a5c-e2ee4d3ae63a.png)
谢谢

**Comment by jindaxiang** [comment]
> kx

没有找到该数据，请提供详细的地址

**Comment by edwardsun** [comment]
您好，
好像需要打开链接 http://www.shfe.com.cn/statements/dataview.html?paramid=kx ，选择日期，然后点击月度统计
![image](https://user-images.githubusercontent.com/359830/106770430-edffb900-6678-11eb-94f3-b08e965f82e6.png)
我选的是上个月月末，就有这个交割数据。

**Comment by jindaxiang** [comment]
> 您好，
> 好像需要打开链接 http://www.shfe.com.cn/statements/dataview.html?paramid=kx ，选择日期，然后点击月度统计
> ![image](https://user-images.githubusercontent.com/359830/106770430-edffb900-6678-11eb-94f3-b08e965f82e6.png)
> 我选的是上个月月末，就有这个交割数据。

感谢提供地址，请升级到 AkShare 0.8.12 版本使用
