### ISSUE TITLE
stock_em_hsgt_stock_statistics

### ISSUE THREAD

**Issue by heyfavour** [jindaxiang/akshare#974]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by heyfavour** [comment]
stock_em_hsgt_stock_statistics 如果是周末没有数据的时候，会抛异常，希望能对数据为空返回空就好了而不是报错

**Comment by jindaxiang** [comment]
> stock_em_hsgt_stock_statistics

请在本地自行处理
