### ISSUE TITLE
import akshare报错

### ISSUE THREAD

**Issue by zyuerugou** [jindaxiang/akshare#977]
**Describe the bug**
import akshare 报错

**Desktop (please complete the following information):**
 - OS:WIN7旗舰版
 - Version 
 -   akshare:0.8.11
 -   py_mini_racer:0.4.0
 
**报错**

---------------------------------------------------------------------------
`
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-c3439955029c> in <module>
----> 1 import akshare as ak

d:\python\lib\site-packages\akshare-0.8.11-py3.7.egg\akshare\__init__.py in <module>
   1466 A 股PE和PB
   1467 """
-> 1468 from akshare.stock_feature.stock_a_pb import stock_a_pb
   1469 from akshare.stock_feature.stock_a_pe import stock_a_pe
   1470 from akshare.stock_feature.stock_a_indicator import (

d:\python\lib\site-packages\akshare-0.8.11-py3.7.egg\akshare\stock_feature\stock_a_pb.py in <module>
    315 }
    316 """
--> 317 ctx = py_mini_racer.MiniRacer()
    318 ctx.eval(hash_code)
    319 token = ctx.call("hex", datetime.now().date().isoformat()).lower()

d:\python\lib\site-packages\py_mini_racer-0.4.0-py3.7.egg\py_mini_racer\py_mini_racer.py in __init__(self)
    166         """ Init a JS context """
    167 
--> 168         self.ext = _fetch_ext_handle()
    169         self.ctx = self.ext.mr_init_context()
    170         self.lock = threading.Lock()

d:\python\lib\site-packages\py_mini_racer-0.4.0-py3.7.egg\py_mini_racer\py_mini_racer.py in _fetch_ext_handle()
    121 
    122     if EXTENSION_PATH is None or not os.path.exists(EXTENSION_PATH):
--> 123         raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
    124     _ext_handle = ctypes.CDLL(EXTENSION_PATH)
    125 

RuntimeError: Native library not available at d:\python\lib\site-packages\py_mini_racer-0.4.0-py3.7.egg\py_mini_racer\mini_racer.dll
`

**Comment by jindaxiang** [comment]
> **Describe the bug**
> import akshare 报错
> 
> **Desktop (please complete the following information):**
> 
> * OS:WIN7旗舰版
> * Version
> * akshare:0.8.11
> * py_mini_racer:0.4.0
> 
> **报错**
> 
> `
> RuntimeError Traceback (most recent call last)
> in
> ----> 1 import akshare as ak
> 
> d:\python\lib\site-packages\akshare-0.8.11-py3.7.egg\akshare__init__.py in
> 1466 A 股PE和PB
> 1467 """
> -> 1468 from akshare.stock_feature.stock_a_pb import stock_a_pb
> 1469 from akshare.stock_feature.stock_a_pe import stock_a_pe
> 1470 from akshare.stock_feature.stock_a_indicator import (
> 
> d:\python\lib\site-packages\akshare-0.8.11-py3.7.egg\akshare\stock_feature\stock_a_pb.py in
> 315 }
> 316 """
> --> 317 ctx = py_mini_racer.MiniRacer()
> 318 ctx.eval(hash_code)
> 319 token = ctx.call("hex", datetime.now().date().isoformat()).lower()
> 
> d:\python\lib\site-packages\py_mini_racer-0.4.0-py3.7.egg\py_mini_racer\py_mini_racer.py in **init**(self)
> 166 """ Init a JS context """
> 167
> --> 168 self.ext = _fetch_ext_handle()
> 169 self.ctx = self.ext.mr_init_context()
> 170 self.lock = threading.Lock()
> 
> d:\python\lib\site-packages\py_mini_racer-0.4.0-py3.7.egg\py_mini_racer\py_mini_racer.py in _fetch_ext_handle()
> 121
> 122 if EXTENSION_PATH is None or not os.path.exists(EXTENSION_PATH):
> --> 123 raise RuntimeError("Native library not available at {}".format(EXTENSION_PATH))
> 124 _ext_handle = ctypes.CDLL(EXTENSION_PATH)
> 125
> 
> RuntimeError: Native library not available at d:\python\lib\site-packages\py_mini_racer-0.4.0-py3.7.egg\py_mini_racer\mini_racer.dll
> `

64 位版本的 Python

**Comment by bobyang-code** [comment]
同类问题
