### ISSUE TITLE
增加提取新浪财务基础三表的功能

### ISSUE THREAD

**Issue by lianzhaowen** [jindaxiang/akshare#981]
https://vip.stock.finance.sina.com.cn/corp/go.php/vFD_FinanceSummary/stockid/600004.phtml

希望能增加 资产负债表，利润表及现金流量表的功能

**Comment by jindaxiang** [comment]
> https://vip.stock.finance.sina.com.cn/corp/go.php/vFD_FinanceSummary/stockid/600004.phtml
> 
> 希望能增加 资产负债表，利润表及现金流量表的功能

感谢反馈问题，请升级到 AKShare 0.8.17 版本使用: https://docs.akshare.top/data/stock/stock.html#id84
