### ISSUE TITLE
fund_em_open_fund_rank 接口是否可以增加参数 

### ISSUE THREAD

**Issue by lightcax** [jindaxiang/akshare#982]
在 fund_em_open_fund_rank 增加参数，参数控制："ft": "all","sc": "zzf",
全部/股票型/混合型/债券型/指数型/QDII/LOF/FOF/

现在返回数据无法分辨哪类基金。谢谢

fund_em_rank.py 

def fund_em_open_fund_rank() -> pd.DataFrame:
    """
    东方财富网-数据中心-开放式基金排行
    http://fund.eastmoney.com/data/fundranking.html
    :return: 开放式基金排行数据
    :rtype: pandas.DataFrame
    """
    current_date = datetime.datetime.now().date().isoformat()
    last_date = str(int(current_date[:4]) - 1) + current_date[4:]
    url = "http://fund.eastmoney.com/data/rankhandler.aspx"
    params = {
        "op": "ph",
        "dt": "kf",
        "ft": "all",
        "rs": "",
        "gs": "0",
        "sc": "zzf",

**Comment by jindaxiang** [comment]
> 在 fund_em_open_fund_rank 增加参数，参数控制："ft": "all","sc": "zzf",
> 全部/股票型/混合型/债券型/指数型/QDII/LOF/FOF/
> 
> 现在返回数据无法分辨哪类基金。谢谢
> 
> fund_em_rank.py
> 
> def fund_em_open_fund_rank() -> pd.DataFrame:
> """
> 东方财富网-数据中心-开放式基金排行
> http://fund.eastmoney.com/data/fundranking.html
> :return: 开放式基金排行数据
> :rtype: pandas.DataFrame
> """
> current_date = datetime.datetime.now().date().isoformat()
> last_date = str(int(current_date[:4]) - 1) + current_date[4:]
> url = "http://fund.eastmoney.com/data/rankhandler.aspx"
> params = {
> "op": "ph",
> "dt": "kf",
> "ft": "all",
> "rs": "",
> "gs": "0",
> "sc": "zzf",

感谢反馈该问题，请升级到 AKShare 0.8.14 版本使用
