### ISSUE TITLE
沪深港股通的资金流向优化建议

### ISSUE THREAD

**Issue by royburns** [jindaxiang/akshare#985]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

当日净买额的准确性要高于当日净流入

![image](https://user-images.githubusercontent.com/652375/107108990-78157080-6877-11eb-9f3c-bb295de025e2.png)

http://data.eastmoney.com/hsgt/index.html

**Describe alternatives you've considered**

**Additional context**

**Comment by jindaxiang** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> 
> 当日净买额的准确性要高于当日净流入
> 
> ![image](https://user-images.githubusercontent.com/652375/107108990-78157080-6877-11eb-9f3c-bb295de025e2.png)
> 
> http://data.eastmoney.com/hsgt/index.html
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

请提供更完善的信息，版本，接口等
