### ISSUE TITLE
AkShare 接口问题报告  stock_szse_summary

### ISSUE THREAD

**Issue by wygzcom** [jindaxiang/akshare#995]
**遇到任何问题，请先确认您的 AkShare 版本是最新的**
```
pip install akshare --upgrade  # Python 版本需要大于 3.7
```

**描述遇到的问题**
1. 操作系统版本
    ubuntu 2020
2. Python 版本
    3.9.1
3. AkShare 版本
    0.8.20
4. 接口的名称和代码
    stock_szse_summary()
5. 接口报错的截图或代码
            Python 3.9.1 (default, Dec 11 2020, 14:32:07) 
            [GCC 7.3.0] :: Anaconda, Inc. on linux
            Type "help", "copyright", "credits" or "license" for more information.
            >>> import akshare as ak
            >>> stock_szse_summary_df = ak.stock_szse_summary(date="20200619")
            /home/xx/miniconda3/envs/py39/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:214: UserWarning: Workbook contains no default style, apply openpyxl's default
              warn("Workbook contains no default style, apply openpyxl's default")
            >>> print(stock_szse_summary_df)
            Empty DataFrame
            Columns: [证券类别]
            Index: []
6. 期望获得的正确结果

**Comment by jindaxiang** [comment]
> **遇到任何问题，请先确认您的 AkShare 版本是最新的**
> 
> ```
> pip install akshare --upgrade  # Python 版本需要大于 3.7
> ```
> 
> **描述遇到的问题**
> 
> 1. 操作系统版本
>    ubuntu 2020
> 2. Python 版本
>    3.9.1
> 3. AkShare 版本
>    0.8.20
> 4. 接口的名称和代码
>    stock_szse_summary()
> 5. 接口报错的截图或代码
>    Python 3.9.1 (default, Dec 11 2020, 14:32:07)
>    [GCC 7.3.0] :: Anaconda, Inc. on linux
>    Type "help", "copyright", "credits" or "license" for more information.
>    >>> import akshare as ak
>    >>> stock_szse_summary_df = ak.stock_szse_summary(date="20200619")
>    /home/xx/miniconda3/envs/py39/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:214: UserWarning: Workbook contains no default style, apply openpyxl's default
>    warn("Workbook contains no default style, apply openpyxl's default")
>    >>> print(stock_szse_summary_df)
>    Empty DataFrame
>    Columns: [证券类别]
>    Index: []
> 6. 期望获得的正确结果

感谢反馈问题，请升级到 AKShare 0.8.21 版本使用，已修复
