### ISSUE TITLE
Akshare_ak.stock_zh_a_daily()接口问题反馈 bug

### ISSUE THREAD

**Issue by rainsweets** [jindaxiang/akshare#996]
<span role="presentation">    <span class="cm-variable">ak</span>.<span class="cm-property">stock_zh_a_daily</span>(<span class="cm-variable">symbol</span><span class="cm-operator">=</span><span class="cm-string">"sz000592"</span>, <span class="cm-variable">start_date</span><span class="cm-operator">=</span><span class="cm-string">"20201106"</span>, <span class="cm-variable">end_date</span><span class="cm-operator">=</span><span class="cm-string">"20201110"</span>,<span class="cm-variable">adjust</span> <span class="cm-operator">=</span> <span class="cm-string">"qfq"</span>)</span>
<div class="output_subarea output_html rendered_html output_result" dir="auto"><div>

<table class="dataframe" border="1">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>open</th>
      <th>high</th>
      <th>low</th>
      <th>close</th>
      <th>volume</th>
      <th>outstanding_share</th>
      <th>turnover</th>
    </tr>
    <tr>
      <th>date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2020-11-06</th>
      <td>2.81</td>
      <td>2.81</td>
      <td>2.75</td>
      <td>2.79</td>
      <td>19904200.0</td>
      <td>1.913847e+09</td>
      <td>0.010400</td>
    </tr>
    <tr>
      <th>2020-11-10</th>
      <td>2.87</td>
      <td>2.88</td>
      <td>2.79</td>
      <td>2.81</td>
      <td>27543917.0</td>
      <td>1.913847e+09</td>
      <td>0.014392</td>
    </tr>
  </tbody>
</table>
</div></div>

缺少数据2020/11/09
ak share version 0.8.4
问题原因：
anaconda3\envs\Astock\Lib\site-packages\akshare\stock\zh_stock_a_sina.py->
def stock_zh_a_daily(
    symbol: str = "sz000001",
    start_date: str = "19900101",
    end_date: str = "21000118",
    adjust: str = "hfq",
) -> pd.DataFrame:
爬虫数据没有问题，包含2020.11.9
line：183 temp_df.drop_duplicates(subset=["open", "high", "low", "close"], inplace=True)
line：212 temp_df.drop_duplicates(subset=["open", "high", "low", "close"], inplace=True)
去重部分删除了重复数据： 股票代码：sz000592  
             open   high    low  close       volume  outstanding_share  \
date   

2019-08-12   2.80   2.86   2.79   2.84   12048200.0       1.913824e+09   

2020-11-09   2.80   2.86   2.79   2.84   28755489.0       1.913847e+09   
造成2020-11-09丢失

**Comment by jindaxiang** [comment]
> 20201110

感谢反馈问题，请升级到 AKShare 0.8.22，已修复
